export const client = `
document.querySelectorAll('video[data-autoplay]').forEach(video=>{video.addEventListener('playing',()=>video.classList.add('playing'));const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting&&window.matchMedia('(prefers-reduced-motion: no-preference)').matches){video.play().catch(()=>{});}else video.pause();}},{threshold:.35});observer.observe(video)});

const catalog=document.querySelector('[data-catalog]');
if(catalog){const cards=[...catalog.querySelectorAll('[data-artist-card]')], search=document.querySelector('#artist-search'), filters=[...document.querySelectorAll('[data-craft-filter]')], none=document.querySelector('#artist-no-results');let craft='All';function update(){const term=(search?.value||'').trim().toLocaleLowerCase();let visible=0;for(const card of cards){const show=(craft==='All'||card.dataset.craft===craft)&&(!term||card.dataset.search.toLocaleLowerCase().includes(term));card.hidden=!show;if(show)visible++}none.hidden=visible>0}search?.addEventListener('input',update);filters.forEach(button=>button.addEventListener('click',()=>{craft=button.dataset.craftFilter;filters.forEach(b=>b.setAttribute('aria-pressed',String(b===button)));update()}));update()}

const form=document.querySelector('#application-form');
if(form){const steps=[...form.querySelectorAll('fieldset[data-step]')], status=form.querySelector('[role="status"]'), progress=[...form.querySelectorAll('.form-progress span')], next=form.querySelector('[data-next]'), back=form.querySelector('[data-back]'), submit=form.querySelector('[type="submit"]');let step=0;
function show(index){step=index;steps.forEach((section,i)=>{section.hidden=i!==step;section.disabled=i!==step});progress.forEach((part,i)=>part.classList.toggle('done',i<=step));back.hidden=step===0;next.hidden=step===steps.length-1;submit.hidden=step!==steps.length-1;status.textContent='';steps[step].scrollIntoView({block:'start',behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':'smooth'})}
function validStep(){const fields=[...steps[step].querySelectorAll('input,select,textarea')];if(step===0)fields.push(...form.querySelectorAll('[data-contact] input'));for(const field of fields){if(!field.checkValidity()){field.reportValidity();return false}}return true}
next.addEventListener('click',()=>{if(validStep())show(Math.min(step+1,steps.length-1))});back.addEventListener('click',()=>show(Math.max(step-1,0)));
let accountToken='';
if(form.dataset.flow==='belong'){try{accountToken=localStorage.getItem('espacios_access_token')||''}catch{}if(accountToken){fetch('/api/auth/me',{headers:{Accept:'application/json',Authorization:'Bearer '+accountToken}}).then(r=>r.ok?r.json():null).then(data=>{const user=data?.user||data?.account||data;if(!user)return;const name=form.querySelector('[name="name"]'),email=form.querySelector('[name="email"]');if(name&&!name.value&&typeof user.name==='string')name.value=user.name;if(email&&typeof user.email==='string'){email.value=user.email;email.readOnly=true;email.title='Verified through espacios.me sign-in'}form.dataset.signedIn='true'}).catch(()=>{})}}
form.addEventListener('submit',async event=>{event.preventDefault();if(!validStep())return;steps.forEach(section=>section.disabled=false);const fd=new FormData(form);const answers={};for(const [key,value] of fd){if(!['name','email','website'].includes(key))answers[key]=String(value).trim()}const message=JSON.stringify({version:1,role:form.dataset.flow,answers});if(message.length>3900){show(step);status.textContent='Please shorten a few answers and try again.';return}const body={name:String(fd.get('name')||''),email:String(fd.get('email')||''),role:form.dataset.flow,ref:form.dataset.ref||'',answers,website:String(fd.get('website')||''),requestId:crypto.randomUUID()};steps.forEach((section,i)=>section.disabled=i!==step);submit.disabled=true;submit.textContent='Sending…';status.textContent='';try{const headers={'Content-Type':'application/json'};if(form.dataset.signedIn==='true'&&accountToken)headers.Authorization='Bearer '+accountToken;const response=await fetch('/communiverse/api/applications',{method:'POST',headers,body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error||'Please try again.');form.replaceChildren();const h=document.createElement('h2'),p=document.createElement('p'),ref=document.createElement('p');h.textContent='Thank you for joining the conversation.';p.textContent='Your answers were saved. A person from Communiverse can follow up with you.';ref.className='note';ref.textContent='Reference: '+String(result.reference||'saved');form.append(h,p,ref)}catch(error){status.textContent=error.message||'Could not send your answers. Please try again.';submit.disabled=false;submit.textContent='Send application ↗'}});
}
`;
