export const extraCss = `
 .review-layout{display:grid;grid-template-columns:1.15fr .85fr;gap:18px;align-items:start}.review-panel{background:#fff;border:1px solid #e1e6ed;border-radius:22px;padding:28px}.review-panel h2{font-size:28px;font-weight:400;letter-spacing:-.04em;margin:0 0 16px}.review-item{border-top:1px solid #e7ecf2;padding:18px 0}.review-item h3{font-size:18px;font-weight:400;margin:4px 0}.review-item p{color:#526075;line-height:1.5}.review-actions{display:flex;gap:9px;flex-wrap:wrap}.review-actions button{min-height:42px;padding:9px 16px}.review-panel .field{display:block;margin:14px 0}.review-panel .field input,.review-panel .field select{width:100%;min-height:46px;padding:10px 12px;border:1px solid #dce3ec;border-radius:12px;background:#f8fafd}.review-panel [role=status]{color:#526075;line-height:1.4}.linked-person{padding:8px 0;border-top:1px solid #edf0f4;color:#526075;font-size:13px;overflow-wrap:anywhere}@media(max-width:800px){.review-layout{grid-template-columns:1fr}}
/* The same restrained controls are used across Discover, catalogues and profiles. */
.brand,.nav a,.button,.sample-badge,.catalog-card h2{font-weight:400}
.top{background:rgba(249,250,252,.89)}
.discovery-hero{display:grid;grid-template-columns:minmax(300px,.92fr) minmax(0,2.55fr);gap:clamp(22px,3.7vw,62px);align-items:start;padding:58px 0 34px}
.discovery-copy{padding-top:20px}.discovery-copy h1{font-size:clamp(52px,6.2vw,98px);font-weight:400;letter-spacing:-.075em;line-height:.94;margin:20px 0}.discovery-copy .lead{max-width:360px;font-size:17px;line-height:1.5;color:#636e80}.discovery-copy .button{margin-top:8px}
.showcase{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px}.showcase-tile{min-width:0}.showcase-art{position:relative;border-radius:18px;overflow:visible}.showcase-art>img:first-child{width:100%;aspect-ratio:.79;object-fit:cover;border-radius:18px;background:#e9e4df}.showcase-avatar{position:absolute;left:12px;bottom:-18px;width:72px;height:72px;object-fit:cover;border:4px solid white;border-radius:50%;box-shadow:0 3px 12px #17203322}.showcase-caption{padding:31px 12px 0}.showcase-caption h2{font-size:16px;font-weight:400;margin:0 0 4px}.showcase-caption p{font-size:13px;color:#647086;margin:0 0 3px}.showcase-caption small{color:#7a8492;font-size:11px}.showcase-tile:hover .showcase-art>img:first-child{box-shadow:0 15px 32px #17203317}
.artist-strip-header{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:20px}.artist-strip-header h2{font-size:25px;font-weight:400;margin:0}.artist-strip{display:flex;gap:15px;overflow-x:auto;padding:5px 5px 17px;scroll-snap-type:x proximity}.artist-strip a{flex:0 0 88px;text-align:center;scroll-snap-align:start}.artist-strip img{width:80px;height:80px;border-radius:50%;object-fit:cover;box-shadow:0 0 0 3px white,0 0 0 4px #e0e6ef}.artist-strip span{display:block;font-size:11px;color:#59667a;margin-top:9px;white-space:nowrap}.artist-strip a:hover img{box-shadow:0 0 0 3px white,0 0 0 5px #0862e7}
.discovery-feature{display:grid;grid-template-columns:1.1fr 1.17fr .86fr .86fr;gap:10px;border-radius:21px;overflow:hidden;background:#fff;border:1px solid #e5e9ef;margin-top:20px}.discovery-feature>img{height:310px;width:100%;object-fit:cover}.discovery-feature-copy{padding:28px 24px;display:flex;flex-direction:column;align-items:start}.discovery-feature-copy h2{font-size:31px;font-weight:400;letter-spacing:-.04em;margin:12px 0 8px}.discovery-feature-copy p{font-size:14px;line-height:1.5;color:#606b7b}.discovery-feature-copy .text-link{margin-top:auto}.discovery-feature-note{display:grid;place-items:center;text-align:center;padding:20px;background:#f7f8fa;font:italic 18px Georgia,serif;color:#566173}
.sample-note{font-size:12px;color:#697589;line-height:1.45;margin:13px 0 0}.sample-work-grid{display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px}.sample-work-card{min-width:0}.sample-work-card img{width:100%;aspect-ratio:.93;object-fit:cover;border-radius:15px}.sample-work-card h3{font-size:15px;font-weight:400;margin:10px 0 4px}.sample-work-card p{font-size:12px;color:#667388;margin:0}
.catalog-card{position:relative}.catalog-card .catalog-visual{position:relative;padding:0}.catalog-card .catalog-visual>img:first-child{width:100%;aspect-ratio:1.15;object-fit:cover}.catalog-card .work-portrait{position:absolute;bottom:-27px;left:15px;width:58px;height:58px;aspect-ratio:1;border:3px solid white;border-radius:50%;object-fit:cover;box-shadow:0 2px 7px #17203320}.catalog-card .catalog-body{padding-top:38px}
.profile-gallery{display:grid;grid-template-columns:1fr 1fr;gap:12px}.profile-gallery img{width:100%;aspect-ratio:.86;object-fit:cover;border-radius:20px}.profile-work{margin:38px 0 16px}.profile-work h2{font-weight:400;font-size:28px}.role-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin:25px 0 34px}.role-card{padding:24px;border:1px solid #e2e8ef;border-radius:20px;background:white;min-height:190px;display:flex;flex-direction:column}.role-card h2{font-size:27px;font-weight:400;margin:10px 0}.role-card p{font-size:14px;color:#617087;line-height:1.45}.role-card .text-link{margin-top:auto}
.people-list{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.person-row{background:white;border:1px solid #e6eaf0;border-radius:16px;padding:18px;display:flex;flex-direction:column;gap:5px}.person-row span{font-size:12px;color:#687487}.metric-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.metric-card{background:white;border:1px solid #e2e8ef;border-radius:16px;padding:20px}.metric-card strong{font-size:33px;font-weight:400;display:block}.metric-card span{font-size:13px;color:#687589}.activity-form{max-width:650px;background:white;border:1px solid #e2e8ef;border-radius:20px;padding:25px;display:grid;gap:13px}.activity-form label{display:grid;gap:6px;font-size:13px;color:#4b586a}.activity-form input,.activity-form select{min-height:45px;border:1px solid #dbe3ee;border-radius:10px;padding:10px;background:#fff}.activity-form .button{justify-self:start}
@media(max-width:1040px){.discovery-hero{grid-template-columns:1fr}.discovery-copy{max-width:640px}.discovery-feature{grid-template-columns:1fr 1fr}.discovery-feature>img{height:280px}.sample-work-grid{grid-template-columns:repeat(3,1fr)}.role-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:680px){.discovery-hero{padding:31px 0 22px;gap:22px}.discovery-copy h1{font-size:clamp(48px,13vw,72px)}.discovery-copy .lead{font-size:15px}.showcase{display:flex;overflow-x:auto;scroll-snap-type:x mandatory;padding-bottom:10px;gap:11px}.showcase-tile{flex:0 0 77%;scroll-snap-align:start}.showcase-art>img:first-child{aspect-ratio:1.15}.artist-strip{gap:10px}.artist-strip a{flex-basis:69px}.artist-strip img{width:62px;height:62px}.artist-strip span{font-size:10px}.discovery-feature{grid-template-columns:1fr 1fr}.discovery-feature>img:first-child{grid-column:1/-1;height:270px}.discovery-feature-copy{grid-column:1/-1;grid-row:2;padding:22px}.discovery-feature>img:nth-of-type(2){height:180px}.discovery-feature-note{font-size:14px}.sample-work-grid{grid-template-columns:repeat(2,1fr);gap:10px}.role-grid{grid-template-columns:1fr 1fr;gap:9px}.role-card{padding:17px;min-height:170px}.role-card h2{font-size:21px}.role-card p{font-size:12px}.people-list,.metric-grid{grid-template-columns:1fr}.profile-gallery{gap:8px}.profile-gallery img{border-radius:13px}.top-in{min-height:70px}.brand{font-size:19px}}
@media(prefers-reduced-motion:reduce){.showcase-tile,.sample-work-card{transition:none}}
`;
