import { videoArt } from './video-art.js';

export const RELEASE = '20261007-marketplace-2';
const ROOT = '/communiverse';
const email = 'hello@communiverseclubs.com';
const e = (value) => String(value ?? '').replace(/[&<>"']/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const path = (suffix = '') => `${ROOT}/${suffix}`;
const SCRIPT_PATH = path(`_public/${RELEASE}.js`);
const safeUrl = (value) => {
  try {
    const url = new URL(value, 'https://espacios.me');
    return url.protocol === 'https:' || (url.origin === 'https://espacios.me' && url.protocol === 'http:') ? e(url.href) : '';
  } catch { return ''; }
};
const button = (label, href, secondary = false) => `<a class="button ${secondary ? 'button-secondary' : ''}" href="${e(href)}">${e(label)} <span aria-hidden="true">↗</span></a>`;

const css = `
:root{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Helvetica,Arial,sans-serif;color:#172033;background:#f5f5f7;font-synthesis:none}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;min-width:320px}a{color:inherit;text-decoration:none}button,input,textarea,select{font:inherit}button,a,input,textarea,select{outline-offset:3px}button{cursor:pointer}img,video{display:block;max-width:100%}
.skip{position:absolute;left:12px;top:-80px;background:#fff;padding:12px 18px;z-index:20}.skip:focus{top:12px}
.shell{max-width:1540px;margin:auto;padding:0 clamp(18px,4.9vw,76px)}.top{position:sticky;top:0;z-index:15;background:rgba(245,245,247,.82);backdrop-filter:blur(18px);border-bottom:1px solid #e9edf2}.top-in{display:flex;align-items:center;justify-content:space-between;gap:22px;min-height:82px}.brand{font-size:24px;font-weight:750;letter-spacing:-.055em;white-space:nowrap}.nav{display:flex;align-items:center;gap:4px;padding:5px;border:1px solid #e3e8ef;background:rgba(255,255,255,.88);box-shadow:0 7px 22px rgba(22,33,51,.05);border-radius:99px}.nav a{padding:11px 17px;min-height:44px;display:grid;place-items:center;border-radius:99px;font-size:14px;font-weight:600;white-space:nowrap}.nav a[aria-current=page]{background:#e7f0ff;color:#0758d4}.nav a:hover,.nav a:focus-visible{background:#eef4fc}.join-link{min-width:116px;text-align:center}
.button{display:inline-flex;align-items:center;justify-content:center;gap:22px;min-height:48px;border:0;border-radius:999px;background:#0862e7;color:#fff;padding:12px 24px;font-size:14px;font-weight:680;box-shadow:0 5px 13px rgba(8,98,231,.15);transition:transform .18s ease,background .18s ease}.button:hover{transform:translateY(-2px);background:#004dbe}.button-secondary{background:#fff;color:#172033;border:1px solid #dce2eb;box-shadow:0 3px 9px rgba(22,33,51,.04)}.button-secondary:hover{background:#f6f9ff}.button:focus-visible{outline:3px solid #7eb0ff}
main{min-height:60vh}.eyebrow{font-size:12px;font-weight:760;letter-spacing:.12em;text-transform:uppercase;color:#586b82}.lead{font-size:clamp(16px,1.25vw,19px);line-height:1.55;color:#526075;max-width:50ch}.hero{display:grid;grid-template-columns:minmax(300px,.9fr) minmax(0,1.7fr);gap:clamp(30px,4vw,64px);padding-top:58px;align-items:center}.hero h1,.page-head h1{font-size:clamp(54px,6vw,100px);line-height:.96;letter-spacing:-.072em;margin:18px 0 22px;font-weight:760}.hero h1 span,.page-head h1 span{color:#0862e7}.hero-copy{max-width:540px}.hero-copy .button{margin-top:18px}.hero-art{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:16px;align-items:stretch}.clip-card{min-width:0}.clip-window{aspect-ratio:.77;overflow:hidden;background:#e5e8ed;border-radius:20px;position:relative}.clip-window video{width:100%;height:100%;object-fit:cover}.clip-window::after{content:"";position:absolute;inset:auto 0 0;height:34%;background:linear-gradient(transparent,rgba(0,0,0,.38));pointer-events:none}.clip-label{position:absolute;z-index:1;left:15px;bottom:15px;color:#fff;font-size:12px;font-weight:700;text-shadow:0 1px 5px #0008}.clip-card h3{font-size:17px;letter-spacing:-.025em;margin:13px 0 3px}.clip-card p{margin:0;color:#647086;font-size:13px}.clip-card:nth-child(2){transform:translateY(26px)}.clip-card:nth-child(3){transform:translateY(-10px)}
.section{padding:100px 0 0}.section-head{display:flex;justify-content:space-between;align-items:end;gap:20px;margin-bottom:24px}.section h2,.page-head h1{margin:0}.section h2{font-size:clamp(32px,3.3vw,52px);line-height:1.05;letter-spacing:-.055em}.text-link{font-size:14px;font-weight:700;color:#0758d4;min-height:44px;display:inline-flex;align-items:center;gap:8px}.text-link:hover{text-decoration:underline}.section-intro{max-width:620px;color:#526075;line-height:1.55;margin:12px 0 0}.four-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.way-card{background:#fff;border:1px solid #e5e9ee;border-radius:22px;min-height:258px;padding:26px;display:flex;flex-direction:column;justify-content:space-between;box-shadow:0 4px 16px #17203307}.way-card:nth-child(1){background:#fff5ee}.way-card:nth-child(2){background:#f3efff}.way-card:nth-child(3){background:#eaf6f3}.way-card:nth-child(4){background:#fff1f4}.way-card strong{font-size:15px;color:#0064b7}.way-card h3{font-size:31px;letter-spacing:-.055em;margin:0 0 10px}.way-card p{font-size:15px;line-height:1.45;color:#526075;margin:0}.way-card:hover{transform:translateY(-3px);transition:transform .2s ease}
.film-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:14px}.film{border-radius:19px;background:#fff;border:1px solid #e5e9ee;overflow:hidden}.film .clip-window{aspect-ratio:1.2;border-radius:0}.film-body{padding:15px 17px 18px}.film h3{font-size:17px;line-height:1.2;margin:0 0 5px;letter-spacing:-.025em}.film p{font-size:13px;color:#607086;margin:0}.film video{background:#dadfe7}.note{font-size:13px;color:#647086;line-height:1.5}
.feature{display:grid;grid-template-columns:1.1fr .9fr;overflow:hidden;border-radius:28px;background:#e8efff;border:1px solid #dce5f3;min-height:360px}.feature-media{min-height:300px;background:#ded5ca}.feature-media video{width:100%;height:100%;object-fit:cover}.feature-copy{padding:clamp(30px,5vw,68px);align-self:center}.feature-copy h2{font-size:clamp(33px,3.8vw,56px);line-height:1.04;letter-spacing:-.055em;margin:12px 0}.feature-copy p{color:#526075;line-height:1.55;max-width:45ch}.feature-copy .button{margin-top:12px}
.page-head{padding:72px 0 44px;max-width:800px}.page-head h1{font-size:clamp(48px,6vw,82px);margin:15px 0 18px}.pill-row{display:flex;gap:8px;flex-wrap:wrap;margin-top:24px}.pill{display:inline-flex;align-items:center;min-height:38px;border-radius:999px;background:#fff;border:1px solid #dfe5ed;padding:8px 14px;font-size:13px;color:#526075}.empty{padding:44px;min-height:300px;border:1px solid #e4e9ef;border-radius:25px;background:#fff;display:flex;flex-direction:column;align-items:flex-start;justify-content:center}.empty-icon{display:grid;place-items:center;background:#e8f1ff;border-radius:100%;font-size:26px;width:58px;height:58px;margin-bottom:22px}.empty h2{font-size:clamp(29px,3vw,43px);letter-spacing:-.05em;margin:0 0 8px}.empty p{color:#526075;line-height:1.5;max-width:55ch;margin:0 0 22px}.catalog{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}.catalog-card{overflow:hidden;border:1px solid #e3e8ef;border-radius:23px;background:#fff}.catalog-card img{width:100%;aspect-ratio:1.15;object-fit:cover;background:#e7ebf0}.catalog-card>div{padding:20px}.catalog-card h2{font-size:24px;letter-spacing:-.04em;margin:0 0 5px}.catalog-card p{color:#526075;margin:0 0 12px;line-height:1.45}.detail{display:grid;grid-template-columns:1fr 1fr;gap:44px;align-items:start;padding-top:70px}.detail img{width:100%;border-radius:25px;aspect-ratio:1;object-fit:cover;background:#e5e9ee}.detail h1{font-size:clamp(48px,5vw,76px);line-height:1;letter-spacing:-.065em;margin:12px 0}.detail p{color:#526075;line-height:1.58}.detail .button{margin-top:15px}
.form-wrap{display:grid;grid-template-columns:1fr 1fr;gap:60px;align-items:start;padding:68px 0 0}.form-wrap h1{font-size:clamp(50px,6vw,82px);letter-spacing:-.07em;line-height:.98;margin:14px 0 20px}.form-card{background:#fff;border:1px solid #e3e8ef;border-radius:24px;padding:clamp(22px,3vw,42px);box-shadow:0 14px 30px #17203308}.field{display:block;margin-bottom:17px}.field span{display:block;font-weight:690;font-size:13px;margin-bottom:8px}.field input,.field textarea,.field select{width:100%;background:#f8fafd;border:1px solid #dce3ec;border-radius:12px;padding:13px 14px;min-height:48px;color:#172033}.field textarea{min-height:120px;resize:vertical}.field input:focus,.field textarea:focus,.field select:focus{border-color:#0862e7;outline:2px solid #b9d5ff}.form-error{color:#ae2230;font-size:13px;min-height:18px}.form-card .button{width:100%}.honeypot{position:absolute;left:-10000px}
.footer{margin-top:110px;background:#eef2f6;border-top:1px solid #e1e7ef;padding:46px 0 35px}.footer-in{display:flex;justify-content:space-between;gap:36px}.footer .brand{margin-bottom:12px}.footer p{color:#657187;line-height:1.5;max-width:40ch}.footer-links{display:flex;flex-wrap:wrap;gap:16px 25px;align-content:start}.footer-links a{font-size:14px;min-height:38px;display:inline-flex;align-items:center}.footer-links a:hover{text-decoration:underline}.footnote{border-top:1px solid #dce2ea;margin-top:36px;padding-top:20px;color:#758195;font-size:12px}
@media(max-width:1100px){.top-in{flex-wrap:wrap;padding-top:13px;padding-bottom:13px;min-height:0}.nav{order:3;overflow-x:auto;width:100%;justify-content:flex-start}.hero{grid-template-columns:1fr}.hero-art{margin-top:8px}.hero h1{max-width:750px}.four-grid,.film-grid{grid-template-columns:repeat(2,1fr)}}
@media(max-width:680px){.shell{padding:0 18px}.top-in{gap:10px}.brand{font-size:21px}.join-link{min-width:0;padding:11px 16px}.nav{gap:0;padding:3px}.nav a{font-size:12px;padding:9px 12px}.hero{padding-top:48px;gap:34px}.hero h1{font-size:clamp(52px,14vw,74px)}.hero-art{gap:9px}.clip-window{border-radius:15px}.clip-card h3{font-size:13px}.clip-card p{font-size:11px}.clip-card:nth-child(2){transform:translateY(15px)}.section{padding-top:80px}.section-head{align-items:start}.section h2{font-size:36px}.four-grid,.film-grid,.catalog{grid-template-columns:1fr 1fr;gap:10px}.way-card{min-height:214px;padding:18px;border-radius:18px}.way-card h3{font-size:25px}.way-card p{font-size:13px}.film .clip-window{aspect-ratio:.9}.film-body{padding:12px}.film h3{font-size:14px}.feature{grid-template-columns:1fr}.feature-media{height:280px;min-height:0}.feature-copy{padding:27px}.page-head{padding-top:52px}.empty{padding:28px;min-height:300px}.detail,.form-wrap{grid-template-columns:1fr;gap:24px}.detail{padding-top:46px}.form-wrap{padding-top:47px}.footer-in{display:block}.footer-links{margin-top:24px}}
@media(max-width:390px){.hero-art{grid-template-columns:repeat(2,1fr)}.clip-card:nth-child(3){display:none}.four-grid{grid-template-columns:1fr 1fr}.nav a{padding:8px 10px}}
@media(prefers-reduced-motion:reduce){html{scroll-behavior:auto}*,*::before,*::after{transition-duration:.01ms!important;animation-duration:.01ms!important}}
.clip-window img,.clip-window video{position:absolute;inset:0;width:100%;height:100%;object-fit:cover}.clip-window video{opacity:0;transition:opacity .3s ease}.clip-window video.playing,.clip-window video[controls]{opacity:1}.film video{background:transparent}
`;

const client = `
document.querySelectorAll('video[data-autoplay]').forEach(video=>{video.addEventListener('playing',()=>video.classList.add('playing'));const observer=new IntersectionObserver(entries=>{for(const entry of entries){if(entry.isIntersecting&&window.matchMedia('(prefers-reduced-motion: no-preference)').matches){video.play().catch(()=>{});}else video.pause();}},{threshold:.35});observer.observe(video)});
const form=document.querySelector('#join-form');if(form){form.addEventListener('submit',async event=>{event.preventDefault();const status=form.querySelector('[role="status"]');const submit=form.querySelector('[type="submit"]');status.textContent='';if(!form.reportValidity())return;submit.disabled=true;submit.textContent='Sending…';const fd=new FormData(form);const subject=String(fd.get('subject')||'Join Communiverse');const body={name:String(fd.get('name')||''),email:String(fd.get('email')||''),subject,message:String(fd.get('message')||''),website:String(fd.get('website')||''),requestId:crypto.randomUUID()};try{const response=await fetch('/communiverse/api/waitlist',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await response.json();if(!response.ok)throw Error(result.error||'Please try again.');form.innerHTML='<div class="empty-icon" aria-hidden="true">✓</div><h2>Thanks for reaching out.</h2><p>Your request was saved. We’ll be in touch.</p><p class="note">Reference: '+result.reference+'</p>';}catch(error){status.textContent=error.message||'Could not send your request. Please try again.';submit.disabled=false;submit.textContent='Send request ↗';}})};
`;

function layout(title, active, body, description = '', canonical = '') {
  const nav = [ ['Discover', path()], ['Artists', path('artists/')], ['Objects', path('works/')], ['Workshops', path('workshops/')], ['Plug', path('plug/')] ];
  const canonicalTag = canonical ? `<link rel="canonical" href="https://espacios.me${e(canonical)}">` : '';
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#f5f5f7"><meta name="description" content="${e(description || 'Communiverse connects craft, culture, and people through the work of making.')}"><title>${e(title)} — Communiverse</title>${canonicalTag}<style>${css}</style></head><body><a class="skip" href="#main">Skip to content</a><header class="top"><div class="shell top-in"><a class="brand" href="${path()}">Communiverse</a><nav class="nav" aria-label="Main navigation">${nav.map(([label,href]) => `<a href="${href}"${active===label?' aria-current="page"':''}>${label}</a>`).join('')}</nav>${button('Join',path('join/'),false)}</div></header><main id="main" class="shell">${body}</main><footer class="footer"><div class="shell"><div class="footer-in"><div><a class="brand" href="${path()}">Communiverse</a><p>Made by people. Found by people. A home for craft, culture, and the people behind it.</p></div><nav class="footer-links" aria-label="Footer navigation"><a href="${path('artists/')}">Artists</a><a href="${path('works/')}">Objects</a><a href="${path('workshops/')}">Workshops</a><a href="${path('plug/')}">Plug</a><a href="${path('ambassadors/')}">Ambassadors</a><a href="${path('join/')}">Join</a><a href="mailto:${email}">Email</a></nav></div><div class="footnote">© ${new Date().getUTCFullYear()} Communiverse · Craft has a human story.</div></div></footer><script defer src="${SCRIPT_PATH}"></script></body></html>`;
}

function clip(item, mode = 'hero') {
  const poster = `https://espacios.me${item.src.replace(/\.mp4$/, '-poster.jpg')}`;
  const interactive = mode === 'story';
  const videoAttrs = interactive ? `controls playsinline preload="none" aria-label="Play ${e(item.title)}"` : 'data-autoplay muted loop playsinline preload="none" aria-hidden="true"';
  return `<article class="${mode === 'hero' ? 'clip-card' : 'film'}"><div class="clip-window"><img src="${e(poster)}" alt="" loading="lazy"><video ${videoAttrs} poster="${e(poster)}"><source src="${e(item.src)}" type="video/mp4"></video><span class="clip-label">${e(item.kind)}</span></div><div class="${mode === 'hero' ? '' : 'film-body'}"><h3>${e(item.title)}</h3><p>${e(item.craft)}</p></div></article>`;
}
function filmSection(items = videoArt.slice(0, 4)) { return `<section class="section" aria-labelledby="films-title"><div class="section-head"><div><span class="eyebrow">See the making</span><h2 id="films-title">A world made by hand.</h2><p class="section-intro">A small window into craft and culture, drawn from the Communiverse film collection.</p></div><a class="text-link" href="${path('stories/')}">View all films <span aria-hidden="true">↗</span></a></div><div class="film-grid">${items.map(item => clip(item, 'film')).join('')}</div><p class="note">Film subjects are shown without attributing a maker. Artist profiles will be added when their details are confirmed.</p></section>`; }
function home() {
  const heroClips = [videoArt[4],videoArt[0],videoArt[10]];
  return layout('Discover','Discover',`<section class="hero"><div class="hero-copy"><span class="eyebrow">Made by people, found by people</span><h1>The world<br>of <span>making.</span></h1><p class="lead">Discover the hands, ideas, and stories behind craft. Meet the Communiverse now, and be first to know when its artist marketplace opens.</p>${button('Explore the making',path('stories/'))}</div><div class="hero-art" aria-label="Craft films from Communiverse">${heroClips.map(item=>clip(item)).join('')}</div></section><section class="section" aria-labelledby="paths-title"><div class="section-head"><div><span class="eyebrow">Your way in</span><h2 id="paths-title">Come for the craft.<br>Stay for the people.</h2></div></div><div class="four-grid"><a class="way-card" href="${path('stories/')}"><strong>01 / WATCH</strong><div><h3>Discover</h3><p>Follow the details, gestures and ideas behind things made with care.</p></div></a><a class="way-card" href="${path('artists/')}"><strong>02 / MEET</strong><div><h3>Artists</h3><p>Artist stories and their work will appear here as the community grows.</p></div></a><a class="way-card" href="${path('workshops/')}"><strong>03 / LEARN</strong><div><h3>Workshops</h3><p>Make something with the people who know the craft.</p></div></a><a class="way-card" href="${path('works/')}"><strong>04 / COLLECT</strong><div><h3>Objects</h3><p>Explore pieces and their stories when the first collection is ready.</p></div></a></div></section>${filmSection()}<section class="section"><div class="feature"><div class="feature-media"><video data-autoplay muted loop playsinline preload="none" poster="${videoArt[0].src.replace(/\.mp4$/, '-poster.jpg')}" aria-label="Weaving on a wooden loom"><source src="${videoArt[0].src}" type="video/mp4"></video></div><div class="feature-copy"><span class="eyebrow">The people behind it</span><h2>Good craft begins with a connection.</h2><p>Communiverse is building a place for independent makers, curious people, and shared experiences. Our first artist listings are being prepared.</p>${button('Meet the community',path('plug/'))}</div></div></section><section class="section"><div class="section-head"><div><span class="eyebrow">Be part of it</span><h2>Have a story to share?</h2><p class="section-intro">Whether you make, teach, collect, or simply love craft, we’d like to hear from you.</p></div>${button('Join the circle',path('join/'))}</div></section>`, 'Discover craft films and the people behind Communiverse. Artist and workshop listings are coming soon.', path());
}
const empty = (icon, title, message, label='Join the circle') => `<div class="empty"><div class="empty-icon" aria-hidden="true">${icon}</div><h2>${e(title)}</h2><p>${e(message)}</p>${button(label,path('join/'))}</div>`;
function catalogCard(item, type) {
  const dest = path(`${type}/${encodeURIComponent(item.slug)}/`);
  const image = type === 'artists' ? item.portrait_url : item.cover_url;
  const sub = type === 'artists' ? [item.discipline,item.location].filter(Boolean).join(' · ') : type === 'works' ? [item.material,item.kind].filter(Boolean).join(' · ') : item.discipline || '';
  return `<a class="catalog-card" href="${dest}">${image ? `<img src="${safeUrl(image)}" alt="" loading="lazy">` : ''}<div><h2>${e(item.name || item.title)}</h2><p>${e(sub)}</p><span class="text-link">Explore <span aria-hidden="true">↗</span></span></div></a>`;
}
function listing(kind, records, error=false) {
  const artists = kind === 'artists', works = kind === 'works';
  const intro = artists ? 'The marketplace is being shaped around real people and their work. We’ll introduce artists here as they join.' : works ? 'Objects made with intention belong here. The first collection will appear after the makers and their work are confirmed.' : 'Small sessions and hands-on experiences are taking shape. Join the circle to hear when the first workshops are ready.';
  const heading = artists ? 'Meet the <span>artists.</span>' : works ? 'Objects with <span>stories.</span>' : 'Make it <span>together.</span>';
  const emptyTitle = artists ? 'The artist space is opening soon.' : works ? 'The first collection is taking shape.' : 'Workshops are on their way.';
  const emptyText = artists ? 'We haven’t published artist profiles yet. We’ll only feature makers once their names, work and permission are confirmed.' : works ? 'There are no objects for sale yet. We’ll share the first pieces after their makers, details, and availability are verified.' : 'There are no confirmed workshop dates yet. Get in touch if you’re an artist who wants to teach, or if you’d like to hear when sessions open.';
  const body = `<header class="page-head"><span class="eyebrow">${artists?'The people behind the work':works?'Craft, to live with':'Learn by doing'}</span><h1>${heading}</h1><p class="lead">${intro}</p></header>${error ? `<p class="note" role="status">The catalogue is temporarily unavailable. Please try again soon.</p>` : ''}${records.length ? `<div class="catalog">${records.map(row => catalogCard(row,kind)).join('')}</div>` : empty(artists?'✺':works?'◇':'✳',emptyTitle,emptyText)}${filmSection(artists ? [videoArt[10],videoArt[5],videoArt[0],videoArt[6]] : [videoArt[4],videoArt[0],videoArt[11],videoArt[1]])}`;
  return layout(artists?'Artists':works?'Objects':'Workshops',artists?'Artists':works?'Objects':'Workshops',body,intro,path(kind+'/'));
}
function stories() { return layout('See the making','Discover',`<header class="page-head"><span class="eyebrow">Communiverse film collection</span><h1>See the <span>making.</span></h1><p class="lead">Thirteen glimpses of art, craft, and culture. These films show processes and objects; they do not identify or endorse a particular maker.</p></header><div class="film-grid">${videoArt.map(item=>clip(item,'story')).join('')}</div>`, '', path('stories/')); }
function join(url) {
  const kind = url.searchParams.get('kind');
  const ref = url.searchParams.get('ref');
  const context = ['artists','works','workshops'].includes(kind) && /^[a-z0-9-]{1,80}$/.test(ref || '')
    ? `${kind === 'artists' ? 'Artist' : kind === 'works' ? 'Object' : 'Workshop'} enquiry: ${ref}` : '';
  const contextOption = context ? `<option value="${e(context)}" selected>About ${e(ref)}</option>` : '';
  return layout('Join','Join',`<div class="form-wrap"><div><span class="eyebrow">Join Communiverse</span><h1>Come on <span>in.</span></h1><p class="lead">Tell us what you make, what you love, or how you’d like to be part of the circle. Your request is saved in the existing Communiverse request system.</p><div class="pill-row"><span class="pill">Artists and makers</span><span class="pill">Craft lovers</span><span class="pill">Workshop hosts</span><span class="pill">Partners</span></div></div><form class="form-card" id="join-form"><label class="field"><span>Your name</span><input name="name" autocomplete="name" required minlength="1" maxlength="120"></label><label class="field"><span>Email address</span><input name="email" type="email" autocomplete="email" required maxlength="254"></label><label class="field"><span>What brings you here?</span><select name="subject" required>${contextOption}<option value="Join Communiverse">I’d like to join</option><option value="Artist enquiry">I’m an artist or maker</option><option value="Workshop enquiry">I’d like to host a workshop</option><option value="Partnership enquiry">I’d like to collaborate</option></select></label><label class="field"><span>Tell us a little more</span><textarea name="message" required minlength="8" maxlength="4000" placeholder="What do you make, love, or want to discover?"></textarea></label><label class="honeypot" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><p class="form-error" role="status" aria-live="polite"></p><button class="button" type="submit">Send request ↗</button><p class="note">We’ll use your details only to respond to this request. You can also email <a href="mailto:${email}">${email}</a>.</p></form></div>`, '', path('join/'));
}
function detail(type, item) {
  if (!item) return null;
  const artist = type === 'artists', work = type === 'works'; const title = artist ? item.name : item.title;
  const image = artist ? item.portrait_url : item.cover_url;
  const meta = artist ? [item.discipline,item.location].filter(Boolean).join(' · ') : work ? [item.material,item.kind].filter(Boolean).join(' · ') : [item.discipline,item.duration_minutes ? `${item.duration_minutes} minutes` : ''].filter(Boolean).join(' · ');
  const link = artist && item.instagram_url ? `<a class="text-link" href="${safeUrl(item.instagram_url)}" target="_blank" rel="noopener noreferrer">Instagram ↗</a>` : '';
  const inquiry = path(`join/?${new URLSearchParams({kind:type,ref:item.slug})}`);
  return layout(title,artist?'Artists':work?'Objects':'Workshops',`<div class="detail"><div>${image?`<img src="${safeUrl(image)}" alt="${e(title)}">`:''}</div><div><a class="text-link" href="${path(type+'/')}">← Back to ${type}</a><p class="eyebrow">${e(meta)}</p><h1>${e(title)}</h1><p>${e(artist?item.bio:item.description)}</p>${link}<div>${button(artist?'Get in touch':work?'Enquire about this piece':'Ask about this workshop',inquiry)}</div></div></div>`, '', path(`${type}/${encodeURIComponent(item.slug)}/`));
}
async function loadCatalog(env, table, slug) {
  if (!env.SUPABASE_URL || !env.SUPABASE_PUBLISHABLE_KEY) return {rows:[],error:false};
  const cols = table === 'artists' ? 'slug,name,discipline,location,bio,portrait_url,instagram_url' : table === 'works' ? 'slug,title,description,material,kind,cover_url' : 'slug,title,description,discipline,duration_minutes,cover_url';
  const query = new URL(`${env.SUPABASE_URL}/rest/v1/${table}`);
  query.searchParams.set('select',cols); query.searchParams.set('status','eq.published');
  if (slug) query.searchParams.set('slug',`eq.${slug}`);
  else { query.searchParams.set('order','published_at.desc'); query.searchParams.set('limit','36'); }
  try {
    const response = await fetch(query,{headers:{apikey:env.SUPABASE_PUBLISHABLE_KEY},signal:AbortSignal.timeout(3500)});
    if (!response.ok) throw Error('Catalog unavailable');
    const rows = await response.json(); return {rows:Array.isArray(rows)?rows:[],error:false};
  } catch { return {rows:[],error:true}; }
}
function html(body,status=200,method='GET') {return new Response(method==='HEAD'?null:body,{status,headers:{'Content-Type':'text/html; charset=utf-8','Cache-Control':'public, max-age=60','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'SAMEORIGIN','Content-Security-Policy':"default-src 'self'; style-src 'unsafe-inline'; script-src 'self'; img-src 'self' https: data:; media-src 'self'; connect-src 'self'; base-uri 'self'; object-src 'none'; frame-ancestors 'self'; form-action 'self'",'X-Communiverse-Marketplace':RELEASE}});}
function legacy(request, env) {
  if (!env.LEGACY) return new Response('Not found', {status:404});
  const url = new URL(request.url);
  if (!['espacios.me','www.espacios.me'].includes(url.hostname)) url.hostname = 'espacios.me';
  return env.LEGACY.fetch(new Request(url, request));
}
const marketplace = { async fetch(request,env={}) {
  const url=new URL(request.url), method=request.method;
  const p=url.pathname.replace(/\/+$/,'/') || '/';
  const owned = p===ROOT || p===path() || p===path('stories/') || p===path('join/') || p===path('artists/') || p===path('works/') || p===path('workshops/') || p===SCRIPT_PATH || /^\/communiverse\/(artists|works|workshops)\/[a-z0-9-]{1,80}\/$/.test(p);
  if (!owned) return legacy(request,env);
  if (!['GET','HEAD'].includes(method)) return new Response('Method not allowed',{status:405,headers:{Allow:'GET, HEAD'}});
  if (p===SCRIPT_PATH) return new Response(method==='HEAD'?null:client,{headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'public, max-age=31536000, immutable','X-Content-Type-Options':'nosniff'}});
  if (p===ROOT || p===path()) return html(home(),200,method);
  if (p===path('stories/')) return html(stories(),200,method);
  if (p===path('join/')) return html(join(url),200,method);
  if (p===path('artists/') || p===path('works/') || p===path('workshops/')) { const type=p.slice(ROOT.length+1,-1); const {rows,error}=await loadCatalog(env,type); return html(listing(type,rows,error),200,method); }
  const match=p.match(/^\/communiverse\/(artists|works|workshops)\/([a-z0-9-]{1,80})\/$/);
  if (match) {const {rows,error}=await loadCatalog(env,match[1],match[2]);if (error) return html(layout('Unavailable',match[1]==='artists'?'Artists':match[1]==='works'?'Objects':'Workshops',empty('⌁','Please try again later.','The catalogue is temporarily unavailable.')),503,method);const page=detail(match[1],rows[0]);return page?html(page,200,method):html(layout('Not found','Discover',empty('⌁','This story is not here yet.','Browse the community while we prepare more stories.')),404,method);}
  return new Response('Not found',{status:404});
}};
export default marketplace;
