export const RELEASE='20261008-plug-artists-1';
export const PREFIX='/communiverse/_public/'+RELEASE;
const old='/communiverse/_public/media/',gallery='/communiverse/media/gallery-20261007/';
const film=(title,src,note='Craft reference film')=>({title,src,note});
const artist=(id,name,role,location,image,summary,more,focus,films)=>({slug:'artist-'+id,id,name,role,location,image:'/communiverse/_public/sample-artists/'+image+'.jpg',category:'artists',group:'Artists',eyebrow:'Artists',sample:true,summary,more,focus,films,socials:[],sources:[],profileUrl:'/communiverse/artists/'+id+'/'});
export const ARTISTS=[
 artist('amina-rahmani','Amina Rahmani','Ceramic restoration','Marrakech, Morocco','amina-rahmani','A second life for the objects we keep. Amina’s atelier explores ceramic repair, quiet colour and the beauty of a visible seam.','Her practice begins with an everyday vessel: study the fracture, preserve its character, and let the repair become part of its next chapter.',['Ceramic repair','Glazes','Material memory'],[film('Another life for a cup',old+'ceramic-repair.mp4')]),
 artist('lucia-quintero','Lucía Quintero','Hand weaving','Bogotá, Colombia','lucia-quintero','Colour measured in threads. Lucía’s studio pairs deep indigo with loose textures and the small variations of a handloom.','A collection around slow repetition: winding, threading and passing the shuttle until a plain surface becomes a rhythm.',['Handloom','Indigo','Textile rhythm'],[film('Threads under tension',old+'loom-weaving.mp4')]),
 artist('matteo-bellini','Matteo Bellini','Wood sculpture','Florence, Italy','matteo-bellini','Wood that seems to move. Matteo’s practice follows the grain into folds, expressive faces and sculptural gestures.','This studio story treats carving as a conversation with the material: reveal the form slowly, keeping the warmth of the original timber.',['Wood carving','Drapery','Figurative forms'],[film('Drapery carved in wood',gallery+'draped-wood-sculpture.mp4'),film('A face shaped in wood',gallery+'carved-dog.mp4')]),
 artist('nia-okafor','Nia Okafor','Wire sculpture','Lagos, Nigeria','nia-okafor','Drawing in three dimensions. Nia’s practice imagines wire as a line that can hold a face, a shadow or a moment of movement.','Open structures, small welds and carefully placed gaps make an collection that changes as you walk around it.',['Wire drawing','Welded forms','Light & shadow'],[film('Lines becoming a figure',gallery+'wire-sculpture.mp4')]),
 artist('sora-nakamura','Sora Nakamura','Lettering and paper','Kyoto, Japan','sora-nakamura','Small marks, expansive worlds. Sora’s paper studio studies patient lettering, handmade surfaces and the edges left by ink.','A practice built on attention: a single stroke, a measured space, then another. The smallest details carry the atmosphere of the whole page.',['Lettering','Paper','Tiny details'],[film('Letters at a tiny scale',gallery+'fine-lettering.mp4')]),
 artist('leila-al-mansouri','Leila Al Mansouri','Metalwork','Dubai, UAE','leila-al-mansouri','Reflection becomes a material. Leila’s atelier explores polished metal, balanced circles and surfaces that borrow their colour from a room.','An collection of forms that reward movement: step closer, circle around, and watch the work change with the light.',['Polished metal','Reflection','Kinetic forms'],[film('A circle in polished metal',gallery+'mirror-metal-sculpture.mp4')]),
 artist('priya-mehta','Priya Mehta','Block printing','Jaipur, India','portrait-priya','Pattern with a human rhythm. Priya’s textile studio combines hand-carved blocks, colour studies and the character of repeated marks.','This practice moves between a single motif and a whole cloth. Related textile films explore pattern and colour rather than documenting block printing.',['Block printing','Pattern','Colour studies'],[film('A floor of colour',old+'patterned-rugs.mp4','Related textile film · decorative rugs')]),
 artist('diego-salazar','Diego Salazar','Silversmithing','Lima, Peru','portrait-diego','Useful objects with a sculptor’s eye. Diego’s metal studio imagines tactile surfaces, warm reflections and hammer marks left visible.','A collection around objects you hold every day. The accompanying sculpture film explores metal and reflection; it does not document silversmithing.',['Metal shaping','Tactile surfaces','Everyday objects'],[film('Metal, light and movement',gallery+'mirror-metal-sculpture.mp4','Related metal film · polished sculpture')]),
 artist('awa-diop','Awa Diop','Basket weaving','Dakar, Senegal','portrait-awa','A vessel made one line at a time. Awa’s practice explores plant fibres, gentle asymmetry and objects that earn their place in daily life.','This studio story is about structure built through repetition. The related handloom film explores weaving principles rather than basket making.',['Plant fibres','Coiling','Everyday vessels'],[film('The rhythm of weaving',old+'loom-weaving.mp4','Related weaving film · handloom textiles')]),
 artist('elias-korhonen','Elias Korhonen','Glassblowing','Helsinki, Finland','portrait-elias','Light held in a form. Elias’s glass studio explores translucent vessels, slender silhouettes and the brief moment when heat makes glass fluid.','An practice shaped by breath, temperature and timing. The new glass film shows a glowing gather taking shape before a finished vessel catches the light.',['Hot glass','Vessels','Light & transparency'],[film('Glass, shaped by heat',PREFIX+'/glass-shaping.mp4')]),
];
export const escapeHTML=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const serialize=people=>JSON.stringify(people).replace(/</g,'\\u003c').replace(/>/g,'\\u003e').replace(/&/g,'\\u0026');
export function portrait(p){const h=escapeHTML;return `<a class="node is-curated" data-slug="${h(p.slug)}" data-name="${h(p.name)}" href="${h(p.profileUrl)}"><img src="${h(p.image)}" alt="" width="240" height="240" decoding="async"><span class="cap"><b>${h(p.name)}</b><small>${h(p.role)}</small></span></a>`;}
export function profileContent(p){const h=escapeHTML;return `<section class="cv-artist-profile"><a class="cv-artist-back" href="/communiverse/plug/?person=${h(p.slug)}">← Back to Plug</a><div class="cv-artist-grid"><div class="cv-artist-about"><img class="cv-artist-portrait" src="${h(p.image)}" alt="${h(p.name)}" width="180" height="180"><p class="cv-artist-kicker">${h(p.role)} · ${h(p.location)}</p><h1>${h(p.name)}</h1><span class="cv-sample">Sample profile</span><article class="cv-artist-card"><h2>In the studio</h2><p>${h(p.summary)}</p><p>${h(p.more)}</p><div class="cv-artist-tags">${p.focus.map(x=>`<span>${h(x)}</span>`).join('')}</div></article><p class="cv-artist-note">An imagined artist story. The films explore related crafts and are not attributed to this profile.</p></div><div class="cv-artist-films">${p.films.map(f=>`<article class="cv-artist-card cv-film-card"><video class="cv-craft-video" src="${h(f.src)}" controls muted loop playsinline preload="metadata" aria-label="${h(f.title)}"></video><h2>${h(f.title)}</h2><p>${h(f.note)}</p></article>`).join('')}</div></div></section>`;}
