/* Browser-rendering assertions, fixture only. No external writes. */
(()=>{'use strict';const tests=[];
const add=(name,ok,detail='')=>tests.push({name,pass:!!ok,details:String(detail||'').slice(0,200)});
const wait=async(fn,ms=8000)=>{const start=Date.now();while(Date.now()-start<ms){const v=fn();if(v)return v;await new Promise(r=>setTimeout(r,80))}return null};
async function run(){try{
 await wait(()=>window.__cvExperienceV3?.ready,3000);
 add('V3 enhancer initialized',window.__cvExperienceV3?.ready===true);
 const block=await wait(()=>document.querySelector('#cv-work-detail .cv3-work-extra'),5000);
 add('Artwork metadata moved outside two-column hero',!!block&&block.previousElementSibling?.classList.contains('cv-work-layout'));
 add('Original media remains inside layout',!!document.querySelector('#cv-work-detail .cv-work-layout img'));
 add('Source link preserved in full-width area',!!block?.querySelector('a.cv-text-link[href="https://example.org"]'));
 add('Source disclaimer preserved',!!block?.textContent.includes('guide prices'));
 add('Tags preserved',block?.querySelectorAll('.cv3-work-tags>*').length===8);
 const more=block?.querySelector('.cv3-tags-more');add('Long tag list collapsible',!!more);more?.click();add('Tag expansion working',more?.getAttribute('aria-expanded')==='true'&&!!block?.querySelector('.cv3-tags-expanded'));
 const count=await wait(()=>document.querySelectorAll('.cv3-focus-item').length>=3,7000);
 add('Live-source focus board renders authorized tasks and requests',!!count);
 add('Focus cards retain native task ids',!!document.querySelector('.cv3-focus-item [data-ws-task="task-1"]'));
 add('Focus cards retain native request ids',!!document.querySelector('.cv3-focus-item [data-ws-request="request-1"]'));
 add('Workspace Overview relabeled Focus',document.querySelector('[data-ws-tab=overview]')?.textContent==='Focus');
 const owner=await wait(()=>document.querySelector('.cv3-person-picker'),7000);
 add('Owner dropdown replaced by avatar radio choices',!!owner&&!!owner.querySelectorAll('button[role=radio]').length);
 const chosen=owner?.querySelector('[data-cv3-person-id=luna]');chosen?.click();add('Avatar selection updates existing form control',document.querySelector('#cv-ws-task-form select[name=owner_id]')?.value==='luna');
 const mentions=await wait(()=>document.querySelector('#cv-ws-comment-form .cv3-mention-picker, #cv-ws-dialog .cv3-mention-picker'),7000);
 add('Notify people renders as circles',!!mentions&&mentions.querySelectorAll('.cv3-mention-choice .cv3-person-circle').length===5);
 const lunaTip=mentions?.querySelector('[data-cv3-person-id=luna] .cv3-person-circle')?.dataset.cv3Tooltip;
 add('Notify circle tooltip is the person name',lunaTip==='Luna',lunaTip||'');
 const notifyHaseeb=mentions?.querySelector('[data-cv3-person-id=haseeb]');const notifyLuna=mentions?.querySelector('[data-cv3-person-id=luna]');
 notifyHaseeb?.click();notifyLuna?.click();
 const picked=[...document.querySelectorAll('#cv-ws-comment-form select[name=mentions] option:checked')].map(o=>o.value);
 add('Several people can stay selected together',picked.includes('haseeb')&&picked.includes('luna')&&picked.length===2,picked.join(','));
 add('Selected circles stay pressed',notifyHaseeb?.getAttribute('aria-pressed')==='true'&&notifyLuna?.getAttribute('aria-pressed')==='true');
 notifyHaseeb?.click();
 const cleared=[...document.querySelectorAll('#cv-ws-comment-form select[name=mentions] option:checked')].map(o=>o.value);
 add('Clearing one person leaves the others selected',!cleared.includes('haseeb')&&cleared.includes('luna')&&cleared.length===1,cleared.join(','));
 add('Mention values stay on the original select',new FormData(document.querySelector('#cv-ws-comment-form')).getAll('mentions').join(',')==='luna');
 add('Native owner selector remains serialized',!!document.querySelector('#cv-ws-task-form select[name=owner_id]')?.getAttribute('name'));
 const fields=await wait(()=>document.querySelector('#cv-ws-task-form .cv3-task-fields'),4000);
 const controls=fields?[...fields.querySelectorAll('select,input')]:[];
 const heights=controls.map(el=>Math.round(el.getBoundingClientRect().height));
 add('State, priority and due date share one row',controls.length===3&&!!fields.querySelector('select[name=status]')&&!!fields.querySelector('select[name=priority]')&&!!fields.querySelector('input[name=due_date]'));
 add('Task fields stay one control tall',heights.length===3&&heights.every(h=>h>=44&&h<=56),heights.join(','));
 add('Sign-off stays a checkbox on the task form',document.querySelector('#cv-ws-task-form .cv-ws-check input[name=approval_required]')?.type==='checkbox');
 const kind=await wait(()=>document.querySelector('.cv3-kind-grid'),7000);add('Request kind visual tiles',!!kind&&kind.querySelectorAll('[role=radio]').length===11);
 kind?.querySelector('[data-cv3-kind=subscription]')?.click();add('Request tile updates original select',document.querySelector('#cv-ws-request-form select[name=kind]')?.value==='subscription');
 const route=await wait(()=>document.querySelector('.cv3-timeline-person'),7000);add('Server-policy preview shows real reviewer identities',!!route&&document.querySelectorAll('.cv3-timeline-person').length===2);
 add('Original request submit button preserved',!!document.querySelector('#cv-ws-request-form button[type=submit]'));
 add('Task actions are review before save',document.querySelector('.cv3-task-actions')?.textContent.includes('Ready to save')===false);
 const member=document.querySelector('.cv3-avatar-group');add('Multi-person selector preserves checkbox controls',!!member&&member.querySelectorAll('input[name=members]').length===4);
 const ask=document.querySelector('#cv-ws-search'),results=document.querySelector('#cv-ws-search-results');
 if(ask&&results){ask.value='Plan an ambassador trip for Luna for 4 days with a $2000 budget';results.hidden=false;results.innerHTML='<section class="cv-ws-assistant"><h2>Your next move</h2><p class="cv-assistant-answer">Luna can travel once the request is reviewed.</p><p class="cv-ws-meta">Next: confirm dates.</p><form data-assistant-submit="draft-1"><label>Title<input name="title" value="Ambassador trip for Luna"></label><label>Estimated amount<input name="amount" type="number"></label><div class="cv-assistant-route" aria-label="Approval path"><span>1. Haseeb</span><span>2. Elferah</span></div><button class="cv-button" type="submit">Create request</button></form></section>';}
 const plan=await wait(()=>document.querySelector('.cv3-plan-travelers'),5000);
 add('A trip question becomes a working plan',!!plan&&plan.textContent.includes('Luna'));
 add('Approval path stays a circle chain',!!document.querySelector('.cv3-plan-reviewers')?.textContent.includes('Haseeb')&&document.querySelector('.cv3-plan-reviewers')?.textContent.includes('Elferah'));
 add('Days and budget are filled from the question',document.querySelector('.cv3-plan-days')?.value==='4'&&document.querySelector('.cv3-plan-budget')?.value==='2000');
 add('The estimate is calculated',document.querySelector('.cv3-plan-total')?.dataset.cv3Estimate==='2000');
 const daily=document.querySelector('.cv3-plan-daily');if(daily){daily.value='100';daily.dispatchEvent(new Event('input',{bubbles:true}));}
 add('Changing the allowance updates the estimate',document.querySelector('.cv3-plan-total')?.dataset.cv3Estimate==='400');
 const stepCount=document.querySelectorAll('.cv3-plan-step').length;document.querySelector('.cv3-plan-add-step')?.click();
 add('A step can be added',document.querySelectorAll('.cv3-plan-step').length===stepCount+1);
 document.querySelector('.cv3-plan-add-person')?.click();document.querySelector('.cv3-plan-picker [data-cv3-person-id="keiffer"]')?.click();
 add('Another person can be added as a circle',!!document.querySelector('.cv3-plan-travelers [data-cv3-person-id="keiffer"]'));
 add('The assistant answer stays on the page',document.querySelector('.cv-assistant-answer')?.textContent.includes('Luna can travel'));
 add('The draft form is still there to review',!!document.querySelector('[data-assistant-submit] button[type=submit]'));
 const lunaCircle=document.querySelector('.cv3-plan-travelers [data-cv3-person-id="luna"]');
 add('People start included',lunaCircle?.getAttribute('aria-pressed')==='true');
 lunaCircle?.click();
 add('Tapping a person leaves them out',lunaCircle?.getAttribute('aria-pressed')==='false');
 lunaCircle?.click();
 const stepTitle=document.querySelector('.cv3-plan-step-title');
 if(stepTitle){stepTitle.value='Pack for the visit';stepTitle.dispatchEvent(new Event('input',{bubbles:true}))}
 add('A step can be rewritten',document.querySelector('.cv3-plan-step-title')?.value==='Pack for the visit');
 document.querySelector('.cv3-plan-step-btn')?.click();
 add('The step circle marks it ready',document.querySelector('.cv3-plan-step')?.classList.contains('is-done')&&document.querySelector('.cv3-plan-progress')?.textContent.startsWith('1 of'));
 const beforeSteps=document.querySelectorAll('.cv3-plan-step').length;
 [...document.querySelectorAll('.cv3-plan-rec .cv3-action')].find(b=>b.textContent==='Add as a step')?.click();
 add('A recommendation can become a step',document.querySelectorAll('.cv3-plan-step').length===beforeSteps+1);
 const sample=[{id:'luna',name:'Luna',role:'ambassador',region:'colombia'},{id:'ammar',name:'Ammar',role:'ambassador',region:'uae'},{id:'balo',name:'Balo',role:'ambassador',region:'uae'},{id:'keiffer',name:'Keiffer',role:'ambassador-lead',region:''}];
 const typed='i want to ordr 15 camras for the ambasadors';
 add('A camera order stays a kit plan',window.__cvExperienceV3.planKind(typed)==='kit');
 add('Fifteen cameras are read from the sentence',window.__cvExperienceV3.readQuantity(typed)===15);
 const matched=window.__cvExperienceV3.namedPeople(typed,{team:sample});
 add('Ambassadors are recognized, including typos',matched.map(p=>p.id).sort().join(',')==='ammar,balo,luna');
 add('The word the is not a person',!matched.some(p=>String(p.name).toLowerCase()==='the'));
 add('A mistyped name still finds Luna',window.__cvExperienceV3.namedPeople('trip for Lunna',{team:sample}).some(p=>p.id==='luna'));
 if(ask&&results){ask.value='I want to order 15 cameras for the ambassadors';results.innerHTML='<section class="cv-ws-assistant"><h2>Your next move</h2><p class="cv-assistant-answer">Route the camera request for approval.</p><form data-assistant-submit="draft-2"><label>Estimated amount<input name="amount" type="number"></label><button class="cv-button" type="submit">Create request</button></form></section>';}
 const camera=await wait(()=>document.querySelector('.cv3-plan-qty'),4000);
 add('Camera order uses a quantity',camera?.value==='15'&&camera.closest('.cv3-plan-field')?.hidden!==true);
 add('Daily allowance is not used for cameras',document.querySelector('.cv3-plan-daily')?.closest('.cv3-plan-field')?.hidden===true);
 add('The plan names ambassadors instead of the',!!document.querySelector('.cv3-plan-travelers')?.textContent.includes('Luna')&&!document.querySelector('.cv3-plan-travelers')?.textContent.includes('Named in your question'));
 add('Email status shows nothing has been sent',(document.querySelector('.cv3-plan-mail-summary')?.textContent||'').includes('0 sent'));
 add('The workspace assistant is Cosmos',document.querySelector('.cv3-plan .cv3-kicker')?.textContent==='COSMOS'&&document.querySelector('.cv3-plan')?.getAttribute('aria-label')==='Cosmos');
 add('Progress shows the current stage',!!document.querySelector('.cv3-plan-stage.is-now')&&!!document.querySelector('.cv3-plan-meter'));
 add('Open items stay visible until the price is set',(document.querySelector('.cv3-plan-ready')?.textContent||'').includes('Unit cost'));
 const width=document.documentElement.clientWidth,overflow=document.documentElement.scrollWidth-width;add('No horizontal overflow',overflow<=3,'overflow='+overflow+' width='+width);
}catch(e){add('Unhandled runtime exception',false,String(e?.message||e))}
 const pre=document.createElement('pre');pre.id='cv3-qa-result';pre.dataset.success=String(tests.every(t=>t.pass));pre.textContent=JSON.stringify({passed:tests.filter(x=>x.pass).length,total:tests.length,tests});document.body.append(pre);
}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',run,{once:true});else run();})();
