import{readFile,writeFile,mkdir}from'node:fs/promises';import{resolve}from'node:path';import{createHash}from'node:crypto';
const source=resolve('worker/releases/social-20261008'),capture=resolve(process.argv[2]||'../social5-current'),dest=resolve(process.argv[3]||'../social5-candidate');await mkdir(dest,{recursive:true});const m=JSON.parse(await readFile(resolve(capture,'manifest.json'),'utf8'));if(m.version!=='5690df4a-8028-45e6-82d9-82b4723c2aa2'||m.modules.length!==71)throw Error('Review new baseline first');const modules=[];
async function add(name,bytes,type){await writeFile(resolve(dest,name),bytes);modules.push({name,content_type:type,sha256:createHash('sha256').update(bytes).digest('hex'),bytes:bytes.length})}
for(const v of m.modules){const b=await readFile(resolve(capture,'modules',v.name));if(createHash('sha256').update(b).digest('hex')!==v.sha256)throw Error('Baseline mismatch');if(!v.name.startsWith('social')||/^social-(1b|2|3)(-focus)?\.txt$/.test(v.name))await add(v.name,b,v.content_type)}
for(const [file,name,type]of [['entry.js','social-entry.js','application/javascript+module'],['auth.js','social-auth.js','application/javascript+module'],['images.json','social-images.txt','text/plain'],['backend.js','social-backend.js','application/javascript+module'],['data.js','social-data.js','application/javascript+module'],['views.js','social-views.js','application/javascript+module'],['style.css','social.css','text/plain'],['client.txt','social.txt','text/plain'],['focus.txt','social-focus.txt','text/plain'],['collected.json','social-collected.txt','text/plain']])await add(name,await readFile(resolve(source,file)),type);
for(const [from,to]of [['social.txt','social-4.txt'],['social-focus.txt','social-4-focus.txt']])await add(to,await readFile(resolve(capture,'modules',from)),'text/plain');
const auth=JSON.parse(await readFile(resolve('../social5-auth-config.json'),'utf8'));const added=[{type:'plain_text',name:'SUPABASE_URL',text:auth.url},{type:'plain_text',name:'SUPABASE_PUBLIC_KEY',text:auth.key}];
await writeFile(resolve(dest,'manifest.json'),JSON.stringify({...m,bindings:[...m.bindings,...added],release:'20261008-social-5',presentationRelease:'20261008-marketplace-1',baselineVersion:m.version,baselineBindings:m.bindings,main_module:'social-entry.js',originalModulesRetained:57,modules},null,2));
const config={name:'communiverse-marketplace',main:'social-entry.js',compatibility_date:m.compatibility_date,no_bundle:true,find_additional_modules:true,rules:[{type:'ESModule',globs:['**/*.js'],fallthrough:true},{type:'Text',globs:['**/*.txt','**/*.css'],fallthrough:true},{type:'Data',globs:['**/*.mp4','**/*.jpg'],fallthrough:true}],d1_databases:[{binding:'COMMUNIVERSE_DB',database_name:'communiverse-clubs-db',database_id:'6126080a-3d53-4043-baa5-3d2ebb4781bb'}],r2_buckets:[{binding:'COMMUNIVERSE_MEDIA',bucket_name:'communiverse-media'}],services:[{binding:'LEGACY',service:'communiverse',environment:'production'}],vars:{SUPABASE_URL:auth.url,SUPABASE_PUBLIC_KEY:auth.key},send_email:[{name:'EMAIL',allowed_sender_addresses:['welcome@communiverse.espacios.me']}]};await writeFile(resolve(dest,'wrangler.jsonc'),JSON.stringify(config,null,2));console.log(JSON.stringify({retained:57,oldImmutableScripts:8,total:modules.length}));
