import assert from'node:assert/strict';import{readFile}from'node:fs/promises';import{DatabaseSync}from'node:sqlite';import{pathToFileURL}from'node:url';import{resolve}from'node:path';
const dir=resolve(process.argv[2]||'../social-candidate'),{api,issue,upload,rank}=await import(pathToFileURL(dir+'/social-backend.js')),{signup}=await import(pathToFileURL(dir+'/market-members.js')),{CATALOG}=await import(pathToFileURL(dir+'/social-data.js'));
const db=new DatabaseSync(':memory:');for(const p of ['marketplace-20261008','social-20261008'])db.exec(await readFile('worker/releases/'+p+'/migration.sql','utf8'));
db.exec(await readFile('worker/releases/social-20261008/migration-9.sql','utf8'));db.exec(await readFile('worker/releases/social-20261008/migration-10.sql','utf8'));
const adapter={prepare(sql){let params=[];const a={bind(...p){params=p;return a},async first(){return db.prepare(sql).get(...params)||null},async all(){return{results:db.prepare(sql).all(...params)}},async run(){return{meta:{changes:db.prepare(sql).run(...params).changes}}}};return a},async batch(queries){db.exec('BEGIN');try{const out=[];for(const q of queries)out.push(await q.run());db.exec('COMMIT');return out}catch(e){db.exec('ROLLBACK');throw e}}};
const messages=[],objects=new Map(),env={COMMUNIVERSE_DB:adapter,EMAIL:{async send(m){messages.push(m);return{messageId:'local-only'}}},COMMUNIVERSE_MEDIA:{async put(k,b,m){objects.set(k,{b,m})}}};for(const i of CATALOG)db.prepare('INSERT INTO cv_catalog(id,kind,artist,region,data,tags,checked_at) VALUES(?,?,?,?,?,?,?)').run(i.id,i.kind,i.artist||'',i.region||'',JSON.stringify(i),JSON.stringify(i.tags),'2026-10-08');
const request=(p,b,cookie='',ip='social-test',origin='https://espacios.me')=>new Request('https://espacios.me/communiverse/api/'+p,{method:b===undefined?'GET':'POST',headers:{'Content-Type':'application/json',Origin:origin,Cookie:cookie,'CF-Connecting-IP':ip},body:b===undefined?undefined:JSON.stringify(b)});
const base={firstName:'Ada',city:'Manila',craft:'Pottery',email:'ada@example.test',phone:'+639171234567',kind:'artist',consent:true,requestId:crypto.randomUUID()};let r=await signup(request('members',base),env);assert.equal(r.status,201);const created=await r.json(),id=created.profileUrl.split('member-')[1],cookie=await issue(id,env);let m=await(await api(request('me',undefined,cookie),env)).json();assert.equal(m.member.verified,false);for(const field of ['email','phone','confirmation_hash','request_key'])assert.ok(!JSON.stringify(m).includes(field+'":'));
assert.equal((await api(request('hearts',{id:'seam-vase',active:true}),env)).status,401);assert.equal((await api(request('hearts',{id:'seam-vase',active:true},cookie,'csrf','https://bad.test'),env)).status,403);
assert.equal((await api(request('auth/start',{email:base.email},'', 'login'),env)).status,200);assert.equal(messages.length,2);const token=messages.at(-1).text.match(/sign-in\/#([a-f0-9]{64})/)[1];assert.notEqual(db.prepare('SELECT hash FROM cv_login_links').get().hash,token);r=await api(request('auth/finish',{token},'', 'login'),env);assert.equal(r.status,200);const signed=r.headers.get('Set-Cookie');for(const v of ['HttpOnly','Secure','SameSite=Lax'])assert.ok(signed.includes(v));assert.equal((await api(request('auth/finish',{token},'', 'login'),env)).status,400);assert.equal((await api(request('auth/start',{email:'missing@example.test'},'', 'unknown'),env)).status,200);assert.equal(messages.length,2);
r=await api(request('hearts',{id:'seam-vase',active:true},signed),env);assert.equal(r.status,200);assert.equal((await r.json()).items[0].hearts,1);await api(request('hearts',{id:'seam-vase',active:true},signed),env);assert.equal(db.prepare('SELECT count(*) n FROM cv_hearts').get().n,1);assert.equal((await api(request('follows',{id:'artist-amina-rahmani',active:true},signed),env)).status,200);await api(request('follows',{id:'artist-amina-rahmani',active:true},signed),env);assert.equal(db.prepare('SELECT count(*) n FROM cv_follows').get().n,1);
let first=await(await api(request('feed',undefined,signed),env)).json(),ids=new Set(first.items.map(i=>i.id));assert.ok(first.cursor);let next=first.cursor;while(next){const d=await(await api(request('feed?cursor='+encodeURIComponent(next),undefined,signed),env)).json();for(const i of d.items){assert.ok(!ids.has(i.id));ids.add(i.id)}next=d.cursor}assert.equal(ids.size,first.total);const saved=await(await api(request('feed?saved=1',undefined,signed),env)).json();assert.deepEqual(saved.items.map(i=>i.id),['seam-vase']);assert.equal((await api(request('feed?cursor='+encodeURIComponent(first.cursor),undefined),env)).status,410);assert.equal(rank([{id:'a',tags:['ceramics'],artist:'potter'},{id:'b',tags:['photo'],artist:'photo'}],{liked:[{tags:['ceramics']}],follows:['potter']})[0].id,'a');
const postId=crypto.randomUUID(),post={requestId:postId,kind:'work',title:'A vessel',body:'Made by me <script>no</script>',region:'philippines',url:'https://example.com/work'};assert.equal((await api(request('community',post,signed),env)).status,201);await api(request('community',post,signed),env);assert.equal(db.prepare('SELECT count(*) n FROM cv_posts').get().n,1);let comment={requestId:crypto.randomUUID(),target:postId,body:'I love the form.'};assert.equal((await api(request('comments',comment,signed),env)).status,201);await api(request('comments',comment,signed),env);assert.equal(db.prepare('SELECT count(*) n FROM cv_comments').get().n,1);assert.equal((await api(request('community',{...post,requestId:crypto.randomUUID(),url:'javascript:alert(1)'},signed),env)).status,400);assert.equal((await api(request('community',{...post,requestId:crypto.randomUUID(),image:'/communiverse/_public/community/someone-else/a.jpg'},signed),env)).status,400);
const second={...base,firstName:'Ben',email:'ben@example.test',requestId:crypto.randomUUID()};r=await signup(request('members',second,'','second'),env);const bid=(await r.json()).profileUrl.split('member-')[1],bcookie=await issue(bid,env);assert.equal((await api(request('community',{...post,requestId:crypto.randomUUID()},bcookie),env)).status,403);await api(request('content/remove',{id:postId,kind:'post'},bcookie),env);assert.equal(db.prepare('SELECT status FROM cv_posts WHERE id=?').get(postId).status,'active');r=await upload(new Request('https://espacios.me/communiverse/api/upload',{method:'POST',headers:{Origin:'https://espacios.me',Cookie:signed},body:'<svg>bad</svg>'}),env);assert.equal(r.status,400);assert.equal(objects.size,0);await api(request('content/remove',{id:postId,kind:'post'},signed),env);assert.equal((await api(request('item?id='+postId),env)).status,404);await api(request('auth/logout',{},signed),env);assert.equal((await(await api(request('me',undefined,signed),env)).json()).member,null);assert.ok(CATALOG.filter(i=>i.kind==='work').every(i=>i.tags.length>=3));assert.ok(CATALOG.filter(i=>i.kind==='event').every(i=>i.source.startsWith('https:')&&(!i.end||i.start<=i.end)));
// Event dates, hosting permissions, ownership and regional curation use real SQLite.
const {eventState,ambassadorFor}=await import(pathToFileURL(dir+'/social-data.js'));
assert.equal(eventState({kind:'event',start:'2026-10-09',end:'2026-10-11'},new Date('2026-10-08T12:00Z')),'upcoming');
assert.equal(eventState({kind:'event',start:'2026-10-01',end:'2026-10-08'},new Date('2026-10-08T12:00Z')),'now');
assert.equal(eventState({kind:'event',start:'2026-10-01',end:'2026-10-07'},new Date('2026-10-08T12:00Z')),'past');
assert.equal(eventState({kind:'venue'}),'places');assert.equal(ambassadorFor({id:'a',region:'colombia'}),'cv-luna');assert.equal(ambassadorFor({id:'b',region:'saudi'}),'cv-abdallah-mahmoudd');assert.equal(ambassadorFor({id:'c',region:'philippines'}),'cv-turbooz');
let listing=await(await api(request('artists'),env)).json();assert.equal(listing.artists.filter(a=>a.kind==='ambassador').length,0);listing=await(await api(request('artists?id=cv-luna'),env)).json();assert.equal(listing.artists[0].kind,'ambassador');listing=await(await api(request('artists?ambassador=cv-luna'),env)).json();assert.ok(listing.artists.length);assert.ok(listing.artists.every(a=>a.ambassador==='cv-luna'));
for(const state of ['upcoming','now','past','places']){const result=await(await api(request('events?state='+state),env)).json();assert.ok(result.total>0);assert.ok(result.events.every(e=>e.state===state));}
const acookie=await issue(id,env),future=new Date(Date.now()+86400000*5).toISOString().slice(0,10),event={requestId:crypto.randomUUID(),title:'Clay together',type:'Workshop',region:'philippines',city:'Manila',venue:'My studio',description:'A small-group clay workshop. Free entry.',start:future,end:future,url:''};
assert.equal((await api(request('events',event),env)).status,401);assert.equal((await api(request('events',event,bcookie),env)).status,403);assert.equal((await api(request('events',{...event,end:'2030-02-30'},acookie),env)).status,400);
assert.equal((await api(request('events',event,acookie),env)).status,201);await api(request('events',event,acookie),env);assert.equal(db.prepare('SELECT count(*) n FROM cv_hosted_events').get().n,1);await api(request('content/remove',{id:event.requestId,kind:'event'},bcookie),env);assert.equal(db.prepare('SELECT status FROM cv_hosted_events').get().status,'active');await api(request('content/remove',{id:event.requestId,kind:'event'},acookie),env);assert.equal(db.prepare('SELECT status FROM cv_hosted_events').get().status,'hidden');
await api(request('me',{firstName:'Ada',city:'Manila',craft:'Pottery',bio:'I collect ceramics.',instagram:'',tiktok:'',region:'philippines',intent:'collector'},acookie),env);assert.equal((await api(request('events',{...event,requestId:crypto.randomUUID()},acookie),env)).status,403);
console.log(JSON.stringify({pass:true,checks:['private sessions','single-use email links','no account enumeration','CSRF','verified public posting','heart/follow idempotency','real heart aggregates','tag ranking','stable pagination','private saved collection','post/comment idempotency','ownership removal','URL/upload validation','logout invalidation','source-backed catalog','event state boundaries','verified artisan hosting','event idempotency and removal','ambassador curation','collector role'],catalog:CATALOG.length,works:ids.size}));
