import {hash,validateSignup,welcome} from './market-members.js';
import {body,json,limited,session} from './social-backend.js';
import {passwordHash,staffSession} from './social-workspace.js';
const fail=(m,s=400)=>{throw Object.assign(Error(m),{status:s})};
const rand=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');
const cookie=(name,value,age=7776000)=>name+'='+value+'; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age='+age;
const equal=(a,b)=>{let d=a.length^b.length;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0};
export const accountToken=r=>r.headers.get('Cookie')?.match(/(?:^|;\s*)__Host-cv-account=([a-f0-9]{64})(?:;|$)/)?.[1];
export async function accountSession(request,env){const t=accountToken(request);if(!t)return null;const db=env.COMMUNIVERSE_DB,a=await db.prepare('SELECT a.* FROM cv_account_sessions s JOIN cv_accounts a ON a.identity_id=s.identity_id WHERE s.hash=? AND s.expires_at>?').bind(await hash(t),Date.now()).first();if(!a)return null;const active=a.staff_id?await db.prepare("SELECT id FROM cv_staff WHERE id=? AND status='active'").bind(a.staff_id).first():await db.prepare("SELECT id FROM cv_members WHERE id=? AND status='active'").bind(a.member_id).first();return active?a:null;}
export async function ensureMemberAccount(db,m){let a=await db.prepare('SELECT * FROM cv_accounts WHERE member_id=?').bind(m).first();if(a)return a;const id='member-'+m;await db.prepare('INSERT OR IGNORE INTO cv_accounts(identity_id,member_id,username,salt,password_hash) VALUES(?,?,?,?,?)').bind(id,m,'member.'+m,rand(),'').run();return db.prepare('SELECT * FROM cv_accounts WHERE member_id=?').bind(m).first();}
export async function ensureStaffAccount(db,p){let a=await db.prepare('SELECT * FROM cv_accounts WHERE staff_id=?').bind(p.id).first();if(a)return a;const full=await db.prepare('SELECT * FROM cv_staff WHERE id=?').bind(p.id).first(),mid='staff-'+p.id;await db.batch([db.prepare("INSERT OR IGNORE INTO cv_members(id,request_key,email,phone,first_name,city,craft,kind,status,confirmation_hash,confirmation_expires_at,email_verified_at) VALUES(?,?,?,'',?,'',?,'member','hidden','','',CURRENT_TIMESTAMP)").bind(mid,'staff:'+p.id,p.id+'@internal.communiverse.invalid',p.name,full.title),db.prepare('INSERT OR IGNORE INTO cv_accounts(identity_id,member_id,staff_id,username,salt,password_hash,iterations) VALUES(?,?,?,?,?,?,?)').bind(p.id,mid,p.id,full.username,full.salt,full.password_hash,full.iterations)]);return db.prepare('SELECT * FROM cv_accounts WHERE staff_id=?').bind(p.id).first();}
export async function issueAccount(identity,env){const t=rand();await env.COMMUNIVERSE_DB.prepare('INSERT INTO cv_account_sessions(hash,identity_id,expires_at) VALUES(?,?,?)').bind(await hash(t),identity,Date.now()+90*86400000).run();return cookie('__Host-cv-account',t);}
function withCookies(data,set,status=200){const r=json(data,status);for(const c of set)r.headers.append('Set-Cookie',c);return r;}
const clearLegacy=()=>['__Host-cv-session','__Host-cv-workspace'].map(k=>cookie(k,'',0));
function credentials(b){const username=String(b.username||'').trim().toLowerCase(),password=String(b.password||'');if(!/^[a-z0-9][a-z0-9._-]{2,39}$/.test(username)||password.length<8||password.length>128)fail('Use a username of 3–40 letters or numbers and a password of at least 8 characters.');return{username,password};}
export async function accountAPI(request,env){const endpoint=new URL(request.url).pathname.split('/').filter(Boolean).pop(),db=env.COMMUNIVERSE_DB;try{
 if(request.method==='GET'&&endpoint==='credentials'){const a=await accountSession(request,env),s=await staffSession(request,env),m=await session(request,env),current=a||(s?await ensureStaffAccount(db,s):m?await ensureMemberAccount(db,m.id):null);if(!current)fail('Sign in to continue.',401);return json({username:current.username.startsWith('member.')?'':current.username,hasPassword:!!current.password_hash});}
 const b=await body(request,7000);
 if(endpoint==='logout'){for(const [name,table] of [['__Host-cv-account','cv_account_sessions'],['__Host-cv-session','cv_sessions'],['__Host-cv-workspace','cv_staff_sessions']]){const t=request.headers.get('Cookie')?.match(new RegExp('(?:^|;\\s*)'+name+'=([a-f0-9]{64})'))?.[1];if(t)await db.prepare('DELETE FROM '+table+' WHERE hash=?').bind(await hash(t)).run()}return withCookies({ok:true},[cookie('__Host-cv-account','',0),...clearLegacy()]);}
 if(endpoint==='login'){await limited(request,db,'account-login',30);const username=String(b.username||'').trim().toLowerCase(),password=String(b.password||'');if(username.length>60||password.length>128)fail('Check your username and password.',401);let a=await db.prepare('SELECT * FROM cv_accounts WHERE username=? COLLATE NOCASE').bind(username).first();const staff=await db.prepare("SELECT * FROM cv_staff WHERE lower(username)=? AND status='active'").bind(username).first();if(!a&&staff)a=await ensureStaffAccount(db,staff);const derived=await passwordHash(password,a?.salt||'comm-universe-dummy-salt',a?.iterations||100000);if(!a||!a.password_hash||!equal(derived,a.password_hash))fail('Check your username and password.',401);const active=a.staff_id?await db.prepare("SELECT id FROM cv_staff WHERE id=? AND status='active'").bind(a.staff_id).first():await db.prepare("SELECT id FROM cv_members WHERE id=? AND status='active'").bind(a.member_id).first();if(!active)fail('Check your username and password.',401);return withCookies({ok:true,profileUrl:'/communiverse/workspace/'},[await issueAccount(a.identity_id,env),...clearLegacy()]);}
 if(endpoint==='register'){await limited(request,db,'account-register',6);let p;try{p=validateSignup(b)}catch(e){fail(e.message)}const {username,password}=credentials(b);if(await db.prepare('SELECT id FROM cv_staff WHERE lower(username)=? UNION SELECT identity_id FROM cv_accounts WHERE username=? COLLATE NOCASE').bind(username,username).first())fail('That username is already in use.',409);if(await db.prepare('SELECT id FROM cv_members WHERE email=?').bind(p.email).first())fail('This email already has an account. Use account recovery to set your username and password.',409);const id=crypto.randomUUID(),salt=rand(),confirmation=rand(),password_hash=await passwordHash(password,salt),intent=['artist','collector','city-representative','cool-kids'].includes(b.intent)?b.intent:'collector';await db.batch([db.prepare('INSERT INTO cv_members(id,request_key,email,phone,first_name,city,craft,kind,instagram,tiktok,confirmation_hash,confirmation_expires_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,await hash(b.requestId),p.email,p.phone,p.first_name,p.city,p.craft,p.kind,p.instagram,p.tiktok,await hash(confirmation),new Date(Date.now()+7*86400000).toISOString()),db.prepare('INSERT INTO cv_accounts(identity_id,member_id,username,salt,password_hash) VALUES(?,?,?,?,?)').bind('member-'+id,id,username,salt,password_hash),db.prepare('INSERT INTO cv_member_preferences(member_id,intent) VALUES(?,?)').bind(id,intent)]);let emailStatus='failed';try{await env.EMAIL.send(welcome({...p,id},confirmation));emailStatus='sent'}catch{}await db.prepare('UPDATE cv_members SET welcome_status=? WHERE id=?').bind(emailStatus,id).run();return withCookies({ok:true,profileUrl:'/communiverse/workspace/',emailStatus,message:'Welcome, '+p.first_name+'. Your circle and workspace are ready.'},[await issueAccount('member-'+id,env),...clearLegacy()],201);}
 if(endpoint==='credentials'){await limited(request,db,'account-password',10);const a=await accountSession(request,env),s=await staffSession(request,env),m=await session(request,env),current=a||(s?await ensureStaffAccount(db,s):m?await ensureMemberAccount(db,m.id):null);if(!current)fail('Sign in to continue.',401);const {username,password}=credentials(b);if(current.password_hash&&!equal(await passwordHash(String(b.currentPassword||''),current.salt,current.iterations),current.password_hash))fail('Check your current password.',401);if(!current.password_hash&&!m?.email_verified_at)fail('Confirm your email before setting account credentials.',403);const used=await db.prepare('SELECT identity_id FROM cv_accounts WHERE username=? COLLATE NOCASE AND identity_id<>?').bind(username,current.identity_id).first(),reserved=await db.prepare('SELECT id FROM cv_staff WHERE lower(username)=?').bind(username).first();if(used||reserved&&reserved.id!==current.staff_id)fail('That username is already in use.',409);const salt=rand(),digest=await passwordHash(password,salt);await db.batch([db.prepare('UPDATE cv_accounts SET username=?,salt=?,password_hash=? WHERE identity_id=?').bind(username,salt,digest,current.identity_id),...(current.staff_id?[db.prepare('UPDATE cv_staff SET username=?,salt=?,password_hash=? WHERE id=?').bind(username,salt,digest,current.staff_id),db.prepare('DELETE FROM cv_staff_sessions WHERE staff_id=?').bind(current.staff_id)]:[]),db.prepare('DELETE FROM cv_account_sessions WHERE identity_id=?').bind(current.identity_id),db.prepare('DELETE FROM cv_sessions WHERE member_id=?').bind(current.member_id)]);return withCookies({ok:true},[await issueAccount(current.identity_id,env),...clearLegacy()]);}
 return json({error:'Not found'},404);
}catch(e){return json({error:e.status?e.message:String(e.message).includes('UNIQUE')?'That username or email is already in use.':'Your account could not be updated. Try again.'},e.status||409)}}
