import {body,json,limited} from './social-backend.js';
import {staffSession,passwordHash} from './social-workspace.js';
import {ensureStaffAccount,ensureMemberAccount} from './social-accounts.js';
const fail=(m,s=400)=>{throw Object.assign(Error(m),{status:s})},clean=(v,n)=>typeof v==='string'?v.trim().slice(0,n):'',q=s=>'"'+String(s).replaceAll('"','""')+'"',rows=async(db,s,...v)=>(await db.prepare(s).bind(...v).all()).results;
const roles=['ceo','operations','ambassador-lead','brand','platform','ai','latam','advisor','ambassador'];
async function entity(db,kind,id){if(kind==='community'){const c=await db.prepare('SELECT id,name,description FROM cv_circles WHERE id=?').bind(id).first();return c&&{...c,kind};}if(kind==='artist'){const c=await db.prepare("SELECT data FROM cv_catalog WHERE id=? AND kind IN ('artist','ambassador')").bind(id).first();if(c){const d=JSON.parse(c.data);return{id,kind,name:d.title,description:d.description,city:d.city}}}const s=await db.prepare('SELECT id,name,username,role,title,profile_slug,status FROM cv_staff WHERE id=?').bind(id).first();if(s)return{...s,kind:'staff'};const m=await db.prepare('SELECT m.id,m.first_name name,m.city,m.craft,m.kind role,m.status,a.username FROM cv_members m LEFT JOIN cv_accounts a ON a.member_id=m.id WHERE m.id=?').bind(id.replace(/^member-/, '')).first();return m&&{...m,id:'member-'+m.id,member_id:m.id,kind:'member'};}
async function purgePlan(db,e){const tables=await rows(db,"SELECT name FROM sqlite_master WHERE type='table' AND name LIKE 'cv_%' AND name NOT IN ('cv_admin_audit','cv_admin_deleted','cv_admin_media_cleanup','cv_join_limits')"),plan=new Map(),info=new Map(),refs=new Map(),keys=new Set(),values=[e.id,...(e.member_id?[e.member_id]:[]),...(e.profile_slug?[e.profile_slug]:[])];const linked=await db.prepare('SELECT member_id FROM cv_accounts WHERE identity_id=?').bind(e.id).first();if(linked?.member_id)values.push(linked.member_id,'member-'+linked.member_id);if(e.kind!=='community'){const aliases=await rows(db,'SELECT member_id,artist_id FROM cv_artist_accounts');for(const a of aliases)if(values.includes(a.artist_id)||values.includes(a.member_id)||values.includes('member-'+a.member_id))values.push(a.artist_id,a.member_id,'member-'+a.member_id);}
 for(const {name}of tables){const cols=await rows(db,'PRAGMA table_info('+q(name)+')'),fks=await rows(db,'PRAGMA foreign_key_list('+q(name)+')');info.set(name,cols);refs.set(name,fks);plan.set(name,new Map());}
 const add=(table,row)=>{const columns=info.get(table),pk=columns.filter(c=>c.pk).map(c=>c.name),key=JSON.stringify(pk.length?pk.map(k=>row[k]):row);if(plan.get(table).has(key))return false;plan.get(table).set(key,row);if(row.key&&typeof row.key==='string')keys.add(row.key);if(row.photo_key)keys.add(row.photo_key);if(row.object_key)keys.add(row.object_key);if(row.image?.startsWith('/communiverse/_public/community/'))keys.add(row.image.slice('/communiverse/_public/'.length));return true};
 const targeted=new Set(['member_id','staff_id','identity_id','artist_id','artist','owner_id','created_by','sender_id','uploader_id','assigned_to','ambassador_id','reviewer_id','profile_slug','target','entity_id']);
 for(const {name}of tables){let columns=info.get(name).filter(c=>targeted.has(c.name)).map(c=>c.name);if(e.kind==='community')columns=info.get(name).filter(c=>c.name==='circle_id').map(c=>c.name);const root=(e.kind==='community'&&name==='cv_circles')||(e.kind==='artist'&&name==='cv_catalog')||(e.kind==='staff'&&name==='cv_staff')||(e.kind==='member'&&name==='cv_members');if(root||(e.kind!=='community'&&['cv_catalog','cv_members'].includes(name)))columns.push('id');if(!columns.length)continue;const placeholders=values.map(()=>'?').join(','),sql=columns.map(c=>q(c)+' IN ('+placeholders+')').join(' OR ');for(const row of await rows(db,'SELECT * FROM '+q(name)+' WHERE '+sql,...columns.flatMap(()=>values)))add(name,row);}
 // Catalogue works also reference the artist inside JSON, and IDs in application targets
 // lack SQL foreign keys. Both are included before the physical delete.
 if(e.kind==='artist')for(const row of await rows(db,"SELECT * FROM cv_catalog WHERE artist=?",e.id))add('cv_catalog',row);
 for(let pass=0;pass<20;pass++){let changed=false;for(const {name}of tables){for(const fk of refs.get(name)){const parents=plan.get(fk.table);if(!parents?.size)continue;const col=fk.to||info.get(fk.table).find(c=>c.pk)?.name;if(!col)continue;const vs=[...new Set([...parents.values()].map(x=>x[col]).filter(v=>v!=null))];for(let i=0;i<vs.length;i+=60){const v=vs.slice(i,i+60);for(const row of await rows(db,'SELECT * FROM '+q(name)+' WHERE '+q(fk.from)+' IN ('+v.map(()=>'?').join(',')+')',...v))changed=add(name,row)||changed;}}
 const ids=[...plan.values()].flatMap(m=>[...m.values()].map(r=>r.id)).filter(Boolean);for(const c of info.get(name).filter(c=>['target','item_id','entity_id','post_id'].includes(c.name)))for(let i=0;i<ids.length;i+=60){const v=ids.slice(i,i+60);for(const row of await rows(db,'SELECT * FROM '+q(name)+' WHERE '+q(c.name)+' IN ('+v.map(()=>'?').join(',')+')',...v))changed=add(name,row)||changed;}}
 if(!changed)break;if(pass===19)fail('This account has a large dependency graph. Review it before deleting.',409);}
 for(const row of plan.get('cv_catalog')?.values()||[])if(row.id&&!values.includes(row.id))values.push(row.id);return{plan,info,keys,summary:[...plan].filter(([,v])=>v.size).map(([table,rows])=>({table,count:rows.size})),values};}
export async function adminAPI(request,env,ctx){const db=env.COMMUNIVERSE_DB;try{const p=await staffSession(request,env);if(!p||!['keiffer','haseeb'].includes(p.id))fail('Account management is available to Keiffer and Haseeb.',403);const u=new URL(request.url),action=u.pathname.split('/').filter(Boolean).pop();if(request.method==='GET'){if(action==='list'){const staff=await rows(db,'SELECT id,name,role,title,status,profile_slug,username FROM cv_staff ORDER BY name'),members=await rows(db,"SELECT 'member-'||m.id id,m.first_name name,m.kind role,m.craft title,m.status,a.username FROM cv_members m LEFT JOIN cv_accounts a ON a.member_id=m.id WHERE m.id NOT LIKE 'staff-%' ORDER BY m.first_name LIMIT 1000"),artists=(await rows(db,"SELECT data FROM cv_catalog WHERE kind='artist'")).map(r=>{const a=JSON.parse(r.data);return{id:a.id,name:a.title,title:a.city,city:a.city,description:a.description,kind:'artist'}}),circles=await rows(db,'SELECT id,name,description,description title FROM cv_circles ORDER BY name');return json({items:[...staff.map(x=>({...x,kind:'staff'})),...members.map(x=>({...x,kind:'member'})),...artists,...circles.map(x=>({...x,kind:'community'}))]});}return json({error:'Not found'},404)}
 const b=await body(request,6000);await limited(request,db,'account-admin',60);
 if(action==='save'){const name=clean(b.name,100),username=clean(b.username,40).toLowerCase(),password=clean(b.password,128),kind=['staff','member','artist','community'].includes(b.kind)?b.kind:'member';if(!name)fail('Add a name.');const e=b.id?await entity(db,kind,b.id):null;if(b.id&&!e)fail('This entry no longer exists.',404);if(e?.kind==='artist'){const row=await db.prepare('SELECT data FROM cv_catalog WHERE id=?').bind(e.id).first(),a=JSON.parse(row.data);a.title=name;a.city=clean(b.city,100)||a.city;a.description=clean(b.description,2500);await db.prepare('UPDATE cv_catalog SET data=? WHERE id=?').bind(JSON.stringify(a),e.id).run();return json({ok:true,id:e.id})}if(e?.kind==='community'){await db.prepare("UPDATE cv_circles SET name=?,description=?,search=lower(?||' '||?||' '||craft||' '||tags) WHERE id=?").bind(name,clean(b.description,2500),name,clean(b.description,2500),e.id).run();return json({ok:true,id:e.id})}
 if(!/^[a-z0-9][a-z0-9._-]{2,39}$/.test(username))fail('Use a username of 3–40 letters or numbers.');if(password&&(password.length<8||password.length>128))fail('Use a password with at least 8 characters.');if(!e&&!password)fail('Set the new account password.');const duplicate=await db.prepare('SELECT identity_id id FROM cv_accounts WHERE username=? COLLATE NOCASE UNION SELECT id FROM cv_staff WHERE lower(username)=?').bind(username,username).all();if(duplicate.results.some(x=>x.id!==e?.id))fail('This username is in use.',409);const salt=crypto.randomUUID(),digest=password?await passwordHash(password,salt):'',id=e?.id||(kind==='staff'?'team-'+crypto.randomUUID():'member-'+crypto.randomUUID());let statements=[];
 if(kind==='staff'||e?.kind==='staff'){const role=roles.includes(b.role)?b.role:'advisor',title=clean(b.title,140)||role,slug=e?.profile_slug||'cv-'+id;if(e){await ensureStaffAccount(db,e);statements.push(db.prepare('UPDATE cv_staff SET name=?,username=?,role=?,title=? WHERE id=?').bind(name,username,role,title,id),db.prepare('UPDATE cv_accounts SET username=? WHERE identity_id=?').bind(username,id));}else{statements.push(db.prepare('INSERT INTO cv_staff(id,username,name,role,title,profile_slug,salt,password_hash) VALUES(?,?,?,?,?,?,?,?)').bind(id,username,name,role,title,slug,salt,digest));}if(e&&password)statements.push(db.prepare('UPDATE cv_staff SET salt=?,password_hash=? WHERE id=?').bind(salt,digest,id));statements.push(db.prepare("INSERT INTO cv_identity_profiles(identity_id,profile_slug,name) VALUES(?,?,?) ON CONFLICT(identity_id) DO UPDATE SET name=excluded.name").bind(id,slug,name));}
 else{if(e)await ensureMemberAccount(db,e.member_id);const mid=e?.member_id||id.slice(7),role=b.role==='artist'?'artist':'member',email=clean(b.email,254).toLowerCase()||username+'@accounts.communiverse.invalid';if(e)statements.push(db.prepare('UPDATE cv_members SET first_name=?,city=?,craft=?,kind=? WHERE id=?').bind(name,clean(b.city,100),clean(b.title,100),role,mid),db.prepare('UPDATE cv_accounts SET username=? WHERE identity_id=?').bind(username,id));else statements.push(db.prepare("INSERT INTO cv_members(id,request_key,email,phone,first_name,city,craft,kind,confirmation_hash,confirmation_expires_at) VALUES(?,?,?,'',?,?,?,?, '', '')").bind(mid,'admin:'+id,email,name,clean(b.city,100),clean(b.title,100),role),db.prepare('INSERT INTO cv_accounts(identity_id,member_id,username,salt,password_hash) VALUES(?,?,?,?,?)').bind(id,mid,username,salt,digest));}
 if(e?.kind==='member')statements.push(db.prepare('UPDATE cv_identity_profiles SET name=? WHERE identity_id=?').bind(name,id));if(e&&password)statements.push(db.prepare('UPDATE cv_accounts SET salt=?,password_hash=? WHERE identity_id=?').bind(salt,digest,id),db.prepare('DELETE FROM cv_account_sessions WHERE identity_id=?').bind(id),db.prepare('DELETE FROM cv_staff_sessions WHERE staff_id=?').bind(id),db.prepare('DELETE FROM cv_sessions WHERE member_id=?').bind(e.member_id||'staff-'+id));statements.push(db.prepare('INSERT INTO cv_admin_audit(id,actor_id,action,target) VALUES(?,?,?,?)').bind(crypto.randomUUID(),p.id,e?'edit-account':'create-account',id));await db.batch(statements);return json({ok:true,id});}
 if(['delete-preview','delete'].includes(action)){const e=await entity(db,b.kind,b.id);if(!e)fail('This entry is no longer available.',404);if(e.id===p.id)fail('You cannot delete the account you are using.');const d=await purgePlan(db,e);if(action==='delete-preview')return json({entity:e,affected:d.summary,total:d.summary.reduce((n,x)=>n+x.count,0)});if(b.confirm!==e.name)fail('Type the exact name to confirm permanent deletion.');const statements=[db.prepare('PRAGMA defer_foreign_keys=ON')];for(const [table,records]of d.plan){const pk=d.info.get(table).filter(c=>c.pk).map(c=>c.name);for(const row of records.values()){const columns=pk.length?pk:Object.keys(row);statements.push(db.prepare('DELETE FROM '+q(table)+' WHERE '+columns.map(c=>q(c)+' IS ?').join(' AND ')).bind(...columns.map(c=>row[c])))}}for(const id of d.values)statements.push(db.prepare('INSERT OR REPLACE INTO cv_admin_deleted(id,kind,actor_id) VALUES(?,?,?)').bind(id,e.kind,p.id));statements.push(...[...d.keys].map(key=>db.prepare('INSERT OR IGNORE INTO cv_admin_media_cleanup(object_key) VALUES(?)').bind(key)),db.prepare('DELETE FROM cv_feed_snapshots'),db.prepare('INSERT INTO cv_admin_audit(id,actor_id,action,target) VALUES(?,?,?,?)').bind(crypto.randomUUID(),p.id,'delete',e.id));await db.batch(statements);let pendingFiles=0;for(const {object_key:key} of await rows(db,'SELECT object_key FROM cv_admin_media_cleanup LIMIT 200'))try{await env.COMMUNIVERSE_MEDIA.delete(key);await db.prepare('DELETE FROM cv_admin_media_cleanup WHERE object_key=?').bind(key).run()}catch{pendingFiles++}return json({ok:true,removed:d.summary,pendingFiles});}
 return json({error:'Not found'},404);
}catch(e){return json({error:e.status?e.message:'The change could not be saved. No completion has been confirmed.'},e.status||409)}}
