import {body,json,limited} from './social-backend.js';
import {workspacePrincipal,workspaceAPI} from './social-workspace.js';
import {collaborationAPI} from './social-collaboration.js';
import {model} from './social-ai.js';
const fail=(m,s=400)=>{throw Object.assign(Error(m),{status:s})},clean=(v,n=1500)=>typeof v==='string'?v.trim().slice(0,n):'';
export const ORGANIZATION={haseeb:'CEO. Strategy, fundraising and UAE/GCC. Approves pay, contracts, new ambassadors, equipment and subscriptions.',elferah:'Head of Operations. Arranges execution after Haseeb approval.',keiffer:'Leads the ambassador programme. Recruiting, scorecards, training, footage review. Receives Luna, Ammar and Balo requests; forwards approval to Haseeb with Elferah involved.',hassan:'Brand, UI and social publishing. Footage goes through his editor then Hassan to publish.',abel:'Platform, marketplace and product.',louis:'AI and artisan pipeline. Sends access and resource needs to Haseeb and Elferah.',alison:'LatAm and Colombia hub; supports Luna.',tariq:'Advisor for culture, art and events.',viktoriya:'Advisor for culture, art and events.',shakiba:'Advisor for culture, art and events.',luna:'Ambassador for Latin America. Reports to Keiffer.',ammar:'Ambassador. Reports to Keiffer.',balo:'Ambassador. Reports to Keiffer.'};
export function requestRoute(p,kind,amount){const reviewer=p.role==='ambassador'?'keiffer':p.role==='ai'||['pay','contract','ambassador','travel','kit','asset','subscription'].includes(kind)||amount!==null?'haseeb':'elferah';return reviewer==='keiffer'?['keiffer','haseeb','elferah']:reviewer==='haseeb'?['haseeb','elferah']:['elferah'];}
const resultUrl=(draft,p,id)=>'/communiverse/workspace/?'+(draft.kind==='task'&&p.kind==='staff'?'task=':draft.kind==='request'&&p.kind==='staff'?'request=':'view=connect&thread=')+encodeURIComponent(id);
const internal=(request,path,b)=>new Request(new URL('/communiverse/api/'+path,request.url),{method:'POST',headers:{Cookie:request.headers.get('Cookie')||'',Origin:new URL(request.url).origin,'Content-Type':'application/json'},body:JSON.stringify(b)});
export async function assistantAPI(request,env,ctx){try{const p=await workspacePrincipal(request,env);if(!p)fail('Sign in to ask Communiverse.',401);const db=env.COMMUNIVERSE_DB,b=await body(request,12000);await limited(request,db,'assistant',35);
 if(b.mode==='submit'){const draft=await db.prepare('SELECT * FROM cv_assistant_drafts WHERE id=? AND identity_id=?').bind(b.id,p.id).first();if(!draft)fail('This draft is unavailable.',404);if(draft.status==='submitted')return json({ok:true,id:draft.result_id,kind:draft.kind,url:resultUrl(draft,p,draft.result_id)});const payload=JSON.parse(draft.payload),v=b.values||{},title=clean(v.title||payload.title,140),description=clean(v.description||payload.description,2500);if(!title||!description)fail('Add a title and details before submitting.');let r;
 if(draft.kind==='request'&&p.kind==='staff'){const amount=v.amount===''||v.amount==null?null:Number(v.amount),currency=clean(v.currency||payload.currency||'AED',3).toUpperCase();r=await workspaceAPI(internal(request,'workspace/requests',{title,body:description,kind:payload.requestKind,amount,currency,requestId:draft.id}),env);}
 else if(draft.kind==='task'&&p.kind==='staff'){const project_id=clean(v.project_id||payload.project_id,100),owner_id=clean(v.owner_id||payload.owner_id||p.id,100);if(!project_id)fail('Choose the project for this task.');r=await workspaceAPI(internal(request,'workspace/tasks',{title,description,project_id,owner_id,status:'todo',priority:['low','normal','high','urgent'].includes(v.priority)?v.priority:'normal',due_date:v.due_date||'',requestId:draft.id}),env);}
 else{const participants=p.kind==='staff'&&payload.recipients?.length?payload.recipients:['elferah'];r=await collaborationAPI(internal(request,'workspace/connect/threads',{title,body:description,participants,requestId:draft.id}),env,ctx);}
 const result=await r.json();if(!r.ok)fail(result.error||'Please review the draft.',r.status);await db.prepare("UPDATE cv_assistant_drafts SET status='submitted',result_id=?,payload=? WHERE id=? AND identity_id=?").bind(result.id,JSON.stringify({...payload,title,description}),draft.id,p.id).run();return json({ok:true,id:result.id,kind:draft.kind,url:resultUrl(draft,p,result.id)});}
 const prompt=clean(b.prompt,2500);if(prompt.length<3)fail('Tell me what you have in mind.');const team=(await db.prepare("SELECT id,name,role,title FROM cv_staff WHERE status='active'").all()).results.map(x=>({...x,responsibilities:ORGANIZATION[x.id]||x.title}));let context={person:{id:p.id,name:p.name,role:p.role},team,projects:[],tasks:[],requests:[]};if(p.kind==='staff'){const r=await workspaceAPI(new Request(new URL('/communiverse/api/workspace/overview',request.url),{headers:request.headers}),env);if(!r.ok)fail('Your workspace context is unavailable.',503);const d=await r.json();context.projects=d.projects.map(x=>({id:x.id,title:x.title,owner:x.owner_id,status:x.status}));context.tasks=d.tasks.slice(0,60).map(x=>({id:x.id,title:x.title,owner:x.owner_id,project:x.project_id,status:x.status,due:x.due_date,approvalRequired:!!x.approval_required}));context.requests=d.requests.slice(0,40).map(x=>({id:x.id,title:x.title,stage:x.stage,reviewer:x.reviewer_id,creator:x.created_by}));}
 const response=await model(env,'You are Communiverse, a practical workspace assistant. Answer questions about the supplied team, tasks and approval dependencies using only authorized context. Do not invent contact information, availability, approved fees or status. For a question return {answer, action:"answer", nextStep}. For a clear request to obtain kit, camera, expense, access, subscription or help return action:"request"; for a task return action:"task"; for a message return action:"message". Return {answer,action,title,description,requestKind,owner_id,project_id,recipients,currency,nextStep}. requestKind is kit,asset,subscription,access,training,travel,pay,contract,resource,other. Unknown prices and dates stay blank; never invent them. Use actual IDs from context only. Requests from ambassadors go through Keiffer then Haseeb approval then Elferah; equipment and subscriptions require Haseeb before operations. A member can ask operations for support. You prepare an editable proposal; the user must submit. Never claim you sent or saved a request. No markdown links. Plain text only.',{prompt,context,history:Array.isArray(b.history)?b.history.slice(-6).map(x=>({role:x.role==='assistant'?'assistant':'user',content:clean(x.content,1000)})):[]});
 const requestedAction=['request','task','message'].includes(response.action)?response.action:'answer',action=p.kind!=='staff'&&requestedAction==='task'?'request':requestedAction,answer=clean(response.answer,2500),nextStep=clean(response.nextStep,500);if(action==='answer')return json({answer,nextStep,assisted:true});const requestKind=['kit','asset','subscription','access','training','travel','pay','contract','resource','other'].includes(response.requestKind)?response.requestKind:'resource',route=action==='request'?requestRoute(p,requestKind,null):[];const payload={title:clean(response.title,140)||'A request from '+p.name,description:clean(response.description,2500)||prompt,requestKind,project_id:context.projects.some(x=>x.id===response.project_id)?response.project_id:'',owner_id:team.some(x=>x.id===response.owner_id)?response.owner_id:p.id,recipients:Array.isArray(response.recipients)?response.recipients.filter(id=>team.some(x=>x.id===id)).slice(0,10):[],currency:/^[A-Z]{3}$/.test(response.currency||'')?response.currency:'AED',route};const id=crypto.randomUUID();await db.prepare('INSERT INTO cv_assistant_drafts(id,identity_id,kind,payload) VALUES(?,?,?,?)').bind(id,p.id,action,JSON.stringify(payload)).run();return json({answer,nextStep,assisted:true,draft:{id,kind:action,...payload},projects:context.projects,people:team.map(x=>({id:x.id,name:x.name})),cta:action==='task'?'Create task':action==='request'?'Submit request':'Send message'});
}catch(e){return json({error:e.status?e.message:'The assistant could not finish. Your request has not been submitted.'},e.status||503)}}
// In-app notification rows are the source of truth; email never contains private conversation text.
export async function flushNotifications(env){const db=env.COMMUNIVERSE_DB,jobs=(await db.prepare("SELECT * FROM cv_notification_delivery WHERE state IN ('pending','waiting-contact','failed') AND attempts<3 ORDER BY CASE state WHEN 'pending' THEN 0 WHEN 'failed' THEN 1 ELSE 2 END,updated_at LIMIT 30").all()).results;for(const j of jobs){let contact=await db.prepare('SELECT email FROM cv_identity_contacts WHERE identity_id=? AND email_verified=1').bind(j.identity_id).first();if(!contact&&j.identity_id.startsWith('member-'))contact=await db.prepare("SELECT email FROM cv_members WHERE id=? AND status='active' AND email_verified_at IS NOT NULL").bind(j.identity_id.slice(7)).first();if(!contact?.email){await db.prepare("UPDATE cv_notification_delivery SET state='waiting-contact',updated_at=CURRENT_TIMESTAMP WHERE source_id=?").bind(j.source_id).run();continue}const claim=await db.prepare("UPDATE cv_notification_delivery SET state='sending',attempts=attempts+1,updated_at=CURRENT_TIMESTAMP WHERE source_id=? AND state IN ('pending','waiting-contact','failed')").bind(j.source_id).run();if(!claim.meta.changes)continue;let kind='';for(const [table,param]of [['cv_tasks','task'],['cv_team_requests','request'],['cv_connect_threads','view=connect&thread'],['cv_connect_meetings','view=connect&meeting']]){if(await db.prepare('SELECT id FROM '+table+' WHERE id=?').bind(j.target).first()){kind=param;break}}const url='https://espacios.me/communiverse/workspace/'+(kind?'?'+kind+'='+encodeURIComponent(j.target):'');try{const sent=await env.EMAIL.send({from:{email:'welcome@communiverse.espacios.me',name:'Communiverse'},to:contact.email,subject:'An update in your Communiverse workspace',text:'You have a new reply, mention or next step in Communiverse.\n\nOpen your workspace to read it: '+url+'\n\nCommuniverse'});await db.prepare("UPDATE cv_notification_delivery SET state='accepted-by-provider',provider_id=?,updated_at=CURRENT_TIMESTAMP WHERE source_id=?").bind(String(sent?.messageId||'').slice(0,200),j.source_id).run()}catch{await db.prepare("UPDATE cv_notification_delivery SET state='delivery-unknown',updated_at=CURRENT_TIMESTAMP WHERE source_id=?").bind(j.source_id).run()}}}
