import{hash}from'./market-members.js';import{json,body,issue,limited}from'./social-backend.js';
const random=()=>[...crypto.getRandomValues(new Uint8Array(32))].map(x=>x.toString(16).padStart(2,'0')).join('');
const cookie=(name,value,age=600)=>`${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${age}`;
const readCookie=(r,name)=>r.headers.get('Cookie')?.match(new RegExp('(?:^|;\\s*)'+name+'=([a-f0-9]{64})(?:;|$)'))?.[1];
const redirect=(url,cookies=[])=>{const h=new Headers({Location:url,'Cache-Control':'no-store','Referrer-Policy':'no-referrer'});cookies.forEach(c=>h.append('Set-Cookie',c));return new Response(null,{status:303,headers:h})};
export async function pending(request,env){const t=readCookie(request,'__Host-cv-onboard');if(!t)return null;return env.COMMUNIVERSE_DB.prepare('SELECT identity_id,email,first_name FROM cv_google_pending WHERE hash=? AND expires_at>?').bind(await hash(t),Date.now()).first()}
export async function google(request,env){const u=new URL(request.url),path=u.pathname.replace(/\/$/,'');const db=env.COMMUNIVERSE_DB;
try{
if(path==='/communiverse/auth/google'&&request.method==='GET'){
 if(!env.SUPABASE_URL||!env.SUPABASE_PUBLIC_KEY)return redirect('/communiverse/sign-in/?error=google-unavailable');await limited(request,db,'google-start',30);
 const state=random(),verifier=random();await db.batch([db.prepare('INSERT INTO cv_google_flows(hash,verifier,expires_at) VALUES(?,?,?)').bind(await hash(state),verifier,Date.now()+600000),db.prepare('DELETE FROM cv_google_flows WHERE expires_at<?').bind(Date.now())]);
 const url=new URL(env.SUPABASE_URL+'/auth/v1/authorize'),bytes=new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier))),challenge=btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
 url.search=new URLSearchParams({provider:'google',redirect_to:'https://espacios.me/communiverse/auth/callback/?state='+state,code_challenge:challenge,code_challenge_method:'s256',scopes:'openid email profile'});
 return redirect(url.href,[cookie('__Host-cv-oauth',state)]);
}
if(path==='/communiverse/auth/callback'&&request.method==='GET'){
 const state=readCookie(request,'__Host-cv-oauth'),provided=u.searchParams.get('state');if(!state||provided!==state)return redirect('/communiverse/sign-in/?error=google-state',[cookie('__Host-cv-oauth','',0)]);
 const flow=await db.prepare('DELETE FROM cv_google_flows WHERE hash=? AND expires_at>? RETURNING verifier').bind(await hash(state),Date.now()).first(),code=u.searchParams.get('code');if(!flow||!code||code.length>4096||u.searchParams.has('error'))return redirect('/communiverse/sign-in/?error=google-expired',[cookie('__Host-cv-oauth','',0)]);
 const exchange=await fetch(env.SUPABASE_URL+'/auth/v1/token?grant_type=pkce',{method:'POST',headers:{apikey:env.SUPABASE_PUBLIC_KEY,'Content-Type':'application/json'},body:JSON.stringify({auth_code:code,code_verifier:flow.verifier}),signal:AbortSignal.timeout(15000)});if(!exchange.ok)throw Error('exchange');const result=await exchange.json();
 const verify=await fetch(env.SUPABASE_URL+'/auth/v1/user',{headers:{apikey:env.SUPABASE_PUBLIC_KEY,Authorization:'Bearer '+result.access_token},signal:AbortSignal.timeout(15000)});if(!verify.ok)throw Error('identity');const user=await verify.json();
 if(!user.id||!user.email_confirmed_at||!user.identities?.some(i=>i.provider==='google')||!/^\S+@\S+\.\S+$/.test(user.email||''))throw Error('unverified');const email=user.email.toLowerCase(),identity='google:'+user.id;
 const existing=await db.prepare("SELECT m.id FROM cv_members m LEFT JOIN cv_google_identities i ON i.member_id=m.id WHERE (i.identity_id=? OR m.email=?) AND m.status='active' LIMIT 1").bind(identity,email).first();
 if(existing){await db.prepare('INSERT OR IGNORE INTO cv_google_identities(identity_id,member_id) VALUES(?,?)').bind(identity,existing.id).run();await db.prepare('UPDATE cv_members SET email_verified_at=COALESCE(email_verified_at,?) WHERE id=?').bind(new Date().toISOString(),existing.id).run();return redirect('/communiverse/profile/',[cookie('__Host-cv-oauth','',0),await issue(existing.id,env)]);}
 const t=random(),first=String(user.user_metadata?.given_name||user.user_metadata?.full_name||'').trim().split(/\s+/)[0].slice(0,60);await db.batch([db.prepare('INSERT INTO cv_google_pending(hash,identity_id,email,first_name,expires_at) VALUES(?,?,?,?,?)').bind(await hash(t),identity,email,first,Date.now()+3600000),db.prepare('DELETE FROM cv_google_pending WHERE expires_at<?').bind(Date.now())]);return redirect('/communiverse/onboarding/',[cookie('__Host-cv-oauth','',0),cookie('__Host-cv-onboard',t,3600)]);
}
if(path==='/communiverse/api/onboarding'&&request.method==='GET'){const p=await pending(request,env);return p?json({firstName:p.first_name,email:p.email}):json({error:'Sign in with Google to continue.'},401)}
if(path==='/communiverse/api/onboarding'&&request.method==='POST'){
 const b=await body(request,3500);let p=await pending(request,env);if(!p)return json({error:'Your setup link expired. Sign in with Google again.'},401);await limited(request,db,'google-onboard',10);
 const str=(v,n)=>typeof v==='string'?v.trim().slice(0,n+1):'',name=str(b.firstName,60),city=str(b.city,100),craft=str(b.craft,80),phone=str(b.phone,30),ig=str(b.instagram,31).replace(/^@/,''),tk=str(b.tiktok,31).replace(/^@/,'');if(!name||name.length>60||!city||city.length>100||!craft||craft.length>80||(!/^\+?[\d\s().-]{7,30}$/.test(phone)||phone.replace(/\D/g,'').length<7||phone.replace(/\D/g,'').length>15)||![ig,tk].every(x=>!x||/^[A-Za-z0-9._]{1,30}$/.test(x))||![name,city,craft].every(x=>!/[\u0000-\u001f]/.test(x))||!['artist','collector','city-representative','cool-kids'].includes(b.intent)||b.consent!==true)return json({error:'Check your details and profile consent.'},400);
 p=await db.prepare('DELETE FROM cv_google_pending WHERE hash=? AND expires_at>? RETURNING identity_id,email,first_name').bind(await hash(readCookie(request,'__Host-cv-onboard')),Date.now()).first();if(!p)return json({error:'Your setup was already completed. Sign in to continue.'},409);
 let member=await db.prepare("SELECT id,status FROM cv_members WHERE email=?").bind(p.email).first();if(member?.status==='hidden')return json({error:'This profile is unavailable.'},403);
 const id=member?.id||crypto.randomUUID(),now=new Date().toISOString();if(!member){await db.prepare('INSERT OR IGNORE INTO cv_members(id,request_key,email,phone,first_name,city,craft,kind,instagram,tiktok,email_verified_at,confirmation_hash,confirmation_expires_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,'google:'+p.identity_id,p.email,phone,name,city,craft,b.intent==='artist'?'artist':'member',ig,tk,now,await hash(random()),now).run();member=await db.prepare("SELECT id FROM cv_members WHERE email=? AND status='active'").bind(p.email).first();}
 if(!member)return json({error:'Please try again.'},409);await db.batch([db.prepare('INSERT OR IGNORE INTO cv_google_identities(identity_id,member_id) VALUES(?,?)').bind(p.identity_id,member.id),db.prepare('INSERT OR IGNORE INTO cv_member_preferences(member_id,intent) VALUES(?,?)').bind(member.id,b.intent),db.prepare('DELETE FROM cv_google_pending WHERE hash=?').bind(await hash(readCookie(request,'__Host-cv-onboard')))]);
 let emailStatus='pending';try{const mail=await env.EMAIL.send({from:{email:'welcome@communiverse.espacios.me',name:'Communiverse'},to:p.email,subject:'Welcome to Communiverse, '+name,text:'Welcome to Communiverse, '+name+'.\n\nYour circle is ready. Discover art, save favourites and meet your community.\n\nYour profile: https://espacios.me/communiverse/profile/\nYour circle: https://espacios.me/communiverse/plug/?person=member-'+member.id});await db.prepare("UPDATE cv_members SET welcome_status='sent' WHERE id=?").bind(member.id).run();emailStatus='sent'}catch{await db.prepare("UPDATE cv_members SET welcome_status='failed' WHERE id=? AND welcome_status<>'sent'").bind(member.id).run()}
 const h=new Headers({'Cache-Control':'no-store','Content-Type':'application/json'});h.append('Set-Cookie',await issue(member.id,env));h.append('Set-Cookie',cookie('__Host-cv-onboard','',0));return new Response(JSON.stringify({ok:true,profileUrl:'/communiverse/profile/',circleUrl:'/communiverse/plug/?person=member-'+member.id,emailStatus}),{status:201,headers:h});
}
return null;
}catch(e){if(path.startsWith('/communiverse/api/'))return json({error:e.status?e.message:'Please try again shortly.'},e.status||503);return redirect('/communiverse/sign-in/?error=google-unavailable',[cookie('__Host-cv-oauth','',0)])}
}
