import IMAGES from './social-images.txt';
import COUNTRY_DATA from './social-countries.txt';import RATE_DATA from './social-rates.txt';
import{ARTISTS,SESSION_PRICES,ITEMS,CITIES}from'./market-data.js';import{body,json,limited,session}from'./social-backend.js';
import {photoURL,publicIdentityMap} from './social-identity.js';
const imageMap=JSON.parse(IMAGES);
export const COUNTRIES=JSON.parse(COUNTRY_DATA).countries,RATES=JSON.parse(RATE_DATA),CURRENCIES=Object.keys(RATES.rates).sort();
const fold=v=>String(v||'').toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const fail=(m,s=400)=>{throw Object.assign(Error(m),{status:s})},clean=(v,n)=>typeof v==='string'?v.trim().slice(0,n+1):'';
export function locationFor(request){const code=clean(request.cf?.country||request.headers.get('CF-IPCountry'),2).toUpperCase(),country=COUNTRIES.find(c=>c.id===code);return{country:country?.id||'',city:clean(request.cf?.city,100),currency:country?.currency||'USD',dial:country?.dial||'',approximate:!!country};}
const regionCode={uae:'AE',saudi:'SA',pakistan:'PK',philippines:'PH',malaysia:'MY',china:'CN',colombia:'CO',peru:'PE',india:'IN',uzbekistan:'UZ'};
const countryFor=a=>a.country||regionCode[a.region]||({Colombia:'CO',Peru:'PE',Morocco:'MA',Spain:'ES',Italy:'IT',Nigeria:'NG',Japan:'JP',UAE:'AE',India:'IN',Mexico:'MX',Senegal:'SN',Finland:'FI'}[a.location?.split(',').pop()?.trim()])||'';
const memberArtistWhere="m.status='active' AND (m.kind='artist' OR (m.email_verified_at IS NOT NULL AND p.intent='artist') OR EXISTS(SELECT 1 FROM cv_artist_accounts a WHERE a.member_id=m.id))";
async function activeMemberArtist(db,id){if(!/^member-[a-f0-9-]{36}$/.test(id||''))return null;return db.prepare('SELECT m.id,m.first_name,m.city,m.craft,p.bio,p.region FROM cv_members m LEFT JOIN cv_member_preferences p ON p.member_id=m.id WHERE m.id=? AND '+memberArtistWhere).bind(id.slice(7)).first();}
async function offeredArtists(db){
 const listed=(await db.prepare("SELECT data FROM cv_catalog WHERE kind='artist'").all()).results.map(x=>JSON.parse(x.data));
 const members=(await db.prepare('SELECT m.id,m.first_name,m.city,m.craft,p.bio,p.region FROM cv_members m LEFT JOIN cv_member_preferences p ON p.member_id=m.id WHERE '+memberArtistWhere+' LIMIT 1000').all()).results;
 const profiles=(await db.prepare('SELECT artist_id,country,city,craft,bio,can_host,host_setup,tags FROM cv_artist_business').all()).results,profileMap=new Map(profiles.map(p=>[p.artist_id,p])),photos=await publicIdentityMap(db);
 const all=[...ARTISTS.map((a,i)=>({id:a.slug,title:a.name,city:a.location?.split(',')[0]||'',country:countryFor(a),craft:ITEMS.find(i=>i.artist===a.slug)?.category||a.role,image:a.image,description:a.summary,tags:a.focus,guideUSD:SESSION_PRICES[i],locationType:'studio'})),...listed.filter(a=>!a.concept).map(a=>({...a,country:countryFor(a),craft:a.primaryCraft||(a.tags||[]).filter(t=>!['gallery',a.region,'selected work'].includes(t)).slice(0,2).join(' · '),guideUSD:null,locationType:'gallery'})),...members.map(m=>({id:'member-'+m.id,title:m.first_name,city:m.city,country:regionCode[m.region]||'',region:m.region||'',craft:m.craft,description:m.bio||'',tags:[m.craft.toLowerCase(),m.region||'community'],image:photoURL('member-'+m.id),guideUSD:null,locationType:'member'}))];
 return [...new Map(all.map(a=>[a.id,a])).values()].map(a=>{const p=profileMap.get(a.id),tags=[...new Set([...(a.tags||[]),...(p?JSON.parse(p.tags||'[]'):[]),p?.craft?.toLowerCase()].filter(Boolean))];return {...a,...(p?{country:p.country||a.country,city:p.city||a.city,craft:p.craft||a.craft,description:p.bio||a.description,canHost:!!p.can_host}:{}),tags,image:photos[a.id]||imageMap[a.image]?.variants?.[1]?.url||a.image};});
}
export async function bookingAPI(request,env){const u=new URL(request.url),path=u.pathname.replace(/\/$/,''),db=env.COMMUNIVERSE_DB;try{
 if(request.method==='GET'&&path==='/communiverse/api/location')return json({...locationFor(request),countries:COUNTRIES,currencies:CURRENCIES,cities:CITIES.map(c=>({...c,country:({UAE:'AE','Saudi Arabia':'SA',Pakistan:'PK',Philippines:'PH',Malaysia:'MY',China:'CN',Colombia:'CO',Peru:'PE',India:'IN',Uzbekistan:'UZ'})[c.country]}))});
 if(['GET','HEAD'].includes(request.method)&&path==='/communiverse/api/prices'){const currency=u.searchParams.get('currency')||'USD';if(!CURRENCIES.includes(currency))fail('Choose a supported currency.');const people=Math.max(1,Math.min(40,Math.floor(Number(u.searchParams.get('people')))||4)),values=[...new Set([...ITEMS.map(i=>i.price),...SESSION_PRICES,...SESSION_PRICES.map(p=>p*people)])],rate=RATES.rates[currency];return request.method==='HEAD'?new Response(null,{headers:{'Cache-Control':'public,max-age=3600','Content-Type':'application/json'}}):json({currency,quotes:Object.fromEntries(values.map(v=>[v,v*rate])),updated:RATES.updated,rate,estimated:true},200,{'Cache-Control':'public,max-age=3600'});}
 if(request.method==='GET'&&path==='/communiverse/api/booking/profile'){const p=await session(request,env);if(!p)return json({profile:null});const x=await db.prepare('SELECT first_name,email,phone FROM cv_members WHERE id=?').bind(p.id).first();return json({profile:x});}
 if(request.method==='GET'&&path==='/communiverse/api/booking/artists'){
 const country=clean(u.searchParams.get('country'),2),city=fold(clean(u.searchParams.get('city'),100)),craft=fold(clean(u.searchParams.get('craft'),80));if(country&&!COUNTRIES.some(c=>c.id===country))fail('Choose a country.');const all=await offeredArtists(db);
 const slots=(await db.prepare("SELECT s.id,s.artist_id,s.country,s.city,s.start_at,s.end_at,s.timezone,s.capacity,s.price_usd,d.price,d.currency,d.usd_rate,d.rate_date FROM cv_workshop_slots s LEFT JOIN cv_artist_slot_details d ON d.slot_id=s.id LEFT JOIN cv_artist_business b ON b.artist_id=s.artist_id WHERE s.status='active' AND s.confirmed_by<>'' AND s.start_at>? AND (b.artist_id IS NULL OR b.can_host=1) ORDER BY s.start_at LIMIT 1000").bind(new Date().toISOString()).all()).results;
 const artists=all.filter(a=>(!country||a.country===country||slots.some(s=>s.artist_id===a.id&&s.country===country))&&(!city||fold([a.city,a.title,...a.tags].join(' ')).includes(city)||slots.some(s=>s.artist_id===a.id&&fold(s.city).includes(city)))&&(!craft||fold([a.craft,...a.tags].join(' ')).includes(craft))).map(a=>({...a,slots:slots.filter(s=>s.artist_id===a.id&&(!country||s.country===country)&&(!city||fold(s.city).includes(city)))}));return json({artists,total:artists.length,currency:COUNTRIES.find(c=>c.id===country)?.currency||'USD'});
 }
 if(request.method==='POST'&&path==='/communiverse/api/booking/request'){
 const b=await body(request,6000);await limited(request,db,'booking',8);if(b.website)fail('Unable to send this request.');const name=clean(b.name,60),email=clean(b.email,254).toLowerCase(),phone=clean(b.phone,30),country=clean(b.country,2),city=clean(b.city,100),craft=clean(b.craft,80),artist=clean(b.artist,100),date=clean(b.date,10),people=Number(b.people),currency=clean(b.currency,3),note=clean(b.note,1000);if(!name||name.length>60||!/^\S+@\S+\.\S+$/.test(email)||email.length>254||!/^\+[\d\s().-]{7,30}$/.test(phone)||phone.replace(/\D/g,'').length>15||!COUNTRIES.some(c=>c.id===country)||!city||city.length>100||!craft||craft.length>80||!Number.isInteger(people)||people<1||people>40||note.length>1000||!CURRENCIES.includes(currency)||!/^[a-f0-9-]{36}$/.test(b.requestId||'')||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date||date<new Date(Date.now()-86400000).toISOString().slice(0,10)||date>new Date(Date.now()+3*365*86400000).toISOString().slice(0,10))fail('Check your location, date and contact details.');const a=ARTISTS.find(a=>a.slug===artist)||await db.prepare("SELECT id FROM cv_catalog WHERE id=? AND kind='artist'").bind(artist).first()||await activeMemberArtist(db,artist);if(artist&&artist!=='find-a-maker'&&!a)fail('Choose a listed artist.');const p=await session(request,env),id='group-'+b.requestId;
 const old=await db.prepare('SELECT id FROM cv_group_requests WHERE request_key=?').bind(b.requestId).first();if(old)return json({ok:true,reference:old.id.slice(-12),message:'Your request is already saved.'});let slot=null;if(b.slot){slot=await db.prepare("SELECT s.* FROM cv_workshop_slots s LEFT JOIN cv_artist_business b ON b.artist_id=s.artist_id WHERE s.id=? AND s.artist_id=? AND s.status='active' AND s.confirmed_by<>'' AND s.start_at>? AND s.capacity>=? AND (b.artist_id IS NULL OR b.can_host=1)").bind(b.slot,artist,new Date().toISOString(),people).first();if(!slot||slot.country!==country||new Intl.DateTimeFormat('en-CA',{timeZone:slot.timezone||'UTC',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(slot.start_at))!==date)fail('That date is no longer offered. Choose another date.');}
 await db.prepare('INSERT INTO cv_group_requests(id,request_key,member_id,name,email,phone,country,city,craft,artist_id,date,people,currency,slot_id,guide_usd,note) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').bind(id,b.requestId,p?.id||null,name,email,phone,country,city,craft,artist==='find-a-maker'?'':artist,date,people,currency,slot?.id||'',slot?.price_usd??(a?.slug?SESSION_PRICES[ARTISTS.indexOf(a)]:null),note).run();return json({ok:true,reference:id.slice(-12),message:'Your session request is saved. We’ll confirm the host, date and total before anything is booked.'},201);
 }
 return json({error:'Not found'},404);
}catch(e){if(!e.status)console.error('Communiverse booking unavailable',e.code||'service');return json({error:e.status?e.message:'Unable to load sessions right now. Please try again.'},e.status||503)}}
export function bookingForm(artist=''){return `<div class="cv-group-intro"><p class="cv-kicker">Friends, teams and curious people</p><h2>A session for your group.</h2><p>Start with a place. Find a practice, choose your people and request a date.</p><p id="cv-group-price" class="cv-session-price">Choose a location to explore artists and session prices.</p><p class="cv-muted">Published dates come from artist-confirmed availability. Other dates are requests, with the host and total agreed before booking.</p></div><form id="cv-group-form" data-initial-artist="${String(artist).replace(/[^a-zA-Z0-9-]/g,'')}">
<div class="cv-group-step"><p class="cv-kicker">1 · A place to make</p><div class="cv-form-row"><label>Country<select name="country" id="cv-group-country" required><option value="">Choose a country</option></select></label><label>City<input name="city" id="cv-group-city" maxlength="100" autocomplete="address-level2" required placeholder="Where would you like to meet?"></label></div><p id="cv-group-location-note" class="cv-muted"></p><button class="cv-text-link" type="button" id="cv-group-location">Use my location</button></div>
<div class="cv-group-step"><p class="cv-kicker">2 · A practice & a person</p><label>Craft or interest<select name="craft" id="cv-group-craft" required><option value="">Choose a craft</option>${['Ceramics','Textiles','Wood','Glass','Metal','Baskets','Paper','Painting','Sculpture','Photography','Digital art','Mixed media'].map(v=>`<option>${v}</option>`).join('')}</select></label><fieldset><legend>Choose an artist</legend><div id="cv-group-artists" class="cv-group-artists"><p class="cv-muted">Choose a location to find artists connected with it.</p></div></fieldset><button type="button" class="cv-text-link" id="cv-group-artists-more" hidden>More artists</button></div>
<div class="cv-group-step"><p class="cv-kicker">3 · A date & a group</p><div id="cv-group-slots"></div><div class="cv-form-row"><label>Preferred date<input name="date" type="date" required></label><label>People<input name="people" type="number" min="1" max="40" value="4" required></label></div><label>Currency<select name="currency" id="cv-group-currency"></select></label><p id="cv-group-date-note" class="cv-muted">A date request is confirmed with the artist before it becomes a booking.</p></div>
<div class="cv-group-step"><p class="cv-kicker">4 · Your details</p><div class="cv-form-row"><label>Your name<input name="name" maxlength="60" autocomplete="given-name" required></label><label>Email<input name="email" type="email" maxlength="254" autocomplete="email" required></label></div><div class="cv-phone-fields"><label>Phone country<select name="phoneCountry" class="cv-phone-country"></select></label><label>Phone number<input name="phone" type="tel" autocomplete="tel-national" maxlength="30" required placeholder="Your number"></label></div><label>Anything to plan around? <span>(optional)</span><textarea name="note" rows="3" maxlength="1000" placeholder="Your group’s interests, accessibility needs or an occasion"></textarea></label></div><label class="cv-honey" aria-hidden="true">Website<input name="website" tabindex="-1" autocomplete="off"></label><button class="cv-button" type="submit">Request this session</button><p class="cv-form-status" role="status"></p></form>`;}
