import COLLECTED from './social-collected.txt';
import {ARTISTS,ITEMS,CITIES} from './market-data.js';
export const RELEASE='20261008-social-2',PREFIX='/communiverse/_public/'+RELEASE;
export const REGIONS=[{id:'uae',name:'UAE',area:'Middle East'},{id:'saudi',name:'Saudi Arabia',area:'Middle East'},{id:'pakistan',name:'Pakistan',area:'South Asia'},{id:'philippines',name:'Philippines',area:'Southeast Asia'},{id:'malaysia',name:'Malaysia',area:'Southeast Asia'},{id:'china',name:'China',area:'East Asia'},{id:'colombia',name:'Colombia',area:'Latin America'},{id:'peru',name:'Peru',area:'Latin America'},{id:'india',name:'India',area:'South Asia'},{id:'uzbekistan',name:'Uzbekistan',area:'Central Asia'}];
const tagSets={Ceramics:['ceramics','stoneware','pottery','glaze','handmade','home','vessel','texture','earth tones'],Textiles:['textiles','weaving','cotton','linen','indigo','soft furnishings','pattern','handmade','slow craft'],Wood:['wood','walnut','carving','sculpture','grain','natural materials','hand tools','home'],Glass:['glass','glassblowing','translucent','sea green','vessel','light','handmade'],Baskets:['baskets','weaving','palm fibre','natural materials','coiling','home','handmade'],Sculpture:['sculpture','wire','metal','minimalism','line','form','shadow','hand shaped'],'Metal & jewellery':['metal','jewellery','brass','silver tone','hammered','polished','small objects','craft'],'Paper & prints':['paper','ink','lettering','prints','brushwork','minimalism','wall art','handmade paper']};
export const CLIPS={balo:{slug:'cv-abdallah-mahmoudd',name:'Balo',file:'balo',region:'uae',tags:['video','storytelling','everyday culture','arabic','ambassador']},ammar:{slug:'cv-turbooz',name:'Ammar',file:'ammar',region:'uae',tags:['video','discovery','uae','lifestyle','ambassador']},luna:{slug:'cv-luna',name:'Luna',file:'luna',region:'peru',tags:['video','travel','documentary','culture','spanish','ambassador']}};
const studioArtists=ARTISTS.map(a=>({id:a.slug,kind:'artist',title:a.name,description:a.summary,image:a.image,source:a.profileUrl,region:'',city:a.location,organizer:'Communiverse studio collection',concept:true,tags:a.focus.map(t=>t.toLowerCase())}));
const studioWorks=ITEMS.map(i=>({...i,kind:'work',artistName:ARTISTS.find(a=>a.slug===i.artist).name,region:'',concept:true,source:'/communiverse/artists/'+i.artist.slice(7)+'/',organizer:'Communiverse studio collection',tags:[...tagSets[i.category],...i.material.toLowerCase().split(/[·\s]+/).filter(t=>t.length>2),i.artist]}));
const craftVideos=ARTISTS.map((a,i)=>({id:'film-'+a.slug,kind:'video',artist:a.slug,artistName:a.name,title:a.role+' · in the making',description:'A closer look at materials and craft techniques.',image:'/communiverse/_public/20261008-marketplace-1/process-'+['ceramics','textiles','wood','wire','paper','metal','printing','metal','baskets','glass'][i]+'.jpg',video:a.films[0].src,source:a.profileUrl,organizer:'Craft reference film',concept:true,region:'',tags:['video','process','craft',a.role.toLowerCase(),...(tagSets[ITEMS.find(p=>p.artist===a.slug)?.category]||[])]}));
const ambassadorRecords=Object.values(CLIPS).flatMap(c=>[{id:c.slug,kind:'ambassador',title:c.name,description:'Communiverse ambassador · local stories and discoveries.',region:c.region,city:'',source:'/communiverse/plug/?filter=ambassadors&person='+c.slug,image:'/communiverse/_public/media/ambassadors/20261008/'+c.file+'.jpg',tags:c.tags},{id:'video-'+c.file,kind:'video',artist:c.slug,artistName:c.name,title:c.name+' · through their lens',description:'A video shared for '+c.name+'’s Communiverse profile.',region:c.region,city:'',video:'/communiverse/_public/media/ambassadors/20261008/'+c.file+'.mp4',image:'/communiverse/_public/media/ambassadors/20261008/'+c.file+'.jpg',source:'/communiverse/plug/?person='+c.slug,organizer:'Communiverse ambassador',tags:c.tags}]);
const countries={'UAE':'uae','Saudi Arabia':'saudi','Pakistan':'pakistan','Philippines':'philippines','Malaysia':'malaysia','China':'china','Colombia':'colombia','Peru':'peru','India':'india','Uzbekistan':'uzbekistan'};
const venues=CITIES.flatMap(c=>c.venues.map((v,i)=>({id:'venue-'+c.id+'-'+i,kind:'venue',title:v.name,type:v.type==='Museum'?'Museum':v.type==='Workshops'?'Workshop':'Gallery',region:countries[c.country],city:c.name,organizer:v.name,description:v.note,source:v.url,image:'',dateLabel:'Year-round · see current programme',checkedAt:'2026-10-08',tags:[v.craft.toLowerCase(),v.type.toLowerCase(),countries[c.country],'culture']})));
const collected=JSON.parse(COLLECTED).map(i=>({...i,tags:[...new Set([...i.tags,i.city?.toLowerCase(),i.organizer?.toLowerCase(),i.artistName?.toLowerCase(),REGIONS.find(r=>r.id===i.region)?.area.toLowerCase()].filter(Boolean))]}));
export const regionForCity=v=>{const city=String(v||'').toLowerCase().trim();const c=CITIES.find(c=>c.name.toLowerCase()===city);return c?countries[c.country]:(REGIONS.find(r=>r.name.toLowerCase()===city)?.id||'')};
export const CATALOG=[...collected,...studioArtists,...studioWorks,...craftVideos,...ambassadorRecords,...venues];

export const AMBASSADOR_REGIONS={"cv-luna":["colombia","peru"],"cv-abdallah-mahmoudd":["uae","saudi"],"cv-turbooz":["pakistan","philippines","malaysia","china","india","uzbekistan"]};
export function ambassadorFor(a){const r=a.region||regionForCity(a.city);return Object.keys(AMBASSADOR_REGIONS).find(id=>AMBASSADOR_REGIONS[id].includes(r))||Object.keys(AMBASSADOR_REGIONS)[[...a.id].reduce((n,c)=>n+c.charCodeAt(0),0)%3]}
export const EVENT_CITIES=CITIES.map(c=>({name:c.name,region:countries[c.country],lat:c.lat,lon:c.lon}));
export function eventState(e,at=new Date()){const today=at.toISOString().slice(0,10),end=e.end||e.expiresOn||e.start;if(e.kind==='venue')return 'places';if(end&&end<today)return 'past';if(!e.start)return 'upcoming';return e.start>today?'upcoming':'now'}
