import previous from './market-entry.js';
import SOCIAL6_SCRIPT from './social-6.txt';import SOCIAL6_FOCUS from './social-6-focus.txt';
import {cleanDisplay} from './social-presentation.js';
import SOCIAL5B_SCRIPT from './social-5b.txt';import SOCIAL5B_FOCUS from './social-5b-focus.txt';
import OLD_SCRIPT from './social-1b.txt';import OLD_FOCUS from './social-1b-focus.txt';
import SOCIAL5_SCRIPT from './social-5.txt';import SOCIAL5_FOCUS from './social-5-focus.txt';
import SOCIAL4_SCRIPT from './social-4.txt';import SOCIAL4_FOCUS from './social-4-focus.txt';
import IMAGES from './social-images.txt';import {google,pending} from './social-auth.js';
import SOCIAL3_SCRIPT from './social-3.txt';import SOCIAL3_FOCUS from './social-3-focus.txt';
import SOCIAL2_SCRIPT from './social-2.txt';import SOCIAL2_FOCUS from './social-2-focus.txt';
import STYLE from './social.css';import SCRIPT from './social.txt';import FOCUS from './social-focus.txt';
import {CATALOG,CLIPS,PREFIX,RELEASE,REGIONS,EVENT_CITIES,AMBASSADOR_REGIONS,ambassadorFor} from './social-data.js';
import {header,feed,events,artists,artistPage,signin,profile,communities,join,hostEvent,onboarding,galleryPage,eventPage,referencePage} from './social-views.js';
import {h,serialize} from './market-views.js';
import {api,session,issue,upload,body} from './social-backend.js';
import {hash} from './market-members.js';
const imageMap=JSON.parse(IMAGES);
const read=new Set(['GET','HEAD']);
const newAPIs=new Set(['galleries','event','auth/start','auth/finish','auth/logout','me','feed','hearts','follows','item','artists','events','community','comments','content/remove','report']);
async function media(request,env,path){const key=path.slice('/communiverse/_public/media/'.length),community=path.startsWith('/communiverse/_public/community/');const name=community?path.slice('/communiverse/_public/'.length):key;if(!/^images\/20261008\/[a-f0-9]{24}-(320|720|1280)\.webp$/.test(name)&&!/^ambassadors\/20261008\/(balo|ammar|luna)\.(mp4|jpg)$/.test(name)&&!/^community\/[a-f0-9-]{36}\/[a-f0-9-]{36}\.(jpg|png|webp)$/.test(name))return new Response('Not found',{status:404});if(community){const visible=await env.COMMUNIVERSE_DB.prepare("SELECT p.id FROM cv_posts p JOIN cv_members m ON m.id=p.member_id WHERE p.image=? AND p.status='active' AND m.status='active' LIMIT 1").bind(path).first();if(!visible){const owner=await session(request,env);if(!owner||!name.startsWith('community/'+owner.id+'/'))return new Response('Not found',{status:404});}}let object;if(request.method==='HEAD'){object=await env.COMMUNIVERSE_MEDIA.head(name);if(!object)return new Response('Not found',{status:404});}else object=await env.COMMUNIVERSE_MEDIA.get(name,{range:request.headers});if(!object)return new Response('Not found',{status:404});const headers=new Headers({'Cache-Control':community?'no-store':'public,max-age=31536000,immutable','X-Content-Type-Options':'nosniff','Accept-Ranges':'bytes','Content-Security-Policy':"default-src 'none'; sandbox"});object.writeHttpMetadata(headers);headers.set('ETag',object.httpEtag);headers.set('Content-Type',name.endsWith('.mp4')?'video/mp4':name.endsWith('.jpg')?'image/jpeg':name.endsWith('.png')?'image/png':'image/webp');const ranged=request.headers.has('Range')&&object.range;if(ranged){const r=object.range;headers.set('Content-Range',`bytes ${r.offset}-${r.offset+r.length-1}/${object.size}`);headers.set('Content-Length',r.length);}else headers.set('Content-Length',object.size);return new Response(request.method==='HEAD'?null:object.body,{status:ranged?206:200,headers});}
export default{async fetch(request,env,ctx){const u=new URL(request.url),path=u.pathname.replace(/\/$/,'');if(u.hostname==='mail.espacios.me'&&path==='/communiverse/auth/callback'&&request.method==='GET'){const target=new URL('https://espacios.me/communiverse/auth/callback/');for(const key of ['state','code','error'])if(u.searchParams.has(key))target.searchParams.set(key,u.searchParams.get(key));return new Response(null,{status:303,headers:{Location:target.href,'Cache-Control':'no-store','Referrer-Policy':'no-referrer','Content-Security-Policy':"default-src 'none'"}});}
 if(!['espacios.me','www.espacios.me'].includes(u.hostname))return previous.fetch(request,env,ctx);
 if(u.hostname==='www.espacios.me'&&path.startsWith('/communiverse/auth/'))return Response.redirect('https://espacios.me'+u.pathname+u.search,303);
 if(path.startsWith('/communiverse/auth/')||path==='/communiverse/api/onboarding'){const response=await google(request,env);if(response)return response;}
 if(path.startsWith('/communiverse/api/')){const endpoint=path.slice('/communiverse/api/'.length);if(newAPIs.has(endpoint))return api(request,env,ctx);if(endpoint==='upload'&&request.method==='POST')return upload(request,env);if(['members','members/confirm'].includes(endpoint)&&request.method==='POST'){let confirmationMember=null,signupRole=null;if(endpoint==='members'){try{const b=await body(request.clone());signupRole=['artist','collector','city-representative','cool-kids'].includes(b.intent)?b.intent:null}catch{}}if(endpoint==='members/confirm'){try{const b=await body(request.clone(),300);if(b.action!=='remove'&&/^[a-f0-9]{64}$/.test(b.token||''))confirmationMember=await env.COMMUNIVERSE_DB.prepare("SELECT id FROM cv_members WHERE confirmation_hash=? AND confirmation_expires_at>? AND status='active'").bind(await hash(b.token),new Date().toISOString()).first()}catch{}}const r=await previous.fetch(request,env,ctx),copy=await r.clone().json();if(copy.ok&&confirmationMember){const headers=new Headers(r.headers);headers.set('Set-Cookie',await issue(confirmationMember.id,env));return new Response(r.body,{status:r.status,headers});}if(copy.ok&&copy.profileUrl&&((endpoint==='members'&&r.status===201)||(endpoint==='members/confirm'&&request.method==='POST'&&copy.message!=='This signup has been removed.'))){const id=copy.profileUrl.match(/member-([a-f0-9-]{36})/)?.[1];if(id){const m=await env.COMMUNIVERSE_DB.prepare("SELECT id FROM cv_members WHERE id=? AND status='active'").bind(id).first();if(m){if(endpoint==='members'&&r.status===201&&signupRole)await env.COMMUNIVERSE_DB.prepare('INSERT OR IGNORE INTO cv_member_preferences(member_id,intent) VALUES(?,?)').bind(id,signupRole).run();const headers=new Headers(r.headers);headers.set('Set-Cookie',await issue(id,env));return new Response(r.body,{status:r.status,headers});}}}return r;}}
 if(read.has(request.method)&&/^\/communiverse\/_public\/member-avatar\/[a-f0-9-]{36}\.svg$/.test(path)){const r=await previous.fetch(request,env,ctx);if(r.status!==200||request.method==='HEAD')return r;const headers=new Headers(r.headers);headers.delete('Content-Length');headers.delete('ETag');return new HTMLRewriter().on('text',{text(chunk){const cleaned=cleanDisplay(chunk.text);if(cleaned!==chunk.text)chunk.replace(cleaned.trim()||'C')}}).transform(new Response(r.body,{status:r.status,headers}));}
 if(read.has(request.method)&&(path.startsWith('/communiverse/_public/media/ambassadors/20261008/')||path.startsWith('/communiverse/_public/media/images/20261008/')||path.startsWith('/communiverse/_public/community/')))return media(request,env,path);
 if(path==='/communiverse/_public/20261008-social-1b.js'||path==='/communiverse/_public/20261008-social-1b-focus.js')return new Response(request.method==='HEAD'?null:path.endsWith('-focus.js')?OLD_FOCUS:OLD_SCRIPT,{headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'public,max-age=31536000,immutable'}});
 if(path==='/communiverse/_public/20261008-social-2.js'||path==='/communiverse/_public/20261008-social-2-focus.js')return new Response(request.method==='HEAD'?null:path.endsWith('-focus.js')?SOCIAL2_FOCUS:SOCIAL2_SCRIPT,{headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'public,max-age=31536000,immutable'}});
 if(path==='/communiverse/_public/20261008-social-3.js'||path==='/communiverse/_public/20261008-social-3-focus.js')return new Response(request.method==='HEAD'?null:path.endsWith('-focus.js')?SOCIAL3_FOCUS:SOCIAL3_SCRIPT,{headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'public,max-age=31536000,immutable'}});
 if(path==='/communiverse/_public/20261008-social-4.js'||path==='/communiverse/_public/20261008-social-4-focus.js')return new Response(request.method==='HEAD'?null:path.endsWith('-focus.js')?SOCIAL4_FOCUS:SOCIAL4_SCRIPT,{headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'public,max-age=31536000,immutable'}});
 if(path==='/communiverse/_public/20261008-social-5.js'||path==='/communiverse/_public/20261008-social-5-focus.js')return new Response(request.method==='HEAD'?null:path.endsWith('-focus.js')?SOCIAL5_FOCUS:SOCIAL5_SCRIPT,{headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'public,max-age=31536000,immutable'}});
 if(path==='/communiverse/_public/20261008-social-5b.js'||path==='/communiverse/_public/20261008-social-5b-focus.js')return new Response(request.method==='HEAD'?null:path.endsWith('-focus.js')?SOCIAL5B_FOCUS:SOCIAL5B_SCRIPT,{headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'public,max-age=31536000,immutable'}});
 if(path==='/communiverse/_public/20261008-social-6.js'||path==='/communiverse/_public/20261008-social-6-focus.js')return new Response(request.method==='HEAD'?null:path.endsWith('-focus.js')?SOCIAL6_FOCUS:SOCIAL6_SCRIPT,{headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'public,max-age=31536000,immutable'}});
 if(path===PREFIX+'.js'||path===PREFIX+'-focus.js'){if(!read.has(request.method))return new Response('Method not allowed',{status:405});return new Response(request.method==='HEAD'?null:path.endsWith('-focus.js')?FOCUS:SCRIPT,{headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'public,max-age=31536000,immutable','X-Content-Type-Options':'nosniff'}})}
 if(!read.has(request.method)||!path.startsWith('/communiverse'))return previous.fetch(request,env,ctx);
 const pages={'/communiverse':'feed','/communiverse/onboarding':'onboarding','/communiverse/galleries':'gallery','/communiverse/gallery':'gallery','/communiverse/event':'event','/communiverse/reference':'reference','/communiverse/events':'events','/communiverse/events/host':'host','/communiverse/join':'join','/communiverse/workshops':'events','/communiverse/artists':'artists','/communiverse/artist':'artist','/communiverse/sign-in':'signin','/communiverse/profile':'profile','/communiverse/communities':'communities'},page=pages[path],p=await session(request,env);
 if(path==='/communiverse/workshops')return Response.redirect(u.origin+'/communiverse/events/'+u.search,308);
 if(p&&path==='/communiverse/join')return Response.redirect(u.origin+'/communiverse/profile/',303);
 if(p&&page==='signin'&&!u.hash)return Response.redirect(u.origin+'/communiverse/profile/',303);
 const req=page?new Request(u.origin+'/communiverse/discover/',request):request;const r=await previous.fetch(req,env,ctx);if(r.status!==200||!r.headers.get('Content-Type')?.includes('text/html'))return r;
 const headers=new Headers(r.headers);headers.set('X-Communiverse-Social',RELEASE);headers.set('Cache-Control','no-store');headers.set('Vary','Cookie');['Content-Length','Content-Encoding','ETag','Last-Modified'].forEach(k=>headers.delete(k));if(request.method==='HEAD'){await r.body?.cancel();return new Response(null,{status:r.status,headers});}
 let html=await r.text(),content=null,initial;
 if(page==='feed'){const q=new URLSearchParams(u.search);if(q.has('saved'))q.set('saved','1');if(q.has('following'))q.set('following','1');initial=await(await api(new Request(u.origin+'/communiverse/api/feed?'+q,{headers:request.headers}),env,ctx)).json();content=feed(initial);}
 else if(page==='onboarding'){const identity=await pending(request,env);if(!identity)return Response.redirect(u.origin+'/communiverse/sign-in/',303);content=onboarding(identity);}
 else if(page==='gallery')content=galleryPage();else if(page==='event')content=eventPage();else if(page==='reference')content=referencePage(u.searchParams.get('url'));
 else if(page)content=({events,artists,artist:artistPage,signin,communities,join,host:()=>hostEvent(p),profile:()=>profile(p)})[page]();
 const isPlug=path==='/communiverse/plug';if(isPlug){const re=/(<script\b[^>]*id="cv-focus-data"[^>]*>)([\s\S]*?)(<\/script>)/;const m=html.match(re);if(m){let people=JSON.parse(m[2]);people=people.map(person=>{const c=Object.values(CLIPS).find(c=>c.slug===person.slug);if(c)return {...person,name:c.name,category:'ambassadors',group:'Ambassadors',role:'Ambassador',summary:c.name+' · ambassador for '+AMBASSADOR_REGIONS[c.slug].map(r=>REGIONS.find(x=>x.id===r).name).join(', '),more:'Discover the artists in '+c.name+'’s curated regional circle. Gallery directory links do not imply a representation agreement.',sources:CATALOG.filter(a=>a.kind==='artist'&&ambassadorFor(a)===c.slug).slice(0,6).map(a=>({label:a.title,url:'/communiverse/artist/?id='+a.id})),galleryLabel:c.name+'’s Profile',profileUrl:'/communiverse/artist/?id='+c.slug,films:[{src:'/communiverse/_public/media/ambassadors/20261008/'+c.file+'.mp4',poster:'/communiverse/_public/media/ambassadors/20261008/'+c.file+'.jpg',title:c.name+' · through their lens',note:'Shared profile video'}]};return person;});const bios=(await env.COMMUNIVERSE_DB.prepare("SELECT member_id,bio FROM cv_member_preferences WHERE bio<>''").all()).results;people=people.map(person=>{const bio=bios.find(b=>'member-'+b.member_id===person.slug);return bio?{...person,more:bio.bio}:person});people=people.map(person=>({...person,image:imageMap[person.image]?.variants[1].url||person.image,workPhotos:(person.workPhotos||[]).map(photo=>({...photo,src:imageMap[photo.src]?.variants[1].url||photo.src})),films:(person.films||[]).map(film=>({...film,poster:imageMap[film.poster]?.variants[1].url||film.poster}))}));html=html.replace(re,(_,a,b,c)=>a+serialize(people)+c);}}
 const clip=Object.values(CLIPS).find(c=>path===({balo:'/communiverse/plug/person/abdallah-mahmoudd',ammar:'/communiverse/plug/person/turbooz',luna:'/communiverse/plug/person/luna'})[c.file]);
 let rewrite=new HTMLRewriter().on('html',{element(el){el.setAttribute('data-cv-social',RELEASE)}}).on('.top,#cv-marketplace-nav,.cv-plug>a.home',{element(el){el.remove()}}).on('head',{element(el){el.append(`<style data-cv-social="${RELEASE}">${STYLE}</style><script defer src="${PREFIX}.js"></script>`,{html:true})}}).on('body',{element(el){el.prepend(header(p,(page==='events'||page==='host')?'/communiverse/events/':page==='artists'||page==='artist'?'/communiverse/artists/':page==='communities'?'/communiverse/communities/':isPlug?'/communiverse/plug/':path==='/communiverse/discover'?'/communiverse/discover/':''),{html:true});el.append(`<script id="cv-social-data" type="application/json">${serialize({regions:REGIONS,cities:EVENT_CITIES,images:imageMap})}</script>`,{html:true})}}).on('img,video',{element(el){const attr=el.tagName==='video'?'poster':'src',source=el.getAttribute(attr),asset=imageMap[source];if(asset){el.setAttribute(attr,asset.variants[1].url);if(el.tagName==='img'){el.setAttribute('srcset',asset.variants.filter((v,n,list)=>list.findIndex(x=>x.width===v.width)===n).map(v=>v.url+' '+v.width+'w').join(','));el.setAttribute('sizes','(max-width:600px) 50vw, 25vw');if(el.getAttribute('width')===null&&el.getAttribute('height')===null){el.setAttribute('width',asset.variants[1].width);el.setAttribute('height',asset.variants[1].height);}el.setAttribute('decoding','async')}}}}).on('a,button',{text(chunk){const text=chunk.text.replace(/[↗↓↑]/g,'');if(text!==chunk.text)chunk.replace(text)}}).on('a[href]',{element(el){let href=el.getAttribute('href');if(href?.startsWith('https:')&&!href.startsWith('https://espacios.me/')){el.setAttribute('href','/communiverse/reference/?url='+encodeURIComponent(href));el.removeAttribute('target');el.removeAttribute('rel');}if(href?.startsWith('/communiverse/workshops')){el.setAttribute('href',href.replace('/communiverse/workshops','/communiverse/events'));el.setInnerContent('Events ↗')}if(p&&href==='/communiverse/join/'){el.setAttribute('href','/communiverse/profile/');el.setInnerContent('My profile ↗')}}});
 if(content)rewrite=rewrite.on('main',{element(el){el.setInnerContent(content,{html:true})}}).on('title',{element(el){el.setInnerContent(({onboarding:'Your circle | Communiverse',gallery:'Galleries | Communiverse',event:'Event | Communiverse',reference:'Connections | Communiverse',feed:'Communiverse · Your art world',events:'Events | Communiverse',host:'Host an event | Communiverse',join:'Join | Communiverse',artists:'Artists | Communiverse',artist:'Artist | Communiverse',signin:'Sign in | Communiverse',profile:'My profile | Communiverse',communities:'Communities | Communiverse'})[page])}}).on('script[src]',{element(el){if(el.getAttribute('src')==='/communiverse/_public/20261008-marketplace-1.js')el.remove()}}).on('meta[property="og:url"],link[rel="canonical"]',{element(el){el.setAttribute(el.tagName==='link'?'href':'content',u.origin+u.pathname)}});
 for(const c of Object.values(CLIPS))if(isPlug)rewrite=rewrite.on('.node[data-slug="'+c.slug+'"]',{element(el){el.setAttribute('data-name',c.name)}}).on('.node[data-slug="'+c.slug+'"] .cap b',{element(el){el.setInnerContent(c.name)}});
 if(isPlug)rewrite=rewrite.on('.cv-collection-note',{element(el){el.setInnerContent('The studio collection includes generated stories and imagery; its films are craft references. Member circles and ambassador videos come from the community.')}});
 if(isPlug)rewrite=rewrite.on('script[src],link[as=script]',{element(el){const key=el.tagName==='script'?'src':'href';if(el.getAttribute(key)==='/communiverse/_public/20261008-marketplace-1-focus.js')el.setAttribute(key,PREFIX+'-focus.js')}});
 if(clip)rewrite=rewrite.on('main',{element(el){el.append(`<section class="cv-social cv-ambassador-film"><h2>${h(clip.name)} · through their lens.</h2><video src="/communiverse/_public/media/ambassadors/20261008/${clip.file}.mp4" poster="/communiverse/_public/media/ambassadors/20261008/${clip.file}.jpg" controls playsinline preload="metadata" style="width:180px;max-width:100%;border-radius:22px"></video><a href="/communiverse/artist/?id=${clip.slug}">Follow ${h(clip.name)} ↗</a></section>`,{html:true})}});
 const rendered=rewrite.transform(new Response(html,{status:r.status,headers}));let skippedText=0;
 return new HTMLRewriter().on('img,video',{element(el){const video=el.tagName.toLowerCase()==='video',attr=video?'poster':'src',asset=imageMap[el.getAttribute(attr)];if(!asset)return;el.setAttribute(attr,asset.variants[1].url);if(!video){el.setAttribute('srcset',asset.variants.filter((v,n,list)=>list.findIndex(x=>x.width===v.width)===n).map(v=>v.url+' '+v.width+'w').join(','));el.setAttribute('sizes','(max-width:600px) 50vw,25vw');if(el.getAttribute('width')===null&&el.getAttribute('height')===null){el.setAttribute('width',asset.variants[1].width);el.setAttribute('height',asset.variants[1].height);}el.setAttribute('decoding','async')}}}).on('video',{element(el){el.removeAttribute('controls');for(const key of ['autoplay','muted','loop','playsinline','disablepictureinpicture','disableremoteplayback'])el.setAttribute(key,'');el.setAttribute('controlslist','nofullscreen noremoteplayback');el.setAttribute('loading','lazy')}}).on('.cv-film-mark,.play-icon,.video-play',{element(el){el.remove()}}).on('*',{element(el){for(const key of ['alt','title','aria-label','placeholder']){const value=el.getAttribute(key);if(value!==null){const cleaned=cleanDisplay(value);if(cleaned!==value)el.setAttribute(key,cleaned)}}}}).on('script,style,textarea',{element(el){skippedText++;el.onEndTag(()=>skippedText--)}}).on('body',{text(chunk){if(skippedText)return;const cleaned=cleanDisplay(chunk.text);if(cleaned!==chunk.text)chunk.replace(cleaned.replace(/&(amp|lt|gt|quot|apos|nbsp|#x[0-9a-f]+|#[0-9]+);/gi,(m,k)=>k[0]==='#'?((n)=>Number.isFinite(n)&&n>=0&&n<=1114111?String.fromCodePoint(n):'�')(k[1].toLowerCase()==='x'?parseInt(k.slice(2),16):Number(k.slice(1))):({amp:'&',lt:'<',gt:'>',quot:'"',apos:"'",nbsp:' '}[k.toLowerCase()])))}}).transform(rendered);
}};
