import previous from './market-entry.js';
import STYLE from './social.css';import SCRIPT from './social.txt';import FOCUS from './social-focus.txt';
import {CATALOG,CLIPS,PREFIX,RELEASE,REGIONS} from './social-data.js';
import {header,feed,events,artists,artistPage,signin,profile,communities} from './social-views.js';
import {h,serialize} from './market-views.js';
import {api,session,issue,upload,body} from './social-backend.js';
import {hash} from './market-members.js';
const read=new Set(['GET','HEAD']);
const newAPIs=new Set(['auth/start','auth/finish','auth/logout','me','feed','hearts','follows','item','artists','events','community','comments','content/remove','report']);
async function media(request,env,path){const key=path.slice('/communiverse/_public/media/'.length),community=path.startsWith('/communiverse/_public/community/');const name=community?path.slice('/communiverse/_public/'.length):key;if(!/^ambassadors\/20261008\/(balo|ammar|luna)\.(mp4|jpg)$/.test(name)&&!/^community\/[a-f0-9-]{36}\/[a-f0-9-]{36}\.(jpg|png|webp)$/.test(name))return new Response('Not found',{status:404});if(community){const visible=await env.COMMUNIVERSE_DB.prepare("SELECT p.id FROM cv_posts p JOIN cv_members m ON m.id=p.member_id WHERE p.image=? AND p.status='active' AND m.status='active' LIMIT 1").bind(path).first();if(!visible){const owner=await session(request,env);if(!owner||!name.startsWith('community/'+owner.id+'/'))return new Response('Not found',{status:404});}}let object;if(request.method==='HEAD'){object=await env.COMMUNIVERSE_MEDIA.head(name);if(!object)return new Response('Not found',{status:404});}else object=await env.COMMUNIVERSE_MEDIA.get(name,{range:request.headers});if(!object)return new Response('Not found',{status:404});const headers=new Headers({'Cache-Control':community?'no-store':'public,max-age=31536000,immutable','X-Content-Type-Options':'nosniff','Accept-Ranges':'bytes','Content-Security-Policy':"default-src 'none'; sandbox"});object.writeHttpMetadata(headers);headers.set('ETag',object.httpEtag);headers.set('Content-Type',name.endsWith('.mp4')?'video/mp4':name.endsWith('.jpg')?'image/jpeg':name.endsWith('.png')?'image/png':'image/webp');if(object.range){const r=object.range;headers.set('Content-Range',`bytes ${r.offset}-${r.offset+r.length-1}/${object.size}`);headers.set('Content-Length',r.length);}else headers.set('Content-Length',object.size);return new Response(request.method==='HEAD'?null:object.body,{status:object.range?206:200,headers});}
function artistCircle(a){return {slug:a.id,name:a.title,category:'artists',group:'Artists',role:'Gallery directory',location:a.city,summary:a.description,more:'Listed by '+a.organizer+'. Explore the published source for biography, works and availability.',focus:a.tags.slice(0,4),profileUrl:'/communiverse/artist/?id='+a.id,image:a.image||'',socials:[],sources:[{label:a.organizer,url:a.source}],films:[],workPhotos:[],galleryLabel:a.title.split(' ')[0]+'’s Gallery',sample:false};}
export default{async fetch(request,env,ctx){const u=new URL(request.url),path=u.pathname.replace(/\/$/,'');if(!['espacios.me','www.espacios.me'].includes(u.hostname))return previous.fetch(request,env,ctx);
 if(path.startsWith('/communiverse/api/')){const endpoint=path.slice('/communiverse/api/'.length);if(newAPIs.has(endpoint))return api(request,env,ctx);if(endpoint==='upload'&&request.method==='POST')return upload(request,env);if(['members','members/confirm'].includes(endpoint)&&request.method==='POST'){let confirmationMember=null;if(endpoint==='members/confirm'){try{const b=await body(request.clone(),300);if(b.action!=='remove'&&/^[a-f0-9]{64}$/.test(b.token||''))confirmationMember=await env.COMMUNIVERSE_DB.prepare("SELECT id FROM cv_members WHERE confirmation_hash=? AND confirmation_expires_at>? AND status='active'").bind(await hash(b.token),new Date().toISOString()).first()}catch{}}const r=await previous.fetch(request,env,ctx),copy=await r.clone().json();if(copy.ok&&confirmationMember){const headers=new Headers(r.headers);headers.set('Set-Cookie',await issue(confirmationMember.id,env));return new Response(r.body,{status:r.status,headers});}if(copy.ok&&copy.profileUrl&&((endpoint==='members'&&r.status===201)||(endpoint==='members/confirm'&&request.method==='POST'&&copy.message!=='This signup has been removed.'))){const id=copy.profileUrl.match(/member-([a-f0-9-]{36})/)?.[1];if(id){const m=await env.COMMUNIVERSE_DB.prepare("SELECT id FROM cv_members WHERE id=? AND status='active'").bind(id).first();if(m){const headers=new Headers(r.headers);headers.set('Set-Cookie',await issue(id,env));return new Response(r.body,{status:r.status,headers});}}}return r;}}
 if(read.has(request.method)&&(path.startsWith('/communiverse/_public/media/ambassadors/20261008/')||path.startsWith('/communiverse/_public/community/')))return media(request,env,path);
 if(path===PREFIX+'.js'||path===PREFIX+'-focus.js'){if(!read.has(request.method))return new Response('Method not allowed',{status:405});return new Response(request.method==='HEAD'?null:path.endsWith('-focus.js')?FOCUS:SCRIPT,{headers:{'Content-Type':'application/javascript; charset=utf-8','Cache-Control':'public,max-age=31536000,immutable','X-Content-Type-Options':'nosniff'}})}
 if(!read.has(request.method)||!path.startsWith('/communiverse'))return previous.fetch(request,env,ctx);
 const pages={'/communiverse':'feed','/communiverse/events':'events','/communiverse/workshops':'events','/communiverse/artists':'artists','/communiverse/artist':'artist','/communiverse/sign-in':'signin','/communiverse/profile':'profile','/communiverse/communities':'communities'},page=pages[path],p=await session(request,env);
 if(path==='/communiverse/workshops')return Response.redirect(u.origin+'/communiverse/events/'+u.search,308);
 if(p&&path==='/communiverse/join')return Response.redirect(u.origin+'/communiverse/profile/',303);
 if(p&&page==='signin'&&!u.hash)return Response.redirect(u.origin+'/communiverse/profile/',303);
 const req=page?new Request(u.origin+'/communiverse/discover/',request):request;const r=await previous.fetch(req,env,ctx);if(r.status!==200||!r.headers.get('Content-Type')?.includes('text/html'))return r;
 const headers=new Headers(r.headers);headers.set('X-Communiverse-Social',RELEASE);headers.set('Cache-Control','no-store');headers.set('Vary','Cookie');['Content-Length','Content-Encoding','ETag','Last-Modified'].forEach(k=>headers.delete(k));if(request.method==='HEAD'){await r.body?.cancel();return new Response(null,{status:r.status,headers});}
 let html=await r.text(),content=null,initial;
 if(page==='feed'){const q=new URLSearchParams(u.search);if(q.has('saved'))q.set('saved','1');if(q.has('following'))q.set('following','1');initial=await(await api(new Request(u.origin+'/communiverse/api/feed?'+q,{headers:request.headers}),env,ctx)).json();content=feed(initial);}
 else if(page)content=({events,artists,artist:artistPage,signin,communities,profile:()=>profile(p)})[page]();
 const isPlug=path==='/communiverse/plug';if(isPlug){const re=/(<script\b[^>]*id="cv-focus-data"[^>]*>)([\s\S]*?)(<\/script>)/;const m=html.match(re);if(m){let people=JSON.parse(m[2]);people=people.map(person=>{const c=Object.values(CLIPS).find(c=>c.slug===person.slug);if(c)return {...person,name:c.name,galleryLabel:c.name+'’s Profile',profileUrl:'/communiverse/artist/?id='+c.slug,films:[{src:'/communiverse/_public/media/ambassadors/20261008/'+c.file+'.mp4',poster:'/communiverse/_public/media/ambassadors/20261008/'+c.file+'.jpg',title:c.name+' · through their lens',note:'Shared profile video'}]};return person;});const bios=(await env.COMMUNIVERSE_DB.prepare("SELECT member_id,bio FROM cv_member_preferences WHERE bio<>''").all()).results;people=people.map(person=>{const bio=bios.find(b=>'member-'+b.member_id===person.slug);return bio?{...person,more:bio.bio}:person});const imported=CATALOG.filter(a=>a.kind==='artist'&&!a.concept).map(artistCircle);people.push(...imported);html=html.replace(re,(_,a,b,c)=>a+serialize(people)+c);const nodes=imported.map(a=>`<a class="node" data-slug="${h(a.slug)}" data-name="${h(a.name)}" href="${h(a.profileUrl)}">${a.image?`<img src="${h(a.image)}" alt="" width="240" height="240" loading="lazy" referrerpolicy="no-referrer">`:`<span class="cv-directory-initial">${h(a.name.slice(0,2))}</span>`}<span class="cap"><b>${h(a.name)}</b><small>${h(a.role)}</small></span></a>`).join('');
 initial={importedNodes:nodes};}}
 const clip=Object.values(CLIPS).find(c=>path===({balo:'/communiverse/plug/person/abdallah-mahmoudd',ammar:'/communiverse/plug/person/turbooz',luna:'/communiverse/plug/person/luna'})[c.file]);
 let rewrite=new HTMLRewriter().on('html',{element(el){el.setAttribute('data-cv-social',RELEASE)}}).on('.top,#cv-marketplace-nav,.cv-plug>a.home',{element(el){el.remove()}}).on('head',{element(el){el.append(`<style data-cv-social="${RELEASE}">${STYLE}</style><script defer src="${PREFIX}.js"></script>`,{html:true})}}).on('body',{element(el){el.prepend(header(p,page==='events'?'/communiverse/events/':page==='artists'||page==='artist'?'/communiverse/artists/':page==='communities'?'/communiverse/communities/':isPlug?'/communiverse/plug/':path==='/communiverse/discover'?'/communiverse/discover/':''),{html:true});el.append(`<script id="cv-social-data" type="application/json">${serialize({regions:REGIONS})}</script>`,{html:true})}}).on('a[href]',{element(el){let href=el.getAttribute('href');if(href?.startsWith('/communiverse/workshops')){el.setAttribute('href',href.replace('/communiverse/workshops','/communiverse/events'));el.setInnerContent('Events ↗')}if(p&&href==='/communiverse/join/'){el.setAttribute('href','/communiverse/profile/');el.setInnerContent('My profile ↗')}}});
 if(content)rewrite=rewrite.on('main',{element(el){el.setInnerContent(content,{html:true})}}).on('title',{element(el){el.setInnerContent(({feed:'Communiverse · Your art world',events:'Events | Communiverse',artists:'Artists | Communiverse',artist:'Artist | Communiverse',signin:'Sign in | Communiverse',profile:'My profile | Communiverse',communities:'Communities | Communiverse'})[page])}}).on('script[src]',{element(el){if(el.getAttribute('src')==='/communiverse/_public/20261008-marketplace-1.js')el.remove()}}).on('meta[property="og:url"],link[rel="canonical"]',{element(el){el.setAttribute(el.tagName==='link'?'href':'content',u.origin+u.pathname)}});
 for(const c of Object.values(CLIPS))if(isPlug)rewrite=rewrite.on('.node[data-slug="'+c.slug+'"]',{element(el){el.setAttribute('data-name',c.name)}}).on('.node[data-slug="'+c.slug+'"] .cap b',{element(el){el.setInnerContent(c.name)}});
 if(isPlug&&initial?.importedNodes)rewrite=rewrite.on('#constellation',{element(el){el.append(initial.importedNodes,{html:true})}}).on('script[src],link[as=script]',{element(el){const key=el.tagName==='script'?'src':'href';if(el.getAttribute(key)==='/communiverse/_public/20261008-marketplace-1-focus.js')el.setAttribute(key,PREFIX+'-focus.js')}});
 if(clip)rewrite=rewrite.on('main',{element(el){el.append(`<section class="cv-social cv-ambassador-film"><h2>${h(clip.name)} · through their lens.</h2><video src="/communiverse/_public/media/ambassadors/20261008/${clip.file}.mp4" poster="/communiverse/_public/media/ambassadors/20261008/${clip.file}.jpg" controls playsinline preload="metadata" style="width:180px;max-width:100%;border-radius:22px"></video><a href="/communiverse/artist/?id=${clip.slug}">Follow ${h(clip.name)} ↗</a></section>`,{html:true})}});
 return rewrite.transform(new Response(html,{status:r.status,headers}));
}};
