import {session,body,json,limited} from './social-backend.js';
import {staffSession} from './social-workspace.js';
import {hash} from './market-members.js';
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status})};
const clean=(v,n)=>typeof v==='string'?v.trim().slice(0,n+1):'';
const random=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join('');
const escape=v=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const photoURL=(slug,version=1)=>'/communiverse/_public/avatar/'+encodeURIComponent(slug)+'?v='+version;
export async function identityPerson(request,env){
 const staff=await staffSession(request,env);let p;
 if(staff)p={...staff,kind:'staff',verified:true};
 else {const member=await session(request,env);if(!member)return null;const pref=await env.COMMUNIVERSE_DB.prepare('SELECT intent FROM cv_member_preferences WHERE member_id=?').bind(member.id).first();const link=await env.COMMUNIVERSE_DB.prepare("SELECT artist_id FROM cv_artist_accounts WHERE member_id=? LIMIT 1").bind(member.id).first();const artist=member.kind==='artist'||pref?.intent==='artist'||!!link;p={id:'member-'+member.id,member_id:member.id,profile_slug:'member-'+member.id,name:member.first_name,title:artist?'Artist':'Communiverse member',role:artist?'artist':'collector',kind:artist?'artist':'member',artist_id:link?.artist_id||'member-'+member.id,verified:!!member.email_verified_at};}
 const profile=await env.COMMUNIVERSE_DB.prepare('SELECT photo_version FROM cv_identity_profiles WHERE identity_id=?').bind(p.id).first();return {...p,photo:photoURL(p.profile_slug,profile?.photo_version||1)};
}
export async function publicIdentityMap(db){
 const profiles=(await db.prepare("SELECT p.profile_slug,p.photo_version FROM cv_identity_profiles p LEFT JOIN cv_members m ON p.identity_id='member-'||m.id LEFT JOIN cv_staff s ON s.id=p.identity_id WHERE (m.status='active' OR s.status='active')").all()).results;
 const map=profiles.reduce((out,p)=>{out[p.profile_slug]=photoURL(p.profile_slug,p.photo_version);return out},{});
 const aliases=(await db.prepare("SELECT a.artist_id,p.profile_slug,p.photo_version FROM cv_artist_accounts a JOIN cv_identity_profiles p ON p.identity_id='member-'||a.member_id JOIN cv_members m ON m.id=a.member_id AND m.status='active'").all()).results;
 for(const a of aliases)map[a.artist_id]=photoURL(a.profile_slug,a.photo_version);return map;
}
export async function identityAvatar(request,env){
 let slug;try{slug=decodeURIComponent(new URL(request.url).pathname.slice('/communiverse/_public/avatar/'.length))}catch{return new Response('Not found',{status:404})}if(!/^[a-zA-Z0-9-]{1,120}$/.test(slug))return new Response('Not found',{status:404});
 const db=env.COMMUNIVERSE_DB;let profile=await db.prepare('SELECT * FROM cv_identity_profiles WHERE profile_slug=?').bind(slug).first();if(!profile)profile=await db.prepare("SELECT p.* FROM cv_artist_accounts a JOIN cv_identity_profiles p ON p.identity_id='member-'||a.member_id WHERE a.artist_id=?").bind(slug).first();if(profile){const active=profile.identity_id.startsWith('member-')?await db.prepare("SELECT id FROM cv_members WHERE id=? AND status='active'").bind(profile.identity_id.slice(7)).first():await db.prepare("SELECT id FROM cv_staff WHERE id=? AND status='active'").bind(profile.identity_id).first();if(!active)return new Response('Not found',{status:404})}let name=profile?.name;
 if(!name&&/^member-[a-f0-9-]{36}$/.test(slug))name=(await db.prepare("SELECT first_name FROM cv_members WHERE id=? AND status='active'").bind(slug.slice(7)).first())?.first_name;
 if(!name)return new Response('Not found',{status:404});
 if(profile?.photo_key){const object=request.method==='HEAD'?await env.COMMUNIVERSE_MEDIA.head(profile.photo_key):await env.COMMUNIVERSE_MEDIA.get(profile.photo_key);if(object){const headers=new Headers({'Content-Type':profile.photo_type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox"});headers.set('ETag',object.httpEtag);headers.set('Content-Length',object.size);return new Response(request.method==='HEAD'?null:object.body,{headers});}}
 if(profile?.photo_url?.startsWith('/communiverse/_public/'))return new Response(null,{status:302,headers:{Location:profile.photo_url,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
 const initials=Array.from(name.trim()).slice(0,2).join('');return new Response(request.method==='HEAD'?null:`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 240 240"><circle cx="120" cy="120" r="120" fill="#e3eafa"/><text x="120" y="138" text-anchor="middle" font-family="Arial,sans-serif" font-size="56" fill="#253a5f">${escape(initials)}</text></svg>`,{headers:{'Content-Type':'image/svg+xml','Cache-Control':'no-store','X-Content-Type-Options':'nosniff'}});
}
async function contactFor(db,p){let c=await db.prepare('SELECT email,phone,email_verified,pending_email FROM cv_identity_contacts WHERE identity_id=?').bind(p.id).first();if(!c&&p.member_id){const m=await db.prepare('SELECT email,phone,email_verified_at FROM cv_members WHERE id=?').bind(p.member_id).first();if(m){await db.prepare('INSERT OR IGNORE INTO cv_identity_contacts(identity_id,email,phone,email_verified) VALUES(?,?,?,?)').bind(p.id,m.email,m.phone||'',m.email_verified_at?1:0).run();c={email:m.email,phone:m.phone||'',email_verified:m.email_verified_at?1:0,pending_email:''};}}return c||{email:'',phone:'',email_verified:0,pending_email:''};}
export async function identityAPI(request,env){const u=new URL(request.url),endpoint=u.pathname.replace(/\/$/,'').slice('/communiverse/api/identity/'.length),db=env.COMMUNIVERSE_DB;try{
 const p=await identityPerson(request,env);if(endpoint==='me'&&request.method==='GET')return json({person:p,contact:p?await contactFor(db,p):null});if(!p)fail('Sign in to update your profile.',401);
 if(endpoint==='contact'&&request.method==='POST'){const b=await body(request,1200);await limited(request,db,'identity-contact',6);const email=clean(b.email,254).toLowerCase(),phone=clean(b.phone,40);if(email&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||phone&&!/^\+?[0-9 ()-]{5,40}$/.test(phone))fail('Check your email address and phone number.');const old=await contactFor(db,p);if(!email||email===old.email){await db.prepare('INSERT INTO cv_identity_contacts(identity_id,email,phone,email_verified) VALUES(?,?,?,?) ON CONFLICT(identity_id) DO UPDATE SET phone=excluded.phone,updated_at=CURRENT_TIMESTAMP').bind(p.id,old.email,phone,old.email_verified).run();return json({ok:true,verification:old.email_verified?'verified':'unchanged'});}const t=random();await db.prepare('INSERT INTO cv_identity_contacts(identity_id,email,phone,email_verified,pending_email,confirmation_hash,confirmation_expires_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(identity_id) DO UPDATE SET phone=excluded.phone,pending_email=excluded.pending_email,confirmation_hash=excluded.confirmation_hash,confirmation_expires_at=excluded.confirmation_expires_at,updated_at=CURRENT_TIMESTAMP').bind(p.id,old.email,phone,old.email_verified,email,await hash(t),Date.now()+86400000).run();const link='https://espacios.me/communiverse/workspace/?contact_token='+t;try{await env.EMAIL.send({from:{email:'welcome@communiverse.espacios.me',name:'Communiverse'},to:email,subject:'Confirm your Communiverse meeting email',text:`Hi ${p.name},\nConfirm this address for workspace meeting invitations: ${link}\nYour private contact details never appear on your public profile.`,html:`<p>Hi ${escape(p.name)},</p><p><a href="${link}">Confirm your meeting email</a></p><p>Your private contact details never appear on your public profile.</p>`});}catch{fail('Your contact was saved, but the confirmation email could not be sent. Try saving again.',502);}return json({ok:true,verification:'sent'});}
 if(endpoint==='contact/confirm'&&request.method==='POST'){const b=await body(request,300);if(!/^[a-f0-9]{64}$/.test(b.token||''))fail('Open your confirmation email.');const r=await db.prepare('UPDATE cv_identity_contacts SET email=pending_email,pending_email=\'\',email_verified=1,confirmation_hash=NULL,confirmation_expires_at=NULL,updated_at=CURRENT_TIMESTAMP WHERE identity_id=? AND confirmation_hash=? AND confirmation_expires_at>?').bind(p.id,await hash(b.token),Date.now()).run();if(!r.meta.changes)fail('This confirmation has expired or belongs to another profile.',410);return json({ok:true});}
 if(endpoint==='photo'&&request.method==='POST'){if(!p.verified)fail('Confirm your email before sharing a profile photo.',403);if(request.headers.get('Origin')!==u.origin)fail('Open this form on Communiverse.',403);await limited(request,db,'identity-photo',12);const type=request.headers.get('Content-Type')?.split(';')[0],types={'image/jpeg':'jpg','image/png':'png','image/webp':'webp'};if(!types[type])fail('Choose a JPG, PNG or WebP image.',415);const reader=request.body?.getReader(),chunks=[];let size=0;if(reader)try{while(true){const r=await reader.read();if(r.done)break;size+=r.value.byteLength;if(size>3*1024*1024){await reader.cancel();fail('Choose a photo under 3 MB.',413)}chunks.push(r.value)}}finally{reader.releaseLock()}const bytes=new Uint8Array(size);let n=0;for(const c of chunks){bytes.set(c,n);n+=c.length}const png=bytes[0]===137&&bytes[1]===80&&bytes[2]===78&&bytes[3]===71,jpg=bytes[0]===255&&bytes[1]===216&&bytes[2]===255,webp=new TextDecoder().decode(bytes.slice(0,4))==='RIFF'&&new TextDecoder().decode(bytes.slice(8,12))==='WEBP';if(size<16||!(type==='image/jpeg'&&jpg||type==='image/png'&&png||type==='image/webp'&&webp))fail('The photo format could not be read.',415);const id=crypto.randomUUID(),key='profiles/'+p.id+'/'+id+'.'+types[type],sha=Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',bytes)),b=>b.toString(16).padStart(2,'0')).join('');await env.COMMUNIVERSE_MEDIA.put(key,bytes,{httpMetadata:{contentType:type},customMetadata:{identity_id:p.id,profile_slug:p.profile_slug,visibility:'public-profile',tags:'profile,portrait',sha256:sha,uploaded_at:new Date().toISOString()}});try{await db.batch([db.prepare('INSERT INTO cv_identity_profiles(identity_id,profile_slug,name,photo_key,photo_type,photo_version) VALUES(?,?,?,?,?,2) ON CONFLICT(identity_id) DO UPDATE SET photo_key=excluded.photo_key,photo_type=excluded.photo_type,photo_version=photo_version+1,updated_at=CURRENT_TIMESTAMP').bind(p.id,p.profile_slug,p.name,key,type),db.prepare('INSERT INTO cv_identity_photo_history(id,identity_id,object_key,content_type,bytes,sha256) VALUES(?,?,?,?,?,?)').bind(id,p.id,key,type,size,sha)]);}catch(e){await env.COMMUNIVERSE_MEDIA.delete(key);throw e}const profile=await db.prepare('SELECT photo_version FROM cv_identity_profiles WHERE identity_id=?').bind(p.id).first();return json({ok:true,photo:photoURL(p.profile_slug,profile.photo_version),version:profile.photo_version});}
 return json({error:'This profile action is unavailable.'},404);
 }catch(e){return json({error:e.status?e.message:'Your profile could not be updated. Try again.'},e.status||503)}}
