import {body,json,limited} from './social-backend.js';
import {studioActor,studioArtistAccess} from './social-artist-workspace.js';
import {COUNTRIES,CURRENCIES} from './social-booking.js';
import {photoURL} from './social-identity.js';
const fail=(message,status=400)=>{throw Object.assign(Error(message),{status})};
const clean=(v,n)=>typeof v==='string'?v.trim().slice(0,n+1):'';
export async function studioMedia(request,env){const id=new URL(request.url).pathname.split('/').pop();if(!/^[a-f0-9-]{36}$/.test(id||''))return new Response('Not found',{status:404});const work=await env.COMMUNIVERSE_DB.prepare("SELECT f.key AS object_key,f.content_type FROM cv_studio_public_work w JOIN cv_connect_files f ON f.id=w.file_id WHERE w.id=? AND w.status='published' AND f.status='active' AND NOT EXISTS(SELECT 1 FROM cv_members m WHERE m.status<>'active' AND (w.created_by='member-'||m.id OR w.artist_id='member-'||m.id OR f.uploader_id='member-'||m.id OR EXISTS(SELECT 1 FROM cv_artist_accounts a WHERE a.member_id=m.id AND a.artist_id=w.artist_id)))").bind(id).first();if(!work)return new Response('Not found',{status:404});const object=request.method==='HEAD'?await env.COMMUNIVERSE_MEDIA.head(work.object_key):await env.COMMUNIVERSE_MEDIA.get(work.object_key,{range:request.headers});if(!object)return new Response('Not found',{status:404});const headers=new Headers({'Content-Type':work.content_type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Accept-Ranges':'bytes','Content-Security-Policy':"default-src 'none'; sandbox"});headers.set('ETag',object.httpEtag);const ranged=request.headers.has('Range')&&object.range;if(ranged){const r=object.range;headers.set('Content-Range',`bytes ${r.offset}-${r.offset+r.length-1}/${object.size}`);headers.set('Content-Length',r.length)}else headers.set('Content-Length',object.size);return new Response(request.method==='HEAD'?null:object.body,{status:ranged?206:200,headers});}
export async function publishingAPI(request,env){const u=new URL(request.url),endpoint=u.pathname.replace(/\/$/,'').slice('/communiverse/api/studio/'.length),db=env.COMMUNIVERSE_DB;try{
 const p=await studioActor(request,env);if(!p)fail('Sign in to your studio or team workspace.',401);
 if(endpoint==='published'&&request.method==='GET'){await studioArtistAccess(db,p,u.searchParams.get('artist_id'));const works=(await db.prepare('SELECT id,artist_id,file_id,title,description,tags,kind,price,currency,status,created_at FROM cv_studio_public_work WHERE artist_id=? ORDER BY created_at DESC LIMIT 300').bind(u.searchParams.get('artist_id')).all()).results.map(w=>({...w,tags:JSON.parse(w.tags)}));return json({works});}
 if(endpoint==='publish'&&request.method==='POST'){const b=await body(request,5000);await limited(request,db,'studio-publish',40);const artist=await studioArtistAccess(db,p,b.artist_id,'write'),title=clean(b.title,140),description=clean(b.description,2000),tags=[...new Set((Array.isArray(b.tags)?b.tags:[]).filter(t=>typeof t==='string').map(t=>clean(t,50).toLowerCase()).filter(Boolean))].slice(0,20),currency=clean(b.currency,3)||'USD',price=b.price===''||b.price==null?null:Number(b.price);if(!title||title.length>140||description.length>2000||tags.some(t=>t.length>50)||!CURRENCIES.includes(currency)||price!==null&&(!Number.isFinite(price)||price<0||price>100000000)||!/^[a-f0-9-]{36}$/.test(b.requestId||''))fail('Check the work’s title, tags and price.');const file=await db.prepare("SELECT * FROM cv_connect_files WHERE id=? AND target=? AND status='active'").bind(b.file_id,'artist:'+b.artist_id).first();if(!file||!['image/jpeg','image/png','image/webp','video/mp4','video/quicktime','video/webm'].includes(file.content_type))fail('Choose a studio photo or video. Documents stay private.',415);const old=await db.prepare('SELECT id,artist_id,created_by FROM cv_studio_public_work WHERE request_key=?').bind(b.requestId).first();if(old){if(old.created_by!==p.id||old.artist_id!==b.artist_id)fail('Refresh the publishing form.',409);return json({ok:true,id:old.id},201)}const id=crypto.randomUUID(),kind=file.content_type.startsWith('video/')?'video':'work',src='/communiverse/_public/studio-media/'+id,business=await db.prepare('SELECT country,city,craft FROM cv_artist_business WHERE artist_id=?').bind(b.artist_id).first(),country=COUNTRIES.find(c=>c.id===(business?.country||artist.country)),region=({AE:'uae',SA:'saudi',PK:'pakistan',PH:'philippines',MY:'malaysia',CN:'china',CO:'colombia',PE:'peru',IN:'india',UZ:'uzbekistan'}[country?.id]||artist.region||'');const item={id,kind,title,description,artist:b.artist_id,artistName:artist.title,region,city:business?.city||artist.city||'',organizer:'Communiverse',image:kind==='video'?'':src,video:kind==='video'?src:undefined,source:'/communiverse/artist/?id='+encodeURIComponent(b.artist_id),tags:[...new Set([kind,business?.craft||artist.primaryCraft||'art',region,...tags].filter(Boolean))],price,currency,memberPost:true,uploaded:true,checkedAt:new Date().toISOString()};await db.batch([db.prepare('INSERT INTO cv_studio_public_work(id,artist_id,file_id,title,description,tags,kind,price,currency,request_key,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(id,b.artist_id,b.file_id,title,description,JSON.stringify(tags),kind,price,currency,b.requestId,p.id),db.prepare('INSERT INTO cv_catalog(id,kind,artist,region,data,tags,checked_at) VALUES(?,?,?,?,?,?,?)').bind(id,kind,b.artist_id,region,JSON.stringify(item),JSON.stringify(item.tags),item.checkedAt)]);return json({ok:true,id},201);}
 if(endpoint==='publish/hide'&&request.method==='POST'){const b=await body(request,500);await studioArtistAccess(db,p,b.artist_id,'write');const w=await db.prepare('SELECT id FROM cv_studio_public_work WHERE id=? AND artist_id=?').bind(b.id,b.artist_id).first();if(!w)fail('This shared work is unavailable.',404);await db.batch([db.prepare("UPDATE cv_studio_public_work SET status='hidden' WHERE id=?").bind(w.id),db.prepare('DELETE FROM cv_catalog WHERE id=?').bind(w.id)]);return json({ok:true});}
 return json({error:'This studio action is unavailable.'},404);
 }catch(e){if(String(e?.message).includes('The artist profile is no longer active'))return json({error:'This artist profile is no longer active.'},409);return json({error:e.status?e.message:'The work could not be shared. Try again.'},e.status||503)}}
