import {accountSession,accountToken} from './social-accounts.js';
import{body,json,limited}from'./social-backend.js';import {identityPerson,photoURL} from './social-identity.js';import{hash}from'./market-members.js';import IMAGES from './social-images.txt';
import{COUNTRIES,CURRENCIES}from'./social-booking.js';
const imageMap=JSON.parse(IMAGES);
export const TEAM=[['haseeb','Haseeb','ceo','CEO'],['elferah','Elferah','operations','Head of Operations'],['keiffer','Keiffer','ambassador-lead','Head of Ambassador Programme'],['hassan','Hassan','brand','Brand, UI & Socials'],['abel','Abel','platform','Platform & Marketplace'],['louis','Louis','ai','AI & Artisan Pipeline'],['alison','Alison','latam','LatAm & Colombia Hub'],['tariq','Tariq','advisor','Culture, Art & Events Advisor'],['viktoriya','Viktoriya','advisor','Culture, Art & Events Advisor'],['shakiba','Shakiba','advisor','Culture, Art & Events Advisor'],['luna','Luna','ambassador','Ambassador · Latin America'],['ammar','Ammar','ambassador','Ambassador'],['balo','Balo','ambassador','Ambassador']].map(([id,name,role,title])=>({id,name,role,title}));
const fail=(m,s=400)=>{throw Object.assign(Error(m),{status:s})},clean=(v,n)=>typeof v==='string'?v.trim().slice(0,n+1):'',uuid=v=>typeof v==='string'&&/^[a-f0-9-]{36}$/.test(v),token=()=>Array.from(crypto.getRandomValues(new Uint8Array(32)),x=>x.toString(16).padStart(2,'0')).join(''),admin=p=>['ceo','operations'].includes(p.role),pipelineEditor=p=>['ceo','operations','ambassador-lead','ai','latam'].includes(p.role);
export async function passwordHash(password,salt,iterations=100000){const bytes=new TextEncoder(),key=await crypto.subtle.importKey('raw',bytes.encode(password),{name:'PBKDF2'},false,['deriveBits']),result=await crypto.subtle.deriveBits({name:'PBKDF2',hash:'SHA-256',salt:bytes.encode(salt),iterations},key,256);return Array.from(new Uint8Array(result),b=>b.toString(16).padStart(2,'0')).join('');}
const equal=(a,b)=>{let d=a.length^b.length;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0;};
export async function staffSession(request,env){if(accountToken(request)){const a=await accountSession(request,env);return a?.staff_id?env.COMMUNIVERSE_DB.prepare("SELECT id,username,name,role,title,region,profile_slug FROM cv_staff WHERE id=? AND status='active'").bind(a.staff_id).first():null;}const t=request.headers.get('Cookie')?.match(/(?:^|;\s*)__Host-cv-workspace=([a-f0-9]{64})(?:;|$)/)?.[1];if(!t)return null;return env.COMMUNIVERSE_DB.prepare("SELECT p.id,p.username,p.name,p.role,p.title,p.region,p.profile_slug FROM cv_staff_sessions s JOIN cv_staff p ON p.id=s.staff_id WHERE s.hash=? AND s.expires_at>? AND p.status='active'").bind(await hash(t),Date.now()).first();}
export {admin};
export async function workspacePrincipal(request,env){const p=await identityPerson(request,env);return p||null;}
async function need(request,env){const p=await staffSession(request,env);if(!p)fail('Sign in to the team workspace.',401);return p;}
const projectScope=(p,alias='p')=>admin(p)?{sql:'1=1',params:[]}:{sql:`(${alias}.owner_id=? OR EXISTS(SELECT 1 FROM cv_project_members pm WHERE pm.project_id=${alias}.id AND pm.staff_id=?))`,params:[p.id,p.id]};
export async function project(db,id,p){const scope=projectScope(p),r=await db.prepare('SELECT p.* FROM cv_projects p WHERE p.id=? AND '+scope.sql).bind(id,...scope.params).first();if(!r)fail('This project is unavailable.',404);return r;}
export async function task(db,id,p){const r=await db.prepare('SELECT * FROM cv_tasks WHERE id=?').bind(id).first();if(!r)fail('This task is unavailable.',404);await project(db,r.project_id,p);return r;}
const requestVisible=(r,p)=>admin(p)||r.created_by===p.id||r.reviewer_id===p.id||(p.role==='ambassador-lead'&&['luna','ammar','balo'].includes(r.created_by))||(p.role==='latam'&&r.created_by==='luna');
async function teamRequest(db,id,p){const r=await db.prepare('SELECT * FROM cv_team_requests WHERE id=?').bind(id).first();if(!r||!requestVisible(r,p))fail('This request is unavailable.',404);return r;}
export async function targetAccess(db,id,p){const t=await db.prepare('SELECT project_id FROM cv_tasks WHERE id=?').bind(id).first();if(t){await project(db,t.project_id,p);return true}const pr=await db.prepare('SELECT id FROM cv_projects WHERE id=?').bind(id).first();if(pr){await project(db,id,p);return true}const r=await db.prepare('SELECT * FROM cv_team_requests WHERE id=?').bind(id).first();if(r&&requestVisible(r,p))return true;fail('This item is unavailable.',404);}
function activity(db,p,target,action,description=''){return db.prepare('INSERT INTO cv_workspace_activity(id,target,staff_id,action,description) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),target,p.id,action,description);}
function notification(db,staff,target,message){return db.prepare('INSERT INTO cv_workspace_notifications(id,staff_id,target,message) VALUES(?,?,?,?)').bind(crypto.randomUUID(),staff,target,message);}
async function taskMentions(db,p,projectId,target,text,previous=''){const tokens=value=>new Set((value.toLowerCase().match(/(?:^|\s)@([\p{L}\p{N}._-]+)/gu)||[]).map(t=>t.trim().slice(1)));const now=tokens(text),old=tokens(previous),staff=(await db.prepare("SELECT id,name,username,role FROM cv_staff WHERE status='active'").all()).results,out=[];for(const person of staff){if(person.id===p.id)continue;const names=[person.username,person.name.split(' ')[0]].map(n=>n.toLowerCase());if(!names.some(n=>now.has(n)&&!old.has(n)))continue;try{await project(db,projectId,person);out.push(notification(db,person.id,target,p.name+' mentioned you in a task.'))}catch{}}return out;}
const date=v=>!v||/^\d{4}-\d{2}-\d{2}$/.test(v)&&Number.isFinite(Date.parse(v))&&new Date(v).toISOString().slice(0,10)===v;
async function staffValid(db,id){if(!await db.prepare("SELECT id FROM cv_staff WHERE id=? AND status='active'").bind(id).first())fail('Choose a team member.');return id;}
const offset=u=>Math.max(0,Math.min(10000,Math.floor(Number(u.searchParams.get('offset')))||0));
export async function workspaceAPI(request,env){const u=new URL(request.url),endpoint=u.pathname.replace(/\/$/,'').slice('/communiverse/api/workspace/'.length),db=env.COMMUNIVERSE_DB;try{
 if(endpoint==='me'&&request.method==='GET'){const p=await workspacePrincipal(request,env);return json({person:p});}
 if(endpoint==='login'&&request.method==='POST'){const b=await body(request,1000),username=clean(b.username,60).toLowerCase(),password=clean(b.password,128);await limited(request,db,'workspace-login',20);if(!username||!password||password.length>128)fail('Enter your team username and password.');const p=await db.prepare("SELECT id,salt,password_hash,iterations FROM cv_staff WHERE lower(username)=? AND status='active'").bind(username).first(),derived=await passwordHash(password,p?.salt||'public-dummy-verification-salt',p?.iterations||100000);if(!p||!equal(derived,p.password_hash))fail('Check your username and password.',401);const t=token();await db.batch([db.prepare('DELETE FROM cv_staff_sessions WHERE expires_at<?').bind(Date.now()),db.prepare('INSERT INTO cv_staff_sessions(hash,staff_id,expires_at) VALUES(?,?,?)').bind(await hash(t),p.id,Date.now()+14*86400000)]);return json({ok:true},200,{'Set-Cookie':'__Host-cv-workspace='+t+'; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=1209600'});}
 const p=await need(request,env);
 if(endpoint==='logout'&&request.method==='POST'){await body(request,100);const t=request.headers.get('Cookie')?.match(/__Host-cv-workspace=([a-f0-9]{64})/)?.[1];if(t)await db.prepare('DELETE FROM cv_staff_sessions WHERE hash=?').bind(await hash(t)).run();return json({ok:true},200,{'Set-Cookie':'__Host-cv-workspace=; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=0'});}
 if(endpoint==='password'&&request.method==='POST'){const b=await body(request,1000);await limited(request,db,'workspace-password',5);const password=clean(b.password,128),old=await db.prepare('SELECT salt,password_hash,iterations FROM cv_staff WHERE id=?').bind(p.id).first();if(!equal(await passwordHash(clean(b.currentPassword,128),old.salt,old.iterations),old.password_hash))fail('Check your current password.',401);if(password.length<8||password.length>128)fail('Choose a password with at least 8 characters.');const salt=token();await db.batch([db.prepare('UPDATE cv_staff SET salt=?,password_hash=?,iterations=100000 WHERE id=?').bind(salt,await passwordHash(password,salt),p.id),db.prepare('DELETE FROM cv_staff_sessions WHERE staff_id=?').bind(p.id),activity(db,p,p.id,'password-changed')]);return json({ok:true},200,{'Set-Cookie':'__Host-cv-workspace=; Path=/; Secure; HttpOnly; SameSite=Lax; Max-Age=0'});}
 if(endpoint==='overview'&&request.method==='GET'){
 const teamProfiles=(await db.prepare("SELECT id,name,username,role,title,region,profile_slug FROM cv_staff WHERE status='active'").all()).results;const scope=projectScope(p),projects=(await db.prepare("SELECT p.id,p.title,p.description,p.owner_id,p.status,p.due_date,p.updated_at,(SELECT count(*) FROM cv_tasks t WHERE t.project_id=p.id AND t.status<>'archived') total,(SELECT count(*) FROM cv_tasks t WHERE t.project_id=p.id AND t.status='done') done,(SELECT count(*) FROM cv_tasks t WHERE t.project_id=p.id AND t.status='blocked') blocked FROM cv_projects p WHERE p.status<>'archived' AND "+scope.sql+' ORDER BY p.updated_at DESC LIMIT 100').bind(...scope.params).all()).results;
 const tasks=(await db.prepare("SELECT t.* FROM cv_tasks t JOIN cv_projects p ON p.id=t.project_id WHERE t.status<>'archived' AND p.status<>'archived' AND "+scope.sql+' ORDER BY t.due_date=\'\',t.due_date,t.created_at DESC LIMIT 1000').bind(...scope.params).all()).results;
 const requests=(await db.prepare('SELECT * FROM cv_team_requests ORDER BY updated_at DESC LIMIT 500').all()).results.filter(r=>requestVisible(r,p));const unread=(await db.prepare('SELECT id,target,message,created_at FROM cv_workspace_notifications WHERE staff_id=? AND read_at IS NULL ORDER BY created_at DESC LIMIT 50').bind(p.id).all()).results;const activityRows=(await db.prepare('SELECT id,target,staff_id,action,description,created_at FROM cv_workspace_activity ORDER BY created_at DESC LIMIT 300').all()).results.filter(a=>projects.some(x=>x.id===a.target)||tasks.some(x=>x.id===a.target)||requests.some(x=>x.id===a.target)).slice(0,40);
 return json({person:{...p,photo:photoURL(p.profile_slug)},team:teamProfiles.map(t=>({...t,profile_slug:teamProfiles.find(x=>x.id===t.id)?.profile_slug||'',photo:photoURL(teamProfiles.find(x=>x.id===t.id)?.profile_slug||'')})),projects,tasks,requests,notifications:unread,activity:activityRows,permissions:{admin:admin(p),pipeline:pipelineEditor(p),schedule:admin(p),approval:p.role==='ceo'},groupRequests:admin(p)?(await db.prepare('SELECT id,name,country,city,craft,artist_id,date,people,currency,guide_usd,status,assigned_to,created_at FROM cv_group_requests ORDER BY created_at DESC LIMIT 100').all()).results:[]});
 }
 if(endpoint==='projects'&&request.method==='GET'){const id=clean(u.searchParams.get('id'),100);if(id){const pr=await project(db,id,p),members=(await db.prepare('SELECT staff_id FROM cv_project_members WHERE project_id=?').bind(id).all()).results.map(x=>x.staff_id),tasks=(await db.prepare("SELECT * FROM cv_tasks WHERE project_id=? AND status<>'archived' ORDER BY created_at DESC").bind(id).all()).results;return json({project:pr,members,tasks,canManage:admin(p)||pr.owner_id===p.id})}const scope=projectScope(p);return json({projects:(await db.prepare('SELECT p.* FROM cv_projects p WHERE '+scope.sql+' ORDER BY updated_at DESC LIMIT 100').bind(...scope.params).all()).results});}
 if(endpoint==='projects'&&request.method==='POST'){
 const b=await body(request,5000);await limited(request,db,'workspace-project',30);const title=clean(b.title,120),description=clean(b.description,2000),due=clean(b.due_date,10),members=[...new Set(Array.isArray(b.members)?b.members:[])];if(!title||title.length>120||description.length>2000||!date(due))fail('Check the project name and date.');for(const id of members)await staffValid(db,id);
 if(b.id){const pr=await project(db,b.id,p);if(!admin(p)&&pr.owner_id!==p.id)fail('Only the project owner can change its details.',403);if(!['active','paused','done','archived'].includes(b.status))fail('Choose a project state.');await db.batch([db.prepare('UPDATE cv_projects SET title=?,description=?,due_date=?,status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(title,description,due,b.status,pr.id),db.prepare('DELETE FROM cv_project_members WHERE project_id=?').bind(pr.id),...members.map(id=>db.prepare('INSERT INTO cv_project_members(project_id,staff_id) VALUES(?,?)').bind(pr.id,id)),activity(db,p,pr.id,'project-updated',title)]);return json({ok:true,id:pr.id});}
 if(!uuid(b.requestId))fail('Refresh the form.');const old=await db.prepare('SELECT id,owner_id FROM cv_projects WHERE request_key=?').bind(b.requestId).first();if(old){if(old.owner_id!==p.id)fail('Refresh the form.',409);return json({ok:true,id:old.id},201)}const id=crypto.randomUUID();await db.batch([db.prepare('INSERT INTO cv_projects(id,title,description,owner_id,due_date,request_key) VALUES(?,?,?,?,?,?)').bind(id,title,description,p.id,due,b.requestId),...members.map(m=>db.prepare('INSERT INTO cv_project_members(project_id,staff_id) VALUES(?,?)').bind(id,m)),activity(db,p,id,'project-created',title)]);return json({ok:true,id},201);
 }
 if(endpoint==='tasks'&&request.method==='GET'){const t=await task(db,u.searchParams.get('id'),p);return json({task:t,canApprove:p.role==='ceo',assets:(await db.prepare("SELECT id,name,bytes,content_type,staff_id,created_at FROM cv_workspace_assets WHERE target=? AND status='active' ORDER BY created_at DESC").bind(t.id).all()).results,comments:(await db.prepare('SELECT * FROM cv_workspace_comments WHERE target=? ORDER BY created_at LIMIT 200').bind(t.id).all()).results,activity:(await db.prepare('SELECT * FROM cv_workspace_activity WHERE target=? ORDER BY created_at DESC LIMIT 50').bind(t.id).all()).results});}
 if(endpoint==='tasks'&&request.method==='POST'){
 const b=await body(request,6000);await limited(request,db,'workspace-task',120);const title=clean(b.title,140),description=clean(b.description,2500),due=clean(b.due_date,10),status=['todo','doing','blocked','review','done','archived'].includes(b.status)?b.status:'todo',priority=['low','normal','high','urgent'].includes(b.priority)?b.priority:'normal',owner=await staffValid(db,b.owner_id||p.id);if(!title||title.length>140||description.length>2500||!date(due))fail('Check the task name and date.');
 if(b.id){const t=await task(db,b.id,p);if(t.approval_required&&status==='done'&&p.role!=='ceo')fail('Haseeb signs off on this task.',403);if(t.approval_required&&!b.approval_required&&p.role!=='ceo')fail('Haseeb signs off on approval changes.',403);const pr=await project(db,t.project_id,p);if(!admin(p)&&![t.owner_id,t.created_by,pr.owner_id].includes(p.id))fail('Only its owner, creator or project lead can edit this task.',403);if(owner!==pr.owner_id&&!await db.prepare('SELECT staff_id FROM cv_project_members WHERE project_id=? AND staff_id=?').bind(pr.id,owner).first()&&!admin(await db.prepare('SELECT role FROM cv_staff WHERE id=?').bind(owner).first()))fail('Add that person to the project first.');const result=await db.prepare('UPDATE cv_tasks SET title=?,description=?,owner_id=?,status=?,priority=?,due_date=?,approval_required=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND version=?').bind(title,description,owner,status,priority,due,b.approval_required?1:0,t.id,Number(b.version)).run();if(!result.meta.changes)fail('This task changed. Open it again to see the latest version.',409);await db.batch([...await taskMentions(db,p,t.project_id,t.id,description,t.description),activity(db,p,t.id,'task-updated',title+' · '+status),db.prepare('UPDATE cv_projects SET updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(t.project_id),...(owner!==t.owner_id?[notification(db,owner,t.id,p.name+' assigned you '+title)]:[])]);return json({ok:true,id:t.id});}
 const pr=await project(db,b.project_id,p);if(!uuid(b.requestId))fail('Refresh the form.');if(owner!==pr.owner_id&&!await db.prepare('SELECT staff_id FROM cv_project_members WHERE project_id=? AND staff_id=?').bind(pr.id,owner).first()&&!admin(await db.prepare('SELECT role FROM cv_staff WHERE id=?').bind(owner).first()))fail('Add that person to the project first.');if(b.approval_required&&status==='done'&&p.role!=='ceo')fail('Haseeb signs off on this task.',403);const old=await db.prepare('SELECT id,created_by FROM cv_tasks WHERE request_key=?').bind(b.requestId).first();if(old){if(old.created_by!==p.id)fail('Refresh the form.',409);return json({ok:true,id:old.id},201)}const id=crypto.randomUUID();await db.batch([...await taskMentions(db,p,pr.id,id,description),db.prepare('INSERT INTO cv_tasks(id,project_id,title,description,owner_id,created_by,status,priority,due_date,approval_required,request_key) VALUES(?,?,?,?,?,?,?,?,?,?,?)').bind(id,pr.id,title,description,owner,p.id,status,priority,due,b.approval_required?1:0,b.requestId),activity(db,p,id,'task-created',title),db.prepare('UPDATE cv_projects SET updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(pr.id),...(owner!==p.id?[notification(db,owner,id,p.name+' assigned you '+title)]:[])]);return json({ok:true,id},201);
 }
 if(endpoint==='requests'&&request.method==='GET'){const r=await teamRequest(db,u.searchParams.get('id'),p);return json({request:r,assets:(await db.prepare("SELECT id,name,bytes,staff_id,content_type FROM cv_workspace_assets WHERE target=? AND status='active'").bind(r.id).all()).results,comments:(await db.prepare('SELECT * FROM cv_workspace_comments WHERE target=? ORDER BY created_at LIMIT 200').bind(r.id).all()).results,activity:(await db.prepare('SELECT * FROM cv_workspace_activity WHERE target=? ORDER BY created_at DESC LIMIT 50').bind(r.id).all()).results});}
 if(endpoint==='requests'&&request.method==='POST'){
 const b=await body(request,6000);await limited(request,db,'workspace-request',30);const title=clean(b.title,140),text=clean(b.body,2500),kind=['resource','kit','training','pay','contract','ambassador','access','travel','asset','subscription','other'].includes(b.kind)?b.kind:'resource',amount=b.amount===''||b.amount===undefined||b.amount===null?null:Number(b.amount),currency=clean(b.currency,3)||'AED';if(!title||title.length>140||!text||text.length>2500||amount!==null&&(!Number.isFinite(amount)||amount<0||amount>100000000)||!CURRENCIES.includes(currency)||!uuid(b.requestId))fail('Check your request details.');const old=await db.prepare('SELECT id,created_by FROM cv_team_requests WHERE request_key=?').bind(b.requestId).first();if(old){if(old.created_by!==p.id)fail('Refresh the form.',409);return json({ok:true,id:old.id},201)}const reviewer=p.role==='ambassador'?'keiffer':p.role==='ai'||['pay','contract','ambassador','travel','kit','asset','subscription'].includes(kind)||amount!==null?'haseeb':'elferah',stage=reviewer==='keiffer'?'keiffer':reviewer==='haseeb'?'approval':'operations',id=crypto.randomUUID();await db.batch([db.prepare('INSERT INTO cv_team_requests(id,request_key,created_by,title,body,kind,stage,reviewer_id,amount,currency) VALUES(?,?,?,?,?,?,?,?,?,?)').bind(id,b.requestId,p.id,title,text,kind,stage,reviewer,amount,currency),activity(db,p,id,'request-created',title),notification(db,reviewer,id,p.name+' sent a request: '+title),...(reviewer!=='elferah'&&p.role!=='ambassador'?[notification(db,'elferah',id,p.name+' sent a request for '+reviewer+' review: '+title)]:[])]);return json({ok:true,id},201);
 }
 if(endpoint==='requests/action'&&request.method==='POST'){
 const b=await body(request,2500),r=await teamRequest(db,b.id,p),note=clean(b.note,1500);await limited(request,db,'workspace-request-action',60);if(note.length>1500)fail('Shorten the decision note.');let stage,reviewer,action=b.action;if(action==='forward'&&r.stage==='keiffer'&&p.id==='keiffer'){stage='approval';reviewer='haseeb'}else if(action==='approve'&&r.stage==='approval'&&p.role==='ceo'){stage='approved';reviewer='elferah'}else if(action==='complete'&&['approved','operations'].includes(r.stage)&&p.role==='operations'){stage='done';reviewer='elferah'}else if(action==='reject'&&['keiffer','approval','operations'].includes(r.stage)&&r.reviewer_id===p.id){stage='rejected';reviewer=r.reviewer_id}else if(action==='needs-info'&&['keiffer','approval','operations'].includes(r.stage)&&r.reviewer_id===p.id){stage='needs-info';reviewer=r.created_by}else if(action==='resubmit'&&r.stage==='needs-info'&&r.created_by===p.id){const creator=await db.prepare('SELECT role FROM cv_staff WHERE id=?').bind(r.created_by).first();reviewer=creator.role==='ambassador'?'keiffer':creator.role==='ai'||r.amount!==null||['pay','contract','ambassador','travel','kit','asset','subscription'].includes(r.kind)?'haseeb':'elferah';stage=reviewer==='keiffer'?'keiffer':reviewer==='haseeb'?'approval':'operations'}else fail('That action belongs to the next person in the approval path.',403);
 if(['reject','needs-info'].includes(action)&&!note)fail('Add a short explanation.');const changed=await db.prepare('UPDATE cv_team_requests SET stage=?,reviewer_id=?,decision_note=?,version=version+1,updated_at=CURRENT_TIMESTAMP WHERE id=? AND version=? AND stage=?').bind(stage,reviewer,note,r.id,Number(b.version),r.stage).run();if(!changed.meta.changes)fail('This request changed. Open it again to see the latest stage.',409);await db.batch([activity(db,p,r.id,'request-'+action,note),notification(db,r.created_by,r.id,p.name+' updated your request: '+stage),...(reviewer!==r.created_by?[notification(db,reviewer,r.id,r.title+' is ready for your '+(stage==='approval'?'approval':'next step'))]:[]),...(action==='forward'?[notification(db,'elferah',r.id,'Keiffer forwarded '+r.title+' to Haseeb for approval')]:[])]);return json({ok:true,id:r.id,stage});
 }
 if(endpoint==='comments'&&request.method==='POST'){const b=await body(request,5000);await targetAccess(db,b.target,p);await limited(request,db,'workspace-comment',120);const text=clean(b.body,2000);if(!text||text.length>2000||!uuid(b.requestId))fail('Add a short update.');const old=await db.prepare('SELECT staff_id FROM cv_workspace_comments WHERE request_key=?').bind(b.requestId).first();if(old){if(old.staff_id!==p.id)fail('Refresh the form.',409);return json({ok:true})}await db.batch([db.prepare('INSERT INTO cv_workspace_comments(id,target,staff_id,body,request_key) VALUES(?,?,?,?,?)').bind(crypto.randomUUID(),b.target,p.id,text,b.requestId),activity(db,p,b.target,'comment-added',text.slice(0,120))]);return json({ok:true},201);}
 if(endpoint==='notifications/read'&&request.method==='POST'){await body(request,100);await db.prepare('UPDATE cv_workspace_notifications SET read_at=CURRENT_TIMESTAMP WHERE staff_id=? AND read_at IS NULL').bind(p.id).run();return json({ok:true});}
 if(endpoint==='pipeline'&&request.method==='GET'){const artists=(await db.prepare("SELECT data FROM cv_catalog WHERE kind='artist' LIMIT 1000").all()).results.map(x=>JSON.parse(x.data));const states=(await db.prepare('SELECT * FROM cv_artist_pipeline LIMIT 1000').all()).results;return json({artists:artists.map(a=>({id:a.id,title:a.title,city:a.city,region:a.region,image:imageMap[a.image]?.variants[1].url||a.image,tags:a.tags,state:states.find(s=>s.artist_id===a.id)||{stage:'discovered',owner_id:'louis',version:0,notes:''}})),canEdit:pipelineEditor(p)});}
 if(endpoint==='pipeline'&&request.method==='POST'){if(!pipelineEditor(p))fail('The artisan programme team updates this pipeline.',403);const b=await body(request,4000),notes=clean(b.notes,1500);if(!['discovered','contacted','filming','review','verified','published','paused'].includes(b.stage)||notes.length>1500||!await db.prepare("SELECT id FROM cv_catalog WHERE id=? AND kind='artist'").bind(b.id).first())fail('Check the artist and pipeline stage.');await staffValid(db,b.owner_id);if(['verified','published'].includes(b.stage)&&!['ceo','operations','ambassador-lead'].includes(p.role))fail('Keiffer, Haseeb or Elferah verifies artists before publishing.',403);const exists=await db.prepare('SELECT version FROM cv_artist_pipeline WHERE artist_id=?').bind(b.id).first();if(exists&&exists.version!==Number(b.version))fail('This artist changed. Refresh the pipeline.',409);await db.batch([db.prepare('INSERT INTO cv_artist_pipeline(artist_id,stage,owner_id,notes) VALUES(?,?,?,?) ON CONFLICT(artist_id) DO UPDATE SET stage=excluded.stage,owner_id=excluded.owner_id,notes=excluded.notes,version=version+1,updated_at=CURRENT_TIMESTAMP').bind(b.id,b.stage,b.owner_id,notes),activity(db,p,b.id,'artist-pipeline-updated',b.stage)]);return json({ok:true});}
 if(endpoint==='sessions'&&request.method==='GET'){if(!admin(p))fail('Operations manages session requests.',403);return json({requests:(await db.prepare('SELECT * FROM cv_group_requests ORDER BY created_at DESC LIMIT 200').all()).results,slots:(await db.prepare('SELECT * FROM cv_workshop_slots ORDER BY start_at DESC LIMIT 200').all()).results});}
 if(endpoint==='sessions/action'&&request.method==='POST'){if(!admin(p))fail('Operations manages session requests.',403);const b=await body(request,1000);if(!['new','reviewing','confirmed','closed'].includes(b.status))fail('Choose a request state.');await staffValid(db,b.assigned_to);const r=await db.prepare('SELECT id FROM cv_group_requests WHERE id=?').bind(b.id).first();if(!r)fail('This session request is unavailable.',404);await db.batch([db.prepare('UPDATE cv_group_requests SET status=?,assigned_to=? WHERE id=?').bind(b.status,b.assigned_to,b.id),activity(db,p,b.id,'session-request-updated',b.status)]);return json({ok:true});}
 if(endpoint==='slots'&&request.method==='POST'){if(!admin(p))fail('Operations publishes confirmed session dates.',403);const b=await body(request,2500),country=COUNTRIES.find(c=>c.id===b.country),city=clean(b.city,100),capacity=Number(b.capacity),price=Number(b.price_usd),start=clean(b.start_at,40),end=clean(b.end_at,40),timezone=clean(b.timezone,80)||'UTC';try{new Intl.DateTimeFormat('en',{timeZone:timezone})}catch{fail('Choose a valid time zone.')}if(b.confirmed!==true||!country||!city||city.length>100||!Number.isInteger(capacity)||capacity<1||capacity>40||!Number.isFinite(price)||price<0||price>100000||!Number.isFinite(Date.parse(start))||!Number.isFinite(Date.parse(end))||Date.parse(start)<=Date.now()||Date.parse(end)<=Date.parse(start)||!await db.prepare("SELECT id FROM cv_catalog WHERE id=? AND kind='artist'").bind(b.artist_id).first())fail('Confirm the artist’s date, price and capacity before publishing.');const id=uuid(b.id)?b.id:crypto.randomUUID();await db.batch([db.prepare('INSERT INTO cv_workshop_slots(id,artist_id,country,city,start_at,end_at,timezone,capacity,price_usd,confirmed_by) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET country=excluded.country,city=excluded.city,start_at=excluded.start_at,end_at=excluded.end_at,timezone=excluded.timezone,capacity=excluded.capacity,price_usd=excluded.price_usd,confirmed_by=excluded.confirmed_by,status=\'active\'').bind(id,b.artist_id,country.id,city,new Date(start).toISOString(),new Date(end).toISOString(),timezone,capacity,price,p.id),activity(db,p,id,'session-date-published',city)]);return json({ok:true,id},201);}
 if(endpoint==='slots/remove'&&request.method==='POST'){if(!admin(p))fail('Operations manages session dates.',403);const b=await body(request,500);await db.batch([db.prepare("UPDATE cv_workshop_slots SET status='hidden' WHERE id=?").bind(b.id),activity(db,p,b.id,'session-date-hidden')]);return json({ok:true});}
 if(endpoint==='assets'&&request.method==='GET'){const target=clean(u.searchParams.get('target'),100);await targetAccess(db,target,p);return json({assets:(await db.prepare("SELECT id,name,bytes,content_type,staff_id,created_at FROM cv_workspace_assets WHERE target=? AND status='active' ORDER BY created_at DESC LIMIT 100").bind(target).all()).results});}
 if(endpoint==='assets'&&request.method==='POST'){
 if(request.headers.get('Origin')!==u.origin)fail('Open the workspace upload form.',403);const target=clean(u.searchParams.get('target'),100),name=clean(u.searchParams.get('name'),180).replace(/[\/\\\u0000-\u001f]/g,'-');await targetAccess(db,target,p);await limited(request,db,'workspace-upload',40);if(!name||name.length>180)fail('Give the file a short name.');const reader=request.body?.getReader();if(!reader)fail('Choose a file.');const chunks=[];let n=0;try{while(true){const q=await reader.read();if(q.done)break;n+=q.value.length;if(n>20*1024*1024){await reader.cancel();fail('Choose a file under 20 MB.',413)}chunks.push(q.value)}}finally{reader.releaseLock()}if(!n)fail('Choose a file with content.');const bytes=new Uint8Array(n);let i=0;for(const b of chunks){bytes.set(b,i);i+=b.length}const header=new TextDecoder().decode(bytes.slice(0,12)),contentType=bytes[0]===255&&bytes[1]===216?'image/jpeg':bytes[0]===137&&bytes[1]===80?'image/png':header.startsWith('RIFF')&&header.slice(8)==='WEBP'?'image/webp':header.startsWith('%PDF')?'application/pdf':'application/octet-stream',id=crypto.randomUUID(),key='workspace/'+target+'/'+id;await env.COMMUNIVERSE_MEDIA.put(key,bytes,{httpMetadata:{contentType}});try{await db.batch([db.prepare('INSERT INTO cv_workspace_assets(id,target,staff_id,name,key,content_type,bytes) VALUES(?,?,?,?,?,?,?)').bind(id,target,p.id,name,key,contentType,n),activity(db,p,target,'file-uploaded',name)])}catch(e){await env.COMMUNIVERSE_MEDIA.delete(key);throw e}return json({ok:true,id},201);
 }
 if(endpoint==='assets/remove'&&request.method==='POST'){const b=await body(request,500),a=await db.prepare("SELECT * FROM cv_workspace_assets WHERE id=? AND status='active'").bind(b.id).first();if(!a)fail('This file is unavailable.',404);await targetAccess(db,a.target,p);if(a.staff_id!==p.id&&!admin(p))fail('Only its uploader or operations can hide the file.',403);await db.batch([db.prepare("UPDATE cv_workspace_assets SET status='hidden' WHERE id=?").bind(a.id),activity(db,p,a.target,'file-hidden',a.name)]);return json({ok:true});}
 if(endpoint==='assets/file'&&['GET','HEAD'].includes(request.method)){const a=await db.prepare("SELECT * FROM cv_workspace_assets WHERE id=? AND status='active'").bind(u.searchParams.get('id')).first();if(!a)fail('This file is unavailable.',404);await targetAccess(db,a.target,p);const object=request.method==='HEAD'?await env.COMMUNIVERSE_MEDIA.head(a.key):await env.COMMUNIVERSE_MEDIA.get(a.key,{range:request.headers});if(!object)fail('This file is unavailable.',404);const headers=new Headers({'Content-Type':a.content_type,'Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(a.name),'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Content-Security-Policy':"default-src 'none'; sandbox",'Accept-Ranges':'bytes'});if(object.range){headers.set('Content-Range',`bytes ${object.range.offset}-${object.range.offset+object.range.length-1}/${object.size}`);headers.set('Content-Length',object.range.length)}else headers.set('Content-Length',object.size);return new Response(request.method==='HEAD'?null:object.body,{status:object.range?206:200,headers});}
 return json({error:'Not found'},404);
}catch(e){if(!e.status)console.error('Communiverse workspace unavailable',e.code||'service');return json({error:e.status?e.message:'Unable to complete this right now. Please try again.'},e.status||503)}}
